### ISSUE TITLE
Flathub not pre-configured as repo for Flatpak on desktop

### ISSUE THREAD

**Issue by krisdale** [clearlinux/distribution#645] opened 2019-04-26 21:41 UTC
**Describe the bug**
Flatpak should be installed and the Flathub repository pre-configured by default with the desktop bundle (as described on the FlatHub Clear Linux quick setup guide: https://flatpak.org/setup/Clear%20Linux/). 

Flatpak is installed with the Desktop bundle, but there is no repository pre-configured. In order to use Flatpak, I had to manually set the repository with 
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

**To Reproduce**
1. With desktop installed, open terminal
2. Try to install a Flatpak e.g. `sudo flatpak install flathub net.sourceforge.chromium-bsu`
3. Will get an error: Remote "flathub" not found

**Expected behavior**
With the desktop bundle installed, I should be able to install a flatpak without having to configure the remote.

**Screenshots**
![Screenshot from 2019-04-26 23-21-17-flatpak- remote-not-found](https://user-images.githubusercontent.com/41927943/56837917-136b5c00-6831-11e9-95ea-e73101d07a05.png)

![Screenshot from 2019-04-26 22-03-21-flatpak remote](https://user-images.githubusercontent.com/41927943/56834555-89b69100-6826-11e9-932f-4ee43dc4c0a5.png)

**Comment by mrkz** [comment] 2019-04-29 16:41
hello @krisdale 

Are you running your system behind a proxy? The flathub setup may fail due to proxy funkiness.

What's the output of the following commands (using gnome-terminal):
```
$ flatpak remotes -v
```

and

```
$ /usr/libexec/clr-init-flathub-repo
```

Should any network issue be present, the last command should timeout in ~60s

**Comment by mrkz** [comment] 2019-04-29 22:56
I just tried this on a fresh install at home (no proxy environment) and I had no issues having flathub initialized:
```
$ flatpak remotes
Name    Options
flathub user   
$ flatpak remote-list --system

$ flatpak remote-list --user
Name    Options
flathub   
``` 

Worth to mention that the flathub repository is installed as a user repository instead of system's one.

![gnome-software](https://user-images.githubusercontent.com/978752/56932094-06a46d80-6aa8-11e9-9104-0aed6d224966.png)

**Comment by pceiley** [comment] 2019-05-06 22:53
Yes, this is occurring because you are executing flatpak as root and Clear sets up the user repositories only. I'm not sure why the system flathub repo is not configured by default on Clear. Is anyone able to shed light on this?

**Comment by mrkz** [comment] 2019-05-07 16:25
>I'm not sure why the system flathub repo is not configured by default on Clear. Is anyone able to shed light on this?

We decided to provide  Flathub repository at user level instead of system level (so flatpak apps are installed and available on a user-level basis).

If you think that we should provide Flathub at system level instead of user level, please open a new issue with the `question` tag, so we can start the conversation about that there :-)

**Comment by mrkz** [comment] 2019-05-14 15:15
I'm closing this issue as I've been unable to reproduce (i.e: I see Flatpak's `flathub` repository correctly configured as a user repository). Should you face the same issue, please open a new bug with the steps you followed to face the issue.

Thanks for your contribution!

**Closed by mrkz** 2019-05-14 15:15 UTC
Labels: bug, desktop, high priority
