### ISSUE TITLE
Nvidia 390.132 not compiling with Kernel 5.5.x

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1737] opened 2020-02-12 17:16 UTC
Just updated to latest swupd and the nvidia driver does not build anymore:

![20200212_165635](https://user-images.githubusercontent.com/55597745/74359484-47613f00-4dbb-11ea-860f-88e466ba391e.jpg)

![20200212_165837](https://user-images.githubusercontent.com/55597745/74359486-492b0280-4dbb-11ea-87b7-d8c9ac0889df.jpg)

**Comment by 0xA1B2** [comment] 2020-02-12 17:17
It also does not build anymore when I go back to the previous 5.4 kernel. Same errors.

**Comment by 0xA1B2** [comment] 2020-02-12 17:24
https://devtalk.nvidia.com/default/topic/1071394/linux/390-132-fails-to-build-on-kernel-5-5-using-clear-linux/?offset=3#5427974

**Comment by ahkok** [comment] 2020-02-12 18:10
Duplicate of #1725

**Closed by ahkok** 2020-02-12 18:10 UTC
Labels: bug, new
