### ISSUE TITLE
R packages do not seem to get stripped right

### ISSUE THREAD

**Issue by fenrus75** [clearlinux/distribution#26] opened 2018-03-23 13:24 UTC
7:47:01 PM	fenrus  -rwxr-xr-x  2 root root  83M Mar 17 04:20 rstanarm.so
7:47:09 PM	fenrus  (so huge since we ship 3 of these)
7:47:19 PM	fenrus   strip rstanarm.so
7:47:24 PM	fenrus  -rwxr-xr-x  2 root root 6.2M Mar 23 02:46 rstanarm.so
7:48:25 PM	fenrus  so we somehow we ain't stripping the paint of the R stuff
7:48:29 PM	fenrus  which makes it a bit big
7:51:43 PM	fenrus  # du -sh /usr/lib64/R/library 1.5G    /usr/lib64/R/library
7:52:07 PM	fenrus   strip library/*/libs/*so
7:52:14 PM	fenrus  # du -sh /usr/lib64/R/library 795M    /usr/lib64/R/library

**Comment by bryteise** [comment] 2018-06-18 17:58
This is still an issue.

**Comment by phmccarty** [comment] 2019-02-28 20:20
I have started work on this issue.

**Comment by phmccarty** [comment] 2019-03-02 04:46
Root caused to be a problem with the way R package tests are executed.

Autospec PR opened: https://github.com/clearlinux/autospec/pull/345

**Comment by phmccarty** [comment] 2019-03-18 05:29
The autospec PR (https://github.com/clearlinux/autospec/pull/345) has been merged, and autospec has been rerun on all R packages to adopt the changes. Closing.

**Closed by phmccarty** 2019-03-18 05:29 UTC
Labels: bug
