### ISSUE TITLE
kde-desktop not working properly

### ISSUE THREAD

**Issue by comptekki** [clearlinux/distribution#2526] opened 2022-01-18 23:21 UTC
kde-desktop no longer shows the menu panel (the bar with the application launcher, date/time, bluetooth, etc.)  It appears plasmashell is no longer runner at login.  Applications are still showing from previous session being saved and the alt-spacebar search for applications works.  I tried to run swupd repair. Running swupd repair says it fixes ~3500 files. But on reboot kde is not fixed and running swupd repair again shows the same error results.  Attached is the output for the repair process
[swupd-repair.txt](https://github.com/clearlinux/distribution/files/7893011/swupd-repair.txt)
.

**Comment by comptekki** [comment] 2022-01-19 21:16
See attached output from journalctl -b
[clr-boot-log.txt](https://github.com/clearlinux/distribution/files/7900619/clr-boot-log.txt)

**Comment by comptekki** [comment] 2022-01-19 21:45
note: 35550 is the last working kde.  When [ swupd repair -m 35560 --force ] is run, kde has black screen 35560.  alt-space bar works, flag-e brings up dolphin, etc.  Updating to 35650 is the same - black screen. No menu panel, or desktop to right-click on, etc.

**Comment by insilications** [comment] 2022-01-28 23:34
You can open a konsole window (kglobalshortcuts is running) with the default shortcut and try plasmashell --replace &

I'm trying to discover what is going on...

**Comment by insilications** [comment] 2022-01-29 00:08
I think I've found the problem. The last plasma-workspace package update is not installing essential files anymore, such as: https://github.com/clearlinux-pkgs/plasma-workspace/commit/5fef8d827d1ecc9685950c131302fbe16586208a

`/usr/share/xdg/autostart/gmenudbusmenuproxy.desktop
/usr/share/xdg/autostart/klipper.desktop
/usr/share/xdg/autostart/org.kde.plasmashell.desktop
/usr/share/xdg/autostart/xembedsniproxy.desktop
/usr/share/xdg/plasmanotifyrc
/usr/share/xdg/taskmanagerrulesrc`

And there is no reason for it not to. Specifically, /usr/share/xdg/autostart/org.kde.plasmashell.desktop is essential to start the plasmashell after login or /usr/bin/startplasma-*

**Comment by phmccarty** [comment] 2022-01-29 00:30
Looks like `KDE_INSTALL_CONFDIR` needs to be set at build time now instead of `XDG_CONFIG_DIRS`.

Working on a fix.

**Comment by fenrus75** [comment] 2022-01-29 00:30
ah ha a clue :)

will go inspect this package to see if I can figure out what is up

**Comment by phmccarty** [comment] 2022-01-29 00:34
Setting `KDE_INSTALL_CONFDIR` does work, but I don't how what effect it will have at runtime. Somewhere that variable defaults to `/etc`...

**Comment by insilications** [comment] 2022-01-29 02:43
@phmccarty  
Setting KDE_INSTALL_CONFDIR worked for me. 

Also, it seems the powerdevil package suffered from the same problem... 
/usr/share/xdg/autostart/powerdevil.desktop was not included
https://github.com/clearlinux-pkgs/powerdevil/commit/f43bf8e1d5e6c4bfb704c690a71d5d3c28f5d489

**Comment by insilications** [comment] 2022-01-29 02:47
More instances: 
/usr/share/xdg/autostart/org.kde.discover.notifier.desktop
https://github.com/clearlinux-pkgs/plasma-discover/commit/8faf05c1a2cea3242de3d84afdc58d937fda9aea

/usr/share/xdg/autostart/pam_kwallet_init.desktop
https://github.com/clearlinux-pkgs/kwallet-pam/commit/cc6568559cca7976d620414429b6caffc8dcc3aa

/usr/share/xdg/autostart/kwrited-autostart.desktop
https://github.com/clearlinux-pkgs/kwrited/commit/3b15d1e433259ef6b8175f2c2635385a452f01e8

**Comment by insilications** [comment] 2022-01-29 04:35
kf5-rpm-macros from fedora has some useful macros showing currently used kde cmake variables... 

```
%_kf5_prefix %_prefix
%_kf5_archdatadir %_qt5_archdatadir
%_kf5_bindir %_kf5_prefix/bin
%_kf5_datadir %_datadir
%_kf5_docdir %_docdir
%_kf5_includedir %_includedir/KF5
%_kf5_libdir %_libdir
%_kf5_libexecdir %_libexecdir/kf5
%_kf5_metainfodir %_metainfodir
%_kf5_qtplugindir %_qt5_plugindir
%_kf5_plugindir %_qt5_plugindir/kf5
%_kf5_sysconfdir %_sysconfdir
%_kf5_mandir %_kf5_datadir/man
%_kf5_buildtype release
%_kf5_qmldir %_kf5_archdatadir/qml
%_kf5_version 5.90.0

%cmake_kf5 \\\
  %undefine __cmake_in_source_build \
  QTDIR="%{_qt5_prefix}" ; export QTDIR ; \
  PATH="%{_qt5_bindir}:$PATH" ; export PATH ; \
  CFLAGS="${CFLAGS:-%optflags}" ; export CFLAGS ; \
  CXXFLAGS="${CXXFLAGS:-%optflags}" ; export CXXFLAGS ; \
  FFLAGS="${FFLAGS:-%optflags%{?_fmoddir: -I%_fmoddir}}" ; export FFLAGS ; \
  %{?__global_ldflags:LDFLAGS="${LDFLAGS:-%__global_ldflags}" ; export LDFLAGS ;} \
    %{__cmake} \\\
    %{?__cmake_builddir:-S "%{_vpath_srcdir}"} \\\
    %{?__cmake_builddir:-B "%{__cmake_builddir}"} \\\
    -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \\\
    -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \\\
    -DCMAKE_Fortran_FLAGS_RELEASE:STRING="-DNDEBUG" \\\
    -DBUILD_SHARED_LIBS:BOOL=ON \\\
    -DBUILD_TESTING:BOOL=FALSE \\\
    -DCMAKE_BUILD_TYPE=%{_kf5_buildtype} \\\
    -DCMAKE_INSTALL_INCLUDEDIR_KF5:PATH=%{_kf5_includedir} \\\
    -DCMAKE_INSTALL_LIBEXECDIR_KF5:PATH=%{_kf5_libexecdir} \\\
    -DCMAKE_INSTALL_PREFIX:PATH=%{_kf5_prefix} \\\
    -DCMAKE_USE_RELATIVE_PATHS:BOOL=ON \\\
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \\\
    -DECM_MKSPECS_INSTALL_DIR:PATH=%{_kf5_archdatadir}/mkspecs/modules \\\
    -DKDE_INSTALL_BINDIR:PATH=%{_kf5_bindir} \\\
    -DKDE_INSTALL_INCLUDEDIR:PATH=%{_includedir} \\\
    -DKDE_INSTALL_KCFGDIR:PATH=%{_datadir}/config.kcfg \\\
    -DKDE_INSTALL_LIBDIR:PATH=%{_kf5_libdir} \\\
    -DKDE_INSTALL_LIBEXECDIR:PATH=%{_libexecdir} \\\
    -DKDE_INSTALL_METAINFODIR:PATH=%{_kf5_metainfodir} \\\
    -DKDE_INSTALL_PLUGINDIR:PATH=%{_qt5_plugindir} \\\
    -DKDE_INSTALL_QMLDIR:PATH=%{_kf5_qmldir} \\\
    -DKDE_INSTALL_QTPLUGINDIR:PATH=%{_qt5_plugindir} \\\
    -DKDE_INSTALL_QTQUICKIMPORTSDIR:PATH=%{_qt5_importdir} \\\
    -DKDE_INSTALL_SYSCONFDIR:PATH=%{_kf5_sysconfdir} \\\
    -DKDE_INSTALL_USE_QT_SYS_PATHS:BOOL=ON

# %%find_lang_kf5
#
# This macro is used in KDE Frameworks 5 packages instead of %%find_lang,
# becasue find_lang is broken an it thinks that "_qt" in foobar_qt.qm is
# the name of the language.
# This macro should NOT be used with anything else but KDE Frameworks, since
# it does some assumptions regarding the names and locations and it might not
# work with other packages.
# We should eventually get this to RPM, or fix %%find_lang
#                                                       -- dvratil
# Usage: find_lang_kf5 fooBar5
#   - will look for fooBar5_qt.qm files in %%{buildroot}/usr/share/locale/
#
%find_lang_kf5() \
    (find %{buildroot}/%{_datadir}/locale/ -name "%1.qm" -type f | sed ' \
        s:%{buildroot}/:: \
        s:%{_datadir}/locale/\\([a-zA-Z_\\@]*\\)/\\([a-zA-Z_]*\\)/%1.qm:%lang(\\1) %{_datadir}/locale/\\1/\\2/%1.qm:' > %1.lang)
```



https://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/k/kf5-rpm-macros-5.90.0-2.fc36.noarch.html

**Comment by phmccarty** [comment] 2022-01-29 06:17
@insilications Thanks for identifying more of the xdg files that disappeared!

I discovered the root cause that led to these mis-packaging issues. A [patch](https://github.com/clearlinux-pkgs/extra-cmake-modules/blob/26df8a21203e7d183872860e3597637b5d148157/better-xdg-dir.patch) to `extra-cmake-modules` was recently disabled (likely due to a patch apply failure), but that patch is required to modify the XDG dir location in the way we set it originally.

So, I rebased it; the patch now applies to the `kde-modules/KDEInstallDirsCommon.cmake` source file instead of `kde-modules/KDEInstallDirs.cmake`.

After I integrate that fix, I will re-autospec these packages to restore XDG content:

```
akonadi
baloo
dragon
filelight
kalarm
kdeconnect-kde
kdelibs4support
khangman
khtml
kio
kmouth
konqueror
krita
ksudoku
kturtle
kwallet-pam
kwrited
kxmlgui
libkleo
palapeli
plasma-desktop
plasma-discover
plasma-workspace
polkit-kde-agent
powerdevil
```

If you discover any other packages affected by this issue, please let us know.

**Comment by insilications** [comment] 2022-01-29 06:56
Thanks @phmccarty!

I've identified another problem that fits in the general category of "kde-desktop" not working properly... qqc2-desktop-style package, which is included in the desktop-kde bundle, is not including an essential library: /usr/lib64/qt5/plugins/kf5/kirigami/org.kde.desktop.so. My heavily modified autospec installs this under lib subpackage. Lack of this file leads to crashes and wrong QML design in the systemsettings5, specially in the "Appearance" tab.

I also installed this as a package, after verifying that systemsettings5 is performing correctly. Just to make sure: https://download.kde.org/stable/plasma/5.23.5/qqc2-breeze-style-5.23.5.tar.xz

**Comment by phmccarty** [comment] 2022-01-30 00:15
@insilications Can you file a separate issue for that packaging problem?

**Comment by phmccarty** [comment] 2022-01-30 05:51
Disregard my previous comment. The fix was easy enough that we don't need to track it separately.

When I autospec `qqc2-desktop-style`, the /usr/lib64/qt5/plugins/kf5/kirigami/org.kde.desktop.so module is built, installed, and resides in the `lib` subpackage, just as needed.

I suspect the reason it was not built is due to an issue with the ordering in which the KDE packages were updated.

In the build log for qqc2-desktop-style-5.90.0-49, I see

```
-- The following OPTIONAL packages have not been found:
 * KF5IconThemes (required version >= 5.90.0)
 * KF5ConfigWidgets (required version >= 5.90.0)
```

But now when I autospec it, those dependencies are found, the module is built/installed, and the runtime deps are added.

**Comment by phmccarty** [comment] 2022-01-31 22:34
The issues for missing XDG data files should all be fixed in [release 35770](https://cdn.download.clearlinux.org/releases/35770/clear/RELEASENOTES). You can navigate to each change via links to the package repos linked above this comment.

And the issue with qqc2-desktop-style is fixed in [release 35780](https://cdn.download.clearlinux.org/releases/35780/clear/RELEASENOTES). See [this commit](https://github.com/clearlinux-pkgs/qqc2-desktop-style/commit/ffcd177fb7b375451b4ee3bd94760f259f5545a5) for details.

**Closed by phmccarty** 2022-01-31 22:34 UTC
Labels: bug
