### ISSUE TITLE
Encountered Clear Linux 31090 (Latest) boot fail on Intel NUC, the whole system freeze with message "SHA256 validated" 

### ISSUE THREAD

**Issue by sriiora** [clearlinux/distribution#1273] opened 2019-09-26 03:03 UTC
Encountered Clear Linux 31090 (Latest) boot fail on Intel NUC, the whole system freeze with message "SHA256 validated" 

I performed swupd update to 31090 and followed by a reboot.  Tested on Intel NUC (BOXNUC7i7BNH, latest BIOS 80) not VM. The kernel (clear-linux-native-5.3.1-838) coming with this version has problem to boot in Intel NUC.

**Comment by puneetse** [comment] 2019-09-26 03:30
Thanks for reporting this @sriiora. This is a duplicate of https://github.com/clearlinux/distribution/issues/1272 . Please add any additional details you have to that issue.

**Closed by puneetse** 2019-09-26 03:30 UTC
Labels: bug, new
