### ISSUE TITLE
Dell Studio xps 8700 i7 not acceptable

### ISSUE THREAD

**Issue by donaldw4** [clearlinux/distribution#899] opened 2019-06-16 16:16 UTC
Clear OS test claim the i7 not acceptable.

**Comment by thiagomacieira** [comment] 2019-06-17 05:54
Did it give any more information why it thinks the system is not acceptable?

**Comment by ahkok** [comment] 2019-06-17 17:37
You likely booted in BIOS mode. Please boot in UEFI mode instead.

**Comment by donaldw4** [comment] 2019-06-20 08:16
I am getting the following message:  Missing required CPU Feature: Advance
Encryption.

How do I solve this problem?

Thanks,
Donald

**Comment by ahkok** [comment] 2019-06-21 04:42
Duplicate of #785

**Closed by ahkok** 2019-06-21 04:42 UTC
Labels: bug

**Comment by thiagomacieira** [comment] 2019-06-22 03:06
For the record, can you tell us what processor that machine has?

**Comment by donaldw4** [comment] 2019-06-22 06:21
All I can tell you is that it is an i7.  Please tell me how to find out the
processor number?  Is it possible that I need an update?

Thanks,
Donald

**Comment by thiagomacieira** [comment] 2019-06-22 15:18
From a Linux system that runs on it, `cat /proc/cpuinfo`.

It's possible that a BIOS update or configuration will turn AES back on. But you might have one of the processors that don't have the feature.

**Comment by donaldw4** [comment] 2019-06-23 20:11
By chance, do you know with site I need to go to in order to check for an update for my BIOS?

Thanks,
Donald

**Comment by donaldw4** [comment] 2019-06-24 01:58
See if this information helps:

**Comment by thiagomacieira** [comment] 2019-06-24 05:26
I get my Dell BIOS upgrades from https://www.dell.com/support/home/us/en/4/product-support/. Type your service tag and it'll show the downloads for your machine. Most of them are Windows executables, even the BIOS and firrmware upgrades, unfortunately.
