### ISSUE TITLE
clear-28280-live-desktop-beta.img desktop does not launch with NVIDIA GPU

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#527] opened 2019-03-13 18:02 UTC
**Describe the bug**
Clear version 28280 live desktop beta boots but does not launch desktop on a system with a NVIDIA 980M GPU. The console login is displayed, but login is not possible. 

**To Reproduce**
1.  Download 28280 - https://cdn.download.clearlinux.org/releases/28280/clear/clear-28280-live-desktop-beta.img.xz 
2. Write to USB
3. Boot from USB
4. No desktop loads and cannot login to console

**Expected behavior**
Either allow a console login after a failed desktop launch or display a message about failed desktop launch meaning the currently booted OS not being functional and to reboot, especially for the live desktop image. 

Right now, it just appears as an OS that doesn't work after booting.

**Comment by puneetse** [comment] 2019-03-13 18:06
Probably related to https://github.com/clearlinux/distribution/issues/353 but the issue I'm trying to highlight here is how the live image specifically reacts to this scenario could be improved.

**Comment by mdhorn** [comment] 2019-03-13 20:29
This is not specifically an image problem, it is a general OS issue for launching the desktop.
We need better error recovery for the startup sequence if the desktop doesn't launch.

**Comment by ahkok** [comment] 2019-03-14 18:37
Duplicate of #353

**Closed by ahkok** 2019-03-14 18:37 UTC
Labels: bug
