### ISSUE TITLE
multicast DNS/DNS-SD service discovery

### ISSUE THREAD

**Issue by AWHubGit** [clearlinux/distribution#1384] opened 2019-10-20 13:04 UTC
Please add something for multicast DNS/DNS-SD service discovery
https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916
https://github.com/lathiat/avahi
https://en.wikipedia.org/wiki/Avahi_%28software%29
https://bitbucket.org/ericse/zeroconf-menu/wiki/Home
http://www.openslp.org/    https://github.com/openslp-org
Thanks.

**Comment by ahkok** [comment] 2019-10-20 18:40
Duplicate of #714 - if we add this, it will be `avahi`.

**Closed by ahkok** 2019-10-20 18:40 UTC
Labels: new, package-request

**Comment by thiagomacieira** [comment] 2019-10-21 17:19
No need, we have systemd-resolved.
```
$ resolvectl query tjmaciei-mac02.local
tjmaciei-mac02.local: fe80::c3c:13b9:f186:501c%2 -- link: enp0s31f6

-- Information acquired via protocol mDNS/IPv6 in 956us.
-- Data is authenticated: no
```

**Comment by desvdp** [comment] 2019-11-29 22:01
not sure systemd-resolved provides even similar functionality: avahi is used to announce services on the network, while resolved only finds them, not?

**Comment by thiagomacieira** [comment] 2019-12-04 02:52
It does, but a much more limited functionality. It announces the machine only and has no support for adding more services, especially not dynamic ones.
