### ISSUE TITLE
KDE main menu application-entries missing

### ISSUE THREAD

**Issue by DarkCaster** [clearlinux/distribution#1035] opened 2019-07-21 15:14 UTC
Starting from OS version 30370 - KDE main menu now completely blank. Almost all menu entries gone missing: application-groups, installed applications, system-settings, etc. Only logout\poweroff\reboot entries remains.

This bug can be reproduced even on clean-install on virtual machine by using this iso: https://cdn.download.clearlinux.org/releases/30450/clear/clear-30450-live-desktop.iso.xz

1) Perform clean installation from provided ISO, disable auto-update, telemetry, and create new user
2) Reboot, install "desktop-kde" bundle
3) Login to X11 Plasma session
4) Open main menu - it should be completely blank

5) Revert to OS version 30360 by issuing "swupd repair -Y -V 30360"
6) Reboot, login to X11 Plasma session again
7) Open main menu - it is working as intended now

**Comment by anselmolsm** [comment] 2019-07-22 16:58
Hi @DarkCaster , It was caused by an issue in kservice package paths. The fix for that is in the process to get published, and that may happen in the next days.

Meanwhile, a workaround: cp /usr/share/xdg/menus/applications.menu ~/.config/menus/

**Comment by DarkCaster** [comment] 2019-07-22 17:13
Thanks! But, somehow, I do not have "/usr/share/xdg/menus/applications.menu" file installed in my system. Instead I have "/usr/share/xdg/applications.menu". Copying it to ~/.config/menus - seems to work for my case. For one of my machines I've also run "Restore to System Menu" in "KDE menu editor" app in order to fully restore menu.

**Comment by anselmolsm** [comment] 2019-07-22 17:27
@DarkCaster sorry, I mixed the workaround with the right path...

You either:

> cp /usr/share/menus/applications.menu ~/.config/menus/

or

> sudo cp /usr/share/menus/applications.menu /usr/share/xdg/menus/applications.menu

**Comment by anselmolsm** [comment] 2019-07-24 00:26
Fix released in 30480.

**Closed by anselmolsm** 2019-07-24 00:26 UTC
Labels: bug, new
