### ISSUE TITLE
valgrind not detecting simple leak with malloc

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#119] opened 2018-07-10 18:41 UTC
Compiling the following program in Clear Linux, then running valgrind show no memory leaks. Double checked in Fedora and as expected there it shows the memory leaks.

```
#include <stdio.h>
#include <stdlib.h>

int main() {
	int *a;
	for (int i = 0; i < 10; i++) {
		a = malloc(100000);
		printf("%p\n", a);
	}
	return 0;
}
```

For the record, the compilation attempts:

```
$ gcc program.c
$ gcc -O0 program.c
$ CFLAGS= gcc program.c                     # Clear does set CFLAGS by default.
$ CFLAGS= gcc -O0 program.c
```

And the valgrind result in Clear:
```
==536== Memcheck, a memory error detector
==536== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==536== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==536== Command: ./a.out
==536== 
0x402b260
0x4043d20
0x405c3d0
0x4074a80
0x408d130
0x40a57e0
0x40bde90
0x40d6540
0x40eebf0
0x41072a0
==536== 
==536== HEAP SUMMARY:
==536==     in use at exit: 0 bytes in 0 blocks
==536==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==536== 
==536== All heap blocks were freed -- no leaks are possible
==536== 
==536== For counts of detected and suppressed errors, rerun with: -v
==536== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

And the output with -v:

```
$ valgrind -v ./a.out 
==720== Memcheck, a memory error detector
==720== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==720== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==720== Command: ./a.out
==720== 
--720-- Valgrind options:
--720--    -v
--720-- Contents of /proc/version:
--720--   Linux version 4.16.11-262.kvm (mockbuild@kojibld02) (gcc version 8.1.1 20180514 (Clear Linux OS for Intel Architecture)) #2 SMP Tue Jun 26 18:05:51 UTC 2018
--720-- 
--720-- Arch and hwcaps: AMD64, LittleEndian, amd64-cx16-rdtscp-sse3-avx
--720-- Page sizes: currently 4096, max supported 4096
--720-- Valgrind library directory: /usr/lib64/valgrind
--720-- Reading syms from /home/c/a.out
--720-- Reading syms from /usr/lib64/ld-2.27.so
--720-- Reading syms from /usr/lib64/valgrind/memcheck-amd64-linux
--720-- ELF section outside all mapped regions
--720-- Scheduler: using generic scheduler lock implementation.
--720-- Reading suppressions file: /usr/lib64/valgrind/default.supp
==720== embedded gdbserver: reading from /tmp/vgdb-pipe-from-vgdb-to-720-by-c-on-???
==720== embedded gdbserver: writing to   /tmp/vgdb-pipe-to-vgdb-from-720-by-c-on-???
==720== embedded gdbserver: shared mem   /tmp/vgdb-pipe-shared-mem-vgdb-720-by-c-on-???
==720== 
==720== TO CONTROL THIS PROCESS USING vgdb (which you probably
==720== don't want to do, unless you know exactly what you're doing,
==720== or are doing some strange experiment):
==720==   /usr/lib64/valgrind/../../bin/vgdb --pid=720 ...command...
==720== 
==720== TO DEBUG THIS PROCESS USING GDB: start GDB like this
==720==   /path/to/gdb ./a.out
==720== and then give GDB the following command
==720==   target remote | /usr/lib64/valgrind/../../bin/vgdb --pid=720
==720== --pid is optional if only one valgrind process is running
==720== 
--720-- REDIR: 0x401ee10 (ld-linux-x86-64.so.2:strlen) redirected to 0x5805c098 (???)
--720-- REDIR: 0x401ebf0 (ld-linux-x86-64.so.2:index) redirected to 0x5805c0b2 (???)
--720-- Reading syms from /usr/lib64/valgrind/vgpreload_core-amd64-linux.so
--720-- ELF section outside all mapped regions
--720-- Reading syms from /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so
--720-- ELF section outside all mapped regions
--720-- Reading syms from /usr/lib64/libc-2.27.so
--720--   Considering /usr/lib/debug/.build-id/dc/085cc6448ccd47df959c24ed40be3b26a9b1a5.debug ..
--720--   .. build-id is valid
0x402b260
0x4043d20
0x405c3d0
0x4074a80
0x408d130
0x40a57e0
0x40bde90
0x40d6540
0x40eebf0
0x41072a0
==720== 
==720== HEAP SUMMARY:
==720==     in use at exit: 0 bytes in 0 blocks
==720==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==720== 
==720== All heap blocks were freed -- no leaks are possible
==720== 
==720== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==720== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

One (wild) guess would be that there is something mismatch between the glibc version and the suppressions distributed in Clear Linux.

**Comment by mbelluzzo** [comment] 2018-07-12 17:57
I was able to reproduce this in my NUC running Clear 23610

**Comment by lpereira** [comment] 2018-07-12 19:07
Running Valgrind with `--default-suppressions=no` makes no difference.

**Comment by VictorRodriguez** [comment] 2018-07-16 20:36
I was able to reproduce, working on debug , track and fixing

**Comment by nesiusra** [comment] 2018-07-17 17:44
How goes root-causing this, @VictorRodriguez?   I'm wondering if this is a valgrind bug, or a result of our compiler/linker toolchain detecting and preventing the leak...

**Comment by phmccarty** [comment] 2018-07-17 17:50
Valgrind memcheck is not reporting any allocations at all, let alone leaks. So this looks like either a valgrind bug or (more likely) a bug in the way valgrind is integrated in Clear Linux.

**Comment by lpereira** [comment] 2018-07-17 17:58
I suspect that the first step would be seeing if Valgrind is actually able to hook into the malloc symbols. The same behavior happens when you're running memcheck with a static binary, or you're linking with a shared library that overrides all the malloc symbols (e.g. tcmalloc, jemalloc, etc.); none of which are the case here.

A curious thing that might or might not be related is that binaries built with GCC in Clear Linux, and @mbelluzzo can confirm this, are making calls to `malloc` instead of `malloc@PLT`; however, this also doesn't seem to be the issue, as a binary built with another GCC, making malloc calls through the PLT, are also showing the same behavior.

Speaking of PLT, memcheck works fine even with immediate binding (`-Wl,-z,-now`), read-only GOT (`-Wl,-z,relro`) and `-fno-plt`. These are usual hardening parameters passed to GCC/linker that could influence memcheck's ability to hook to symbols in shared libraries, but that's not the case.  However, the devil is in the details, so I would double check changes in default linker/compilation flags made since the time Valgrind was working on ClearLinux.

**Comment by VictorRodriguez** [comment] 2018-07-17 19:07
So far this is my update: 

testing code examples [examples] (https://github.com/VictorRodriguez/operating-systems-lecture/tree/master/labs/gcc/valgrind)

binary with leaks

Running in CLR , Compiled in CLR = FAIL ( do not detect mem leaks ) 
Running in Fedora , Compiled in CLR = PASS ( detect mem leaks ) 
Running in CLR , Compiled in Fedora = FAIL ( do not detect mem leaks ) 
Running in Fedora , Compiled in Fedora = PASS ( detect mem leaks ) 

Then I move the --prefix=/tmp/build Valgrind build directory across distros and this is the answer : 

Valgrind compiled in CLR , Running in CLR = FAIL ( do not detect mem leaks ) 
Valgrind compiled in Fedora , Running in CLR = FAIL ( do not detect mem leaks ) 
Valgrind compiled in CLR , Running in Fedora = PASS ( detect mem leaks ) 
Valgrind compiled in Fedora , Running in Fedora = PASS ( detect mem leaks )

**Comment by VictorRodriguez** [comment] 2018-07-17 21:57
Under CLR system as @phmccarty  mention the major problem is that we are not reporting any allocation at all: 
#include <stdio.h>
#include <stdlib.h>

int main(){
	malloc(100);
	return 0;
}

will show in Fedora : 

==18711== HEAP SUMMARY:
==18711==     in use at exit: 100 bytes in 1 blocks
==18711==   total heap usage: 1 allocs, 0 frees, 100 bytes alloca

and in CLR : 

==16761== HEAP SUMMARY:
==16761==     in use at exit: 0 bytes in 0 blocks
==16761==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated

Valgrind works by doing a just-in-time (JIT) translation of the input program into an equivalent version that has additional checking. For the memcheck tool, this means it literally looks at the x86 code in the executable and detects what instructions represent memory accesses. These instructions are sandboxed so that it can trap accesses to uninitialized memory (even if those accesses do not cause a page fault or segmentation fault). The memcheck tool also has special knowledge of routines like malloc() and free(), so it can track what memory is still “reachable” when the program terminates. Based on documentation, there will also be no replacement if you use an alternative malloc library such as tcmalloc, jemalloc

**Comment by VictorRodriguez** [comment] 2018-07-19 02:29
Fix FOUND :) 
based on https://bugs.kde.org/show_bug.cgi?id=395682
As soon as the patch is merged and test corroborate fix, i will upload on what clr version is fixed and close the bug

**Comment by nesiusra** [comment] 2018-07-19 05:41
Thanks, Victor.

**Comment by VictorRodriguez** [comment] 2018-07-19 22:38
@cmarcelo could you please check that version 23830 works fine and close this issue?

**Closed** 2018-07-20 17:33 UTC

**Comment by cmarcelo** [comment] 2018-07-20 17:49
> @cmarcelo could you please check that version 23830 works fine and close this issue?

Confirmed it works. Thanks!
