### ISSUE TITLE
docker build failed in clearlinux

### ISSUE THREAD

**Issue by qzheng527** [clearlinux/distribution#1107] opened 2019-08-08 04:04 UTC
The same dockerfile build failed in clear linux but succeeded in ubuntu.
Narrowing down to the very simple dockerfile as below.
"
FROM clearlinux:latest

ARG swupd_args
RUN swupd update --no-boot-update $swupd_args
RUN swupd info
"
Failure log in clear linux was:
"
 Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM clearlinux:latest
 ---> 8966001d97e4
Step 2/4 : ARG swupd_args
 ---> ab8867e3c5c8
Step 3/4 : RUN swupd update $swupd_args
 ---> Running in 570df06feea6

Update started.
Preparing to update from 30650 to 30700
......

        ...100%
Update was applied.
Calling post-update helper scripts
none
Warning: helper script (/usr/bin/clr-boot-manager) not found, it will be skipped
Update took 134.0 seconds, 16 MB transferred
329 files were not in a pack
Update successful. System updated from version 30650 to version 30700
Removing intermediate container 570df06feea6
 ---> 61e3b5c5e841
Step 4/4 : RUN swupd info
 ---> Running in 1febe6ad3478
standard_init_linux.go:190: exec user process caused "no such file or directory"
time="2019-08-08T04:18:18Z" level=error msg="init failed" error="standard_init_linux.go:190: exec user process caused \"no such file or directory\"" name=kata-agent pid=1 source=agent
panic: --this line should have never been executed, congratulations--

goroutine 1 [running, locked to thread]:
main.init.0()
        /tmp/build-image-tmp.BtpwTq1Wlp/go/src/github.com/kata-containers/agent/agent.go:1228 +0x10f
The command '/bin/sh -c swupd info' returned a non-zero code: 2
"

The installed clear linux version is 30650.
Adding "RUN ldconfig" after "swupd update" didn't help.

**Comment by phmccarty** [comment] 2019-08-08 04:20
@qzheng527 glibc was upgraded to 2.30 in build 30700, and swupd is supposed to run `ldconfig` automatically these days (see https://github.com/clearlinux-pkgs/swupd-client/blob/d11cfd13c6c1124aee48f7457b046a434da106c5/always-run-ldconfig.patch). Perhaps it's unrelated to the glibc upgrade, but nothing else stands out in the release notes.

**Comment by qzheng527** [comment] 2019-08-08 05:12
I found the root cause maybe the “Native Overlay Diff” option.
Running "docker info" we got
“
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
“
On clear, the default value for “Native Overlay Diff” was false but on Ubuntu it was true.
I used below way to change the value to true on Clear then the build was successful.

sudo modprobe -r overlay && sudo modprobe overlay redirect_dir=off
sudo systemctl restart docker

This default value is related to the kernel config CONFIG_OVERLAY_FS_REDIRECT_DIR.
In clear it is set to "y" but in ubuntu 4.19 kernel it is set to "n".

**Comment by wxb071216** [comment] 2019-08-15 06:53
I found with --no-cache option, even set Native Overlay Diff to true, docker build will still fail with error "The command '/bin/sh -c swupd update --no-boot-update $swupd_args' returned a non-zero code: 255"

**Comment by hnanni** [comment] 2019-08-15 21:56
can I have the docker file?

**Comment by phmccarty** [comment] 2019-08-15 22:38
@hnanni This Dockerfile is enough to reproduce it:

```
FROM clearlinux:latest

ARG swupd_args
RUN swupd update --no-boot-update $swupd_args
RUN swupd info
```

**Comment by hnanni** [comment] 2019-08-16 20:32
I neither can reproduce it

I've added a test of the docker build. Currently it contains the "-m" workaroud., as soon as the fix lands in the release, will remove it

**Comment by phmccarty** [comment] 2019-08-16 23:21
@hnanni Did you try testing from an older base image, like `30650`, and updating to latest from there?

**Comment by mythi** [comment] 2019-08-19 05:08
>Maybe if your clearlinux:latest base image is older than 30700,

FWIW, it's always good to build with `--pull` to ensure the latest base if fetched.

**Comment by hnanni** [comment] 2019-08-19 17:19
HAven't tried with old versions, but pulled the latest:

Status: Downloaded newer image for clearlinux:latest
Step 2/4 : RUN swupd info
 
Installed version: 30730
Step 3/4 : RUN swupd update -m 30740 --no-boot-update
 
Update started.
Preparing to update from 30730 to 30740
[...]
Update was applied.
Calling post-update helper scripts
Update took 8.2 seconds, 5 MB transferred
Update successful. System updated from version 30730 to version 30740

**Comment by phmccarty** [comment] 2019-08-19 18:12
@hnanni I think this issue should be tested with an older starting version, ideally from the release in the original report, `30650`.

I can reproduce by running this script. Can you test with this instead?

```
#!/bin/bash -ex

FROM_VER=30650
TO_VER=30740

sudo rm -rf ./base ./base.tar.xz
mkdir ./base
TMP=$(mktemp -d -p $PWD)
sudo swupd os-install --version="$FROM_VER" --statedir="$TMP" --path="$PWD/base" --no-boot-update --bundles os-core,os-core-update --format=staging
sudo rm -rf "$TMP"

sudo tar -C ./base -cJf ./base.tar.xz .

cat > Dockerfile.base << EOF
FROM scratch
ADD base.tar.xz /
CMD ["/bin/bash"]
EOF

sudo docker build -t clearlinux:old -f Dockerfile.base .

cat > Dockerfile.test << EOF
FROM clearlinux:old
ARG swupd_args
RUN swupd update -m $TO_VER --no-boot-update $swupd_args
RUN swupd info
EOF

PROXY_ARG=
if [ -n "$https_proxy" ]; then
        PROXY_ARG="--build-arg HTTPS_PROXY=$https_proxy"
fi

sudo docker build -t clearlinux:test -f Dockerfile.test $PROXY_ARG .
```

**Comment by phmccarty** [comment] 2019-08-19 20:02
After further debug, updating from `30690` to `30700` using the test script above, it appears that the many symlinks glibc installs in `/usr/lib64` were not updated in course of that update, leaving a corrupt image as a result, since those symlinks *must* be updated.

So, for example, `/usr/lib64/ld-linux-x86-64.so.2` was still pointing to `ld-2.29.so` after the swupd update, but it should have been updated to point to `ld-2.30.so`. If I update `Dockerfile.test` to execute:

```
RUN swupd update -m $TO_VER --no-boot-update $swupd_args && ln -sf ld-2.30.so /usr/lib64/ld-linux-x86-64.so.2
```

then the subsequent RUN command exits with:

```
Step 4/4 : RUN swupd info
 ---> Running in be54640cb40c
/bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
```

Inspecting the result showed that `/usr/lib64/libc.so.6` was still present, but pointing to `libc-2.29.so` instead of `libc-2.30.so`.

**Comment by phmccarty** [comment] 2019-08-19 20:11
For reference, here are the files/dirs/symlinks that were updated/created in `/usr/lib64` for the swupd update described in my previous comment. Note that no symlinks were updated or created aside from `/usr/lib64/p11-kit-trust.so`:

```
/usr/lib64
/usr/lib64/audit
/usr/lib64/audit/sotruss-lib.so
/usr/lib64/gconv
/usr/lib64/gconv/ANSI_X3.110.so
/usr/lib64/gconv/ASMO_449.so
/usr/lib64/gconv/BIG5.so
/usr/lib64/gconv/BRF.so
/usr/lib64/gconv/CP10007.so
/usr/lib64/gconv/CP1125.so
/usr/lib64/gconv/CP1250.so
/usr/lib64/gconv/CP1251.so
/usr/lib64/gconv/CP1252.so
/usr/lib64/gconv/CP1253.so
/usr/lib64/gconv/CP1254.so
/usr/lib64/gconv/CP1256.so
/usr/lib64/gconv/CP1257.so
/usr/lib64/gconv/CP737.so
/usr/lib64/gconv/CP770.so
/usr/lib64/gconv/CP771.so
/usr/lib64/gconv/CP772.so
/usr/lib64/gconv/CP773.so
/usr/lib64/gconv/CP774.so
/usr/lib64/gconv/CP775.so
/usr/lib64/gconv/CSN_369103.so
/usr/lib64/gconv/CWI.so
/usr/lib64/gconv/gconv-modules.cache
/usr/lib64/gconv/GEORGIAN-ACADEMY.so
/usr/lib64/gconv/GEORGIAN-PS.so
/usr/lib64/gconv/GOST_19768-74.so
/usr/lib64/gconv/GREEK7-OLD.so
/usr/lib64/gconv/GREEK7.so
/usr/lib64/gconv/GREEK-CCITT.so
/usr/lib64/gconv/HP-GREEK8.so
/usr/lib64/gconv/HP-ROMAN8.so
/usr/lib64/gconv/HP-ROMAN9.so
/usr/lib64/gconv/HP-THAI8.so
/usr/lib64/gconv/HP-TURKISH8.so
/usr/lib64/gconv/IBM858.so
/usr/lib64/gconv/IEC_P27-1.so
/usr/lib64/gconv/INIS-8.so
/usr/lib64/gconv/INIS-CYRILLIC.so
/usr/lib64/gconv/INIS.so
/usr/lib64/gconv/ISIRI-3342.so
/usr/lib64/gconv/ISO_10367-BOX.so
/usr/lib64/gconv/ISO_11548-1.so
/usr/lib64/gconv/ISO_2033.so
/usr/lib64/gconv/ISO_5427-EXT.so
/usr/lib64/gconv/ISO_5427.so
/usr/lib64/gconv/ISO_5428.so
/usr/lib64/gconv/ISO646.so
/usr/lib64/gconv/ISO8859-10.so
/usr/lib64/gconv/ISO8859-11.so
/usr/lib64/gconv/ISO8859-13.so
/usr/lib64/gconv/ISO8859-14.so
/usr/lib64/gconv/ISO8859-15.so
/usr/lib64/gconv/ISO8859-16.so
/usr/lib64/gconv/ISO8859-1.so
/usr/lib64/gconv/ISO8859-2.so
/usr/lib64/gconv/ISO8859-3.so
/usr/lib64/gconv/ISO8859-4.so
/usr/lib64/gconv/ISO8859-5.so
/usr/lib64/gconv/ISO8859-6.so
/usr/lib64/gconv/ISO8859-7.so
/usr/lib64/gconv/ISO8859-8.so
/usr/lib64/gconv/ISO8859-9E.so
/usr/lib64/gconv/ISO8859-9.so
/usr/lib64/gconv/ISO-IR-197.so
/usr/lib64/gconv/ISO-IR-209.so
/usr/lib64/gconv/KOI8-R.so
/usr/lib64/gconv/KOI8-RU.so
/usr/lib64/gconv/KOI-8.so
/usr/lib64/gconv/KOI8-T.so
/usr/lib64/gconv/KOI8-U.so
/usr/lib64/gconv/LATIN-GREEK-1.so
/usr/lib64/gconv/LATIN-GREEK.so
/usr/lib64/gconv/MAC-CENTRALEUROPE.so
/usr/lib64/gconv/MACINTOSH.so
/usr/lib64/gconv/MAC-IS.so
/usr/lib64/gconv/MAC-SAMI.so
/usr/lib64/gconv/MAC-UK.so
/usr/lib64/gconv/MIK.so
/usr/lib64/gconv/NATS-DANO.so
/usr/lib64/gconv/NATS-SEFI.so
/usr/lib64/gconv/PT154.so
/usr/lib64/gconv/RK1048.so
/usr/lib64/gconv/SAMI-WS2.so
/usr/lib64/gconv/TIS-620.so
/usr/lib64/gconv/VISCII.so
/usr/lib64/haswell
/usr/lib64/haswell/avx512_1
/usr/lib64/haswell/avx512_1/libm-2.30.so
/usr/lib64/haswell/avx512_1/libmvec-2.30.so
/usr/lib64/haswell/avx512_1/.wh.libm-2.29.so
/usr/lib64/haswell/avx512_1/.wh.libmvec-2.29.so
/usr/lib64/haswell/libc-2.30.so
/usr/lib64/haswell/libcrypt-2.30.so
/usr/lib64/haswell/libm-2.30.so
/usr/lib64/haswell/libmvec-2.30.so
/usr/lib64/haswell/.wh.libc-2.29.so
/usr/lib64/haswell/.wh.libcrypt-2.29.so
/usr/lib64/haswell/.wh.libm-2.29.so
/usr/lib64/haswell/.wh.libmvec-2.29.so
/usr/lib64/ld-2.30.so
/usr/lib64/libanl-2.30.so
/usr/lib64/libatomic.so.1.2.0
/usr/lib64/libBrokenLocale-2.30.so
/usr/lib64/libc-2.30.so
/usr/lib64/libcrypt-2.30.so
/usr/lib64/libdl-2.30.so
/usr/lib64/libgcc_s.so.1
/usr/lib64/libgfortran.a
/usr/lib64/libgfortran.so.5.0.0
/usr/lib64/libgomp.so.1.0.0
/usr/lib64/libitm.so.1.0.0
/usr/lib64/libm-2.30.so
/usr/lib64/libmemusage.so
/usr/lib64/libmvec-2.30.so
/usr/lib64/libnsl-2.30.so
/usr/lib64/libnss_compat-2.30.so
/usr/lib64/libnss_dns-2.30.so
/usr/lib64/libnss_files-2.30.so
/usr/lib64/libnss_hesiod-2.30.so
/usr/lib64/libpcprofile.so
/usr/lib64/libpthread-2.30.so
/usr/lib64/libquadmath.so.0.0.0
/usr/lib64/libresolv-2.30.so
/usr/lib64/librt-2.30.so
/usr/lib64/libssp.so.0.0.0
/usr/lib64/libstdc++.so.6.0.27
/usr/lib64/libthread_db-1.0.so
/usr/lib64/libutil-2.30.so
/usr/lib64/p11-kit-trust.so -> libnssckbi.so
/usr/lib64/.wh.ld-2.29.so
/usr/lib64/.wh.libanl-2.29.so
/usr/lib64/.wh.libBrokenLocale-2.29.so
/usr/lib64/.wh.libc-2.29.so
/usr/lib64/.wh.libcrypt-2.29.so
/usr/lib64/.wh.libdl-2.29.so
/usr/lib64/.wh.libm-2.29.so
/usr/lib64/.wh.libmvec-2.29.so
/usr/lib64/.wh.libnsl-2.29.so
/usr/lib64/.wh.libnss_compat-2.29.so
/usr/lib64/.wh.libnss_dns-2.29.so
/usr/lib64/.wh.libnss_files-2.29.so
/usr/lib64/.wh.libnss_hesiod-2.29.so
/usr/lib64/.wh.libpthread-2.29.so
/usr/lib64/.wh.libresolv-2.29.so
/usr/lib64/.wh.librt-2.29.so
/usr/lib64/.wh.libutil-2.29.so
```

**Comment by qzheng527** [comment] 2019-08-20 01:31
@phmccarty I tired with your script on one newly created Clear VM.
It failed with the log as below.
"
Step 4/4 : RUN swupd info
 ---> Running in 6be53c45ec35
standard_init_linux.go:190: exec user process caused "no such file or directory"
time="2019-08-20T01:40:54Z" level=error msg="init failed" error="standard_init_linux.go:190: exec user process caused \"no such file or directory\"" name=kata-agent pid=1 source=agent
panic: --this line should have never been executed, congratulations--

goroutine 1 [running, locked to thread]:
main.init.0()
        /tmp/build-image-tmp.BtpwTq1Wlp/go/src/github.com/kata-containers/agent/agent.go:1228 +0x10f
"
But after I changed “Native Overlay Diff” option from false to true (mentioned in the beginning of the thread), the build could succeed. Changed it back, build failed again.
I tried adding "--no-cache" option, same behavior.
Could you try in your side with my suggest?
Thanks.

**Comment by phmccarty** [comment] 2019-08-20 04:16
@qzheng527 I had forgotten to test your suggestion, sorry about that.

I can confirm that setting `redirect_dir=off` for the `overlay` module fixes the issue. Examining the differences between my `clearlinux:old` and `clearlinux:test` docker images shows that all of the symlinks are updated properly in `clearlinux:test`.

So while disabling that module parameter fixes swupd updates in this case, I can't speak to the tradeoffs involved in disabling the kernel config option `CONFIG_OVERLAY_FS_REDIRECT_DIR`.

@miguelinux Thoughts?

**Comment by miguelinux** [comment] 2019-08-23 16:08
Let's remove it, I'm working on it

**Comment by phmccarty** [comment] 2019-08-23 20:59
Thanks @miguelinux

**Comment by miguelinux** [comment] 2019-08-23 21:17
It will be removed by **linux-5.2.9-826**

**Comment by hnanni** [comment] 2019-09-03 23:33
@miguelinux 

May you also apply the patch to the linux-kvm kernel?

**Comment by miguelinux** [comment] 2019-09-05 17:54
@hnanni done it will be available in 1 or 2 days

**Comment by puneetse** [comment] 2019-09-08 17:52
@miguelinux @phmccarty is disabling `CONFIG_OVERLAY_FS_REDIRECT_DIR` something that we should communicate as a change for those with an OverlayFS that is outside of Docker?

>Note, that redirects are not backward compatible. That is, mounting an overlay which has redirects on a kernel that doesn't support this feature will have unexpected results.

**Comment by phmccarty** [comment] 2019-09-09 16:57
@puneetse Yes, I think it would be worth communicating.

**Comment by miguelinux** [comment] 2019-09-09 17:11
agree

**Comment by ganeshmaharaj** [comment] 2019-09-11 00:25
Wonder if the fix discussed here will fix the below issues.
https://github.com/clearlinux/distribution/issues/1141
https://github.com/clearlinux/distribution/issues/1044

**Comment by ganeshmaharaj** [comment] 2019-09-11 00:41
Checked and i am able to build, push and download contents on other systems. This for the fix @phmccarty @miguelinux

**Comment by bryteise** [comment] 2019-09-11 16:29
I'm going to close this and the likely linked set of issues. For those finding this comment, kernel change was made in Clear Linux to those running on other hosts you may need to change the native overlay diff method using something like:
```sudo modprobe -r overlay && sudo modprobe overlay redirect_dir=off
sudo systemctl restart docker```

**Closed by bryteise** 2019-09-11 16:29 UTC
Labels: bug, cloud-native
