### ISSUE TITLE
clear-29350-installer does not autostart

### ISSUE THREAD

**Issue by clefrks** [clearlinux/distribution#703] opened 2019-05-10 03:20 UTC
When booting up the image, it did not go into clr-installer, instead prompt to login.

**Comment by mdhorn** [comment] 2019-05-10 03:31
Please specify the exact image in question.

Neither clear-29350-live-server.iso.xz nor clear-29350-live-desktop.iso.xz will start the installer by default, by design.

**Comment by clefrks** [comment] 2019-05-10 04:54
This image: https://cdn.download.clearlinux.org/releases/current/clear/clear-29350-installer.img.xz

**Comment by ionutnechita** [comment] 2019-05-11 16:30
this issue also appears on 29360.

**Comment by mdhorn** [comment] 2019-05-13 05:41
The clr-installer service is no longer supported.
Both the clear-xxxxx-installer.iso.xz and clear-xxxxx-installer.img.xz images will be removed in the very near future.

The two supported images going forward are:
clear-xxxxx-live-desktop.iso.xz 
- boots into a live desktop environment
- contains a graphical installer which can be started on demand

clear-xxxxx-live-server.iso.xz
- boots into a live image environment with a login prompt
- provides directions for setting root temp password, configuring the network,  and launching installer
- contains a text-based installer which can be started on demand

**Comment by dorileo** [comment] 2019-08-21 21:32
I assume this issue is invalid now, @mdhorn can we close it?

**Comment by mdhorn** [comment] 2019-08-21 22:08
Yes, this can be closed.  Thx

**Closed by mdhorn** 2019-08-21 22:08 UTC
Labels: bug
