### ISSUE TITLE
Can't disable "Automatic Date & Time" in gnome-control-center

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#632] opened 2019-04-18 19:04 UTC
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
In Clear 28920, the "Automatic Date & Time" switch keeps returning to the ON position when I flipped it to OFF.  When it does go to the OFF position, it will go back to the ON position when you navigate away from this screen and come back to it.

**To Reproduce**
1. Go to GDM Settings --> Details --> Date & Time 
2. Flip the "Automatic Date & Time" switch to OFF
3. It should flip back to ON.
4. If it does go to the OFF position, navigate to another settings and then come back to it.  Should be in the ON position again.

**Comment by ahkok** [comment] 2019-04-19 16:27
@mrkz

**Comment by mrkz** [comment] 2019-04-26 14:35
so it is effectively stopping the NTP service, but somehow get re-enabled back again. 

From journalctl I get:
```
Apr 26 09:28:57 mark-lap systemd[1]: Reloading.
Apr 26 09:28:57 mark-lap systemd[1]: Stopping Network Time Synchronization...
Apr 26 09:28:57 mark-lap systemd-timedated[9135]: Set NTP to disabled
Apr 26 09:28:57 mark-lap systemd[1]: systemd-timesyncd.service: Succeeded.
Apr 26 09:28:57 mark-lap systemd[1]: Stopped Network Time Synchronization.
Apr 26 09:28:57 mark-lap audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 26 09:28:57 mark-lap kernel: audit: type=1131 audit(1556288937.644:171): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 26 09:28:57 mark-lap systemd[1]: Reloading.
Apr 26 09:28:57 mark-lap systemd-timedated[9135]: Set NTP to enabled
Apr 26 09:28:57 mark-lap systemd[1]: Started Network Time Synchronization.
Apr 26 09:28:57 mark-lap audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 26 09:28:57 mark-lap kernel: audit: type=1130 audit(1556288937.791:172): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 26 09:28:58 mark-lap systemd-timesyncd[9164]: Synchronized to time server for the first time 10.101.111.111:111 (SOMEDOMAIN.COM)
```

**Comment by mrkz** [comment] 2019-05-06 22:21
Ok, found the culprint on this issue.

We use `systemd-timesyncd` as NTP client, so when `gnome-control-center` asks for NTP to be disabled, it's effectively disabled/stopped, however, due to a regression ([timedate: fix emitted value when ntp client is enabled/disabled #11951](https://github.com/systemd/systemd/issues/11944)) on systemd-241 (current version on clearlinux) we're getting hit by this same issue.

We're cherry-picking the fix on systemd and pushing a fix, so hopefully this should be resolved in release **29250** or later.

Will comment & close once the fix is released.

**Closed** 2019-05-07 20:31 UTC
Labels: bug, high priority

**Comment by dvtate** [comment] 2019-06-09 23:51
![image](https://user-images.githubusercontent.com/15305612/59165825-69494a00-8ae7-11e9-8e2d-780ee7fac474.png)
![image](https://user-images.githubusercontent.com/15305612/59165831-81b96480-8ae7-11e9-95b2-df1d3c3ca7bf.png)
