### ISSUE TITLE
Black screen with blinking underscore after fresh install, versions after 39400 (link in mainpage) affected. Fix included.

### ISSUE THREAD

**Issue by mikma-git** [clearlinux/distribution#2926] opened 2023-07-15 14:54 UTC
Hello!

Background:
I installed 39400 that didn't work, and then installed 39600 which also didn't work, and started to investigate the logs.

Problem:
I booted up Clear Linux with Live USB and installed Clear Linux 39630 to my Intel NUC with destructive install. 
After install was completed, I rebooted my pc and was greeted with black screen with blinking underscore, which after a short time stopped blinking and nothing happened.

Here's the reason from dmesg:
[    3.811580] gnome-shell[755]: segfault at 80 ip 00005620f89f8e10 sp 00005620c27faec8 error 4 cpu 3 in libxkbcommon.so.0.0.0[5620f89e0000+21000] likely on CPU 3 (core 1, socket 0)

Linked are two logs:
[CL39630_journalctl-full.txt](https://github.com/clearlinux/distribution/files/12061906/CL39630_journalctl-full.txt) - This is the complete output of journalctl.
[CL39630_segfault-short.txt](https://github.com/clearlinux/distribution/files/12061907/CL39630_segfault-short.txt) - The reason of gnome-shell segfault from journalctl.

Solution which I confirmed to fix this issue:
Install x11-tools.
`ssh mikma@ipaddress`
`sudo swupd bundle-add x11-tools`
`sudo reboot`

After the reboot the GUI boots up just fine.

**Comment by Aqua1ung** [comment] 2023-07-15 22:56
Duplicate of https://github.com/clearlinux/distribution/issues/2920.

**Closed** 2023-10-07 06:44 UTC
Labels: bug, new
