### ISSUE TITLE
Chrome?

### ISSUE THREAD

**Issue by ldmtwo** [clearlinux/distribution#432] opened 2018-06-14 03:42 UTC
I've been trying to follow the instructions for creating a bundle to add RPMs, but I do not see the desired result at the end. I planned to install Chrome via .rpm. Could you guys update the documentation to specifically install RPMs?

As for the material I was reading, this did not seem to work and it's a bit confusing. Local bundles created via mixer cannot be installed  via "swupd bundle-add bundle1"
https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer
https://clearlinux.org/documentation/clear-linux/guides/maintenance/swupdaddpkg

"mixer bundle list local" shows bundle1 that I created (as root).

Maybe chrome won't work in the end, but I would rather see an error than be confused. Thanks.

**Comment by nesiusra** [comment] 2019-02-12 19:28
@ahkok  - have you been looking at Chrome in Clear lately? Your thoughts?

**Comment by Mountainerd** [comment] 2019-04-18 03:39
If you don't have a Debian/Ubuntu environment handy, I wrote up a quick Docker container image that will make the AppImage and dump it into the mounted directory you map in. Nothing fancy but it outputs a working Google Chrome.
`docker pull jaybee83/clr-appimages:chrome`
`docker run --rm -v /path/to/dir:/mnt/out jaybee83/clr-appimages:chrome`

**Comment by ahkok** [comment] 2019-04-22 21:15
Dupe of #422

**Closed by ahkok** 2019-04-22 21:15 UTC
Labels: duplicate, question
