### ISSUE TITLE
37300 to 37310 = black screen

### ISSUE THREAD

**Issue by KaeLL** [clearlinux/distribution#2781] opened 2022-12-09 17:22 UTC
A couple hundred meters down the rabbit hole of installing CL on a 5800X3D + 3060 TI, I've reached this issue in which one of the bundles below result in a black screen following a reboot or log out. The reason I'm focusing on these 2 revisions is because apparently every other after 37300 display the same behavior (I've tested 10 between 37300 and 37730). It's also not possible to switch to other tty's, or even reboot with Ctrl + Alt + Del.
<details>
<summary>37300 to 37310 list of bundles to be updated</summary>

```
Update started
Preparing to update from 37300 to 37310
Downloading packs (230.29 MB) for:
 - NetworkManager
 - NetworkManager-extras
 - NetworkManager-tui
 - alsa-utils
 - aspell
 - baobab
 - binutils
 - bootloader
 - c-basic
 - cheese
 - cloud-api
 - connections
 - curl
 - desktop
 - desktop-apps
 - desktop-assets
 - desktop-autostart
 - desktop-gnomelibs
 - desktop-locales
 - emacs-x11
 - eog
 - evince
 - evolution
 - file-roller
 - firefox
 - flatpak
 - fonts-basic
 - geary
 - gedit
 - ghostscript
 - gimp
 - git
 - gjs
 - gnome-calculator
 - gnome-characters
 - gnome-color-manager
 - gnome-disk-utility
 - gnome-font-viewer
 - gnome-logs
 - gnome-music
 - gnome-photos
 - gnome-screenshot
 - gnome-system-monitor
 - gnome-text-editor
 - gnome-todo
 - gnome-weather
 - gnupg
 - graphviz
 - gstreamer
 - gvim
 - hardware-printing
 - kernel-native
 - lib-imageformat
 - lib-opengl
 - lib-poppler
 - lib-samba
 - libX11client
 - libglib
 - libstdcpp
 - llvm
 - nautilus
 - openblas
 - openssh-server
 - os-core
 - os-core-plus
 - os-core-update
 - perl-basic
 - polkit
 - poppler
 - pulseaudio
 - pygobject
 - python-extras
 - python3-basic
 - qt-basic
 - qt-core
 - seahorse
 - sysadmin-basic
 - thermal_daemon
 - totem
 - tzdata
 - vim
 - webkitgtk
 - wpa_supplicant
 - x11-server
 - xz
 - zstd
 ```

</details>

**Comment by KaeLL** [comment] 2022-12-09 17:56
Just checked the release notes, and 37310 brought Gnome 43. What can I do to help fix this?

**Comment by bryteise** [comment] 2022-12-10 02:52
Which graphics drivers are you using for this? I am running nouveau but with KDE and not seeing a problem with 37300 and just want to know if I can replicate it if I try to use gnome.

**Comment by KaeLL** [comment] 2022-12-10 19:57
I haven't really changed anything in the installation, so nouveau.

**Comment by KaeLL** [comment] 2022-12-13 15:39
Is there anything else I can/should do, @bryteise?

**Comment by bryteise** [comment] 2022-12-13 19:43
Any chance you've tried both wayland and x11 and see the same results?

**Comment by KaeLL** [comment] 2022-12-13 19:58
Since it doesn't even get to the login screen, no. Is there a way to sort of pass a kernel parameter to initialize Wayland or something like that?

**Comment by bryteise** [comment] 2022-12-13 20:29
Any chance you can get an ssh server running on the system and see if you can login to it remotely? I am seeing a gnome crash but it is in a VM (and not nvidia) so I'm unsure if it is using the same path.

**Comment by KaeLL** [comment] 2022-12-13 21:11
Done. Now what?

**Comment by bryteise** [comment] 2022-12-13 21:13
If you are able to login via ssh, try looking at `journalctl -b` and see if you spot anything related to gnome-session having problems.

**Comment by KaeLL** [comment] 2022-12-13 21:15
```
Dec 13 18:12:29 qwert gnome-session-binary[543]: WARNING: Application 'org.gnome.Shell.desktop' failed to register before timeout
Dec 13 18:12:29 qwert gnome-session-binary[543]: Unrecoverable failure in required component org.gnome.Shell.desktop
Dec 13 18:12:29 qwert /usr/libexec/gdm-wayland-session[542]: dbus-daemon[542]: [session uid=311 pid=542] Activating service name='ca.desrt.dconf' requested by ':1.2' (uid=311 pid=543 comm="/usr/libexec/gnome-session-binary --autostart /u>
Dec 13 18:12:29 qwert /usr/libexec/gdm-wayland-session[542]: dbus-daemon[542]: [session uid=311 pid=542] Successfully activated service 'ca.desrt.dconf'
Dec 13 18:12:29 qwert dbus-daemon[421]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.26' (uid=311 pid=748 comm="/usr/libexec/gsd-rfkill ")
Dec 13 18:12:29 qwert systemd[1]: Starting Hostname Service...
Dec 13 18:12:29 qwert /usr/libexec/gdm-wayland-session[542]: dbus-daemon[542]: [session uid=311 pid=542] Activating service name='org.freedesktop.systemd1' requested by ':1.13' (uid=311 pid=759 comm="/usr/libexec/gsd-sharing ")
Dec 13 18:12:29 qwert /usr/libexec/gdm-wayland-session[542]: dbus-daemon[542]: [session uid=311 pid=542] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Dec 13 18:12:29 qwert gsd-sharing[759]: Failed to StopUnit service: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1
Dec 13 18:12:29 qwert gsd-sharing[759]: Failed to StopUnit service: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1
Dec 13 18:12:29 qwert systemd[1]: Started CUPS Scheduler.
Dec 13 18:12:29 qwert cupsd[814]: REQUEST localhost - - "POST / HTTP/1.1" 200 356 Create-Printer-Subscriptions successful-ok
Dec 13 18:12:29 qwert dbus-daemon[421]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dec 13 18:12:29 qwert systemd[1]: Started Hostname Service.
Dec 13 18:12:59 qwert systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Dec 13 18:13:59 qwert gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.Keyboard.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session[543]: gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.Keyboard.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session[543]: gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session[543]: gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.Power.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session[543]: gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.Color.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session-binary[543]: Unrecoverable failure in required component org.gnome.SettingsDaemon.Keyboard.desktop
Dec 13 18:13:59 qwert gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session-binary[543]: Unrecoverable failure in required component org.gnome.SettingsDaemon.MediaKeys.desktop
Dec 13 18:13:59 qwert gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.Power.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session-binary[543]: Unrecoverable failure in required component org.gnome.SettingsDaemon.Power.desktop
Dec 13 18:13:59 qwert gnome-session-binary[543]: WARNING: Application 'org.gnome.SettingsDaemon.Color.desktop' failed to register before timeout
Dec 13 18:13:59 qwert gnome-session-binary[543]: Unrecoverable failure in required component org.gnome.SettingsDaemon.Color.desktop
Dec 13 18:13:59 qwert gnome-session-binary[543]: Entering running state
```

**Comment by bryteise** [comment] 2022-12-13 21:21
Huh alrighty, not quite seeing what is going wrong from that. Would you mind posting the full `journalctl -b` output?

**Comment by KaeLL** [comment] 2022-12-13 21:23
Sure
https://termbin.com/hw60

**Comment by KaeLL** [comment] 2022-12-13 21:24
Its in reverse now, btw

**Comment by bryteise** [comment] 2022-12-13 21:28
Looks like the nouveau driver is having a problem based on the stack trace. Not really sure what to do with that though =/.

**Comment by KaeLL** [comment] 2022-12-13 21:33
:/

**Comment by KaeLL** [comment] 2022-12-13 21:36
Does the 37300 - 37310 diff tells anything?

**Comment by bryteise** [comment] 2022-12-13 21:52
Only gnome 43 doing something the nouveau driver doesn't like. I will say I run sddm + KDE and use the nouveau driver so it appears gnome specific.

**Comment by KaeLL** [comment] 2022-12-13 22:19
With that, the GUI works now. Here's the journalctl if you want to see the difference: https://termbin.com/znj4
I'm now updating to 37740 to see if there are any issues.

**Comment by KaeLL** [comment] 2022-12-13 22:38
Alright, so after the update, X.org crashes: https://termbin.com/i2si

**Comment by KaeLL** [comment] 2022-12-13 22:43
And if I remove the custom.conf to start Wayland, it crashes all the same, and apparently, it tries to start X after Wayland doesn't work, and crashes again (not reversed this time)
https://termbin.com/4x1br

**Comment by bryteise** [comment] 2022-12-13 23:06
Any chance you can try a run of the kernel from 37310 in the 37740 userspace? Not a good time either way.

**Comment by KaeLL** [comment] 2022-12-13 23:08
How do I do that?

**Comment by bryteise** [comment] 2022-12-13 23:23
You can check over ssh into the system if clr-boot-manager still lists the old kernel. Otherwise, you'd need to go back to 37310, reboot, run the update and then modify `/boot/loader/loader.conf` to use the old kernel as the default (can be done via clr-boot-manager's set-kernel if you'd prefer though I'd double check the loader.conf either way as this is painful to get the older kernel back).

**Comment by KaeLL** [comment] 2022-12-13 23:27
It does list the old one, and I just learned about clr-boot-manager, set it to run the older kernel, and got basically the same thing (both X and Wayland breaking): https://termbin.com/jac3

**Comment by bryteise** [comment] 2022-12-13 23:34
Alrighty, well something in userspace. Unfortunately lots of change between 37310 and 37740.

**Comment by KaeLL** [comment] 2022-12-13 23:37
Is "bisecting" the versions the only way? If so, to your knowledge, how can I optimize the process to a maximum?

**Comment by bryteise** [comment] 2022-12-13 23:46
You might be able to pick more likely candidates to inspect via https://cdn.download.clearlinux.org/releases/$VER/clear/RELEASENOTES but it will be mostly guesses around glib/gnome updates.

```
                                             #10 0x000055a30886c91c gbm_create_device (libgbm.so.1.0.0 + 0x491c)
                                             #11 0x000055a30c29abe9 meta_render_device_gbm_initable_init (libmutter-11.so.0.0.0 + 0x1cebe9)
                                             #12 0x000055a30d3a9967 g_initable_new (libgio-2.0.so.0.7400.1 + 0x9d967)
                                             #13 0x000055a30c26f146 create_render_device.lto_priv.0 (libmutter-11.so.0.0.0 + 0x1a3146)
                                             #14 0x000055a30c26fb16 add_drm_device (libmutter-11.so.0.0.0 + 0x1a3b16)
                                             #15 0x000055a30c27134d meta_backend_native_initable_init (libmutter-11.so.0.0.0 + 0x1a534d)
                                             #16 0x000055a30d3a9967 g_initable_new (libgio-2.0.so.0.7400.1 + 0x9d967)
                                             #17 0x000055a30c19fcf5 meta_context_real_setup (libmutter-11.so.0.0.0 + 0xd3cf5)
                                             #18 0x000055a30c1a7402 meta_context_main_setup (libmutter-11.so.0.0.0 + 0xdb402)
                                             #19 0x000055a30c1a7699 meta_context_setup (libmutter-11.so.0.0.0 + 0xdb699)
                                             #20 0x000055a30d83460d main (gnome-shell + 0x460d)
```
Any of the binaries in that backtrace would be the main candidates I'd check for updates to.

**Comment by KaeLL** [comment] 2022-12-14 00:04
What's the best way to revert to an older version from a nuked install? I know that going forward can be done by a `swupd update -V $VER`. What about the other way around? I'd have to repair the installation (liveusb + swupd repair)?

**Comment by bryteise** [comment] 2022-12-14 00:16
As long as you can ssh into the bad version, running `swupd repair -V $VER -x` will allow you to go backwards.

**Comment by bryteise** [comment] 2022-12-14 00:17
Otherwise, liveusb is probably the easier method.

**Comment by KaeLL** [comment] 2022-12-14 19:52
For the record, I wish you guys did something about the egregiously slow updates/repairs, specially the former. It's borderline absurd watching my ssd/net/cpu basically idle, with the occasional transient spike in net usage :(
Each update/repair taking up to 40 minutes is really discouraging, it's probably faster to do a usb reinstall.

**Comment by bryteise** [comment] 2022-12-14 20:08
The updates are really optimized for updating from previous to next release (the auto update path). We also made a lot of improvements in 37600+ that would make it not as painful to update from that. Unfortunately repair is a slow path because it does the work file by file.

We could look at having repair build a list of files instead first but that'll need a fair amount of work to get the logic in place to find what bundles are worth downloading vs getting a single file.

**Comment by KaeLL** [comment] 2022-12-14 23:07
Alright, so version 37330 is the one in which Xorg starts to crash. Here are the logs: https://termbin.com/pw7d8
Worth remembering that Wayland starts to break at 37310, which I wouldn't mind too much if X was working and if I was running proprietary drivers, both of which aren't the case, so I guess it's relevant.

**Comment by KaeLL** [comment] 2022-12-14 23:11
And `swupd repair` was a waste of time, as Gnome kept giving me the "oh no, something has gone wrong" window. So I nuked it by reinstalling 37300 and updated version by version (which luckily was only 3 versions).

**Comment by KaeLL** [comment] 2022-12-15 20:36
@bryteise anything else I should do?

**Comment by bryteise** [comment] 2022-12-16 19:56
I'm away from the office until Monday, I'll try to get in and see if I can reproduce but I don't see anything obvious in the 37330 [changelog](https://cdn.download.clearlinux.org/releases/37330/clear/RELEASENOTES).

**Comment by KaeLL** [comment] 2022-12-21 19:11
Got anything for me, @bryteise ?

**Comment by bryteise** [comment] 2022-12-21 19:58
Not yet unfortunately.

**Comment by fenrus75** [comment] 2023-01-19 14:16
is it really X or wayland (please use wayland and not X... X is effectively
nearly unmaintained upstream and it's increasingly hard to get it to work
on hardware that/s well supported by linux, never mind nvidia binary)

**Comment by SPAstef** [comment] 2023-01-19 15:47
@fenrus75 So the issue seems to be GDM, since in a last desperate attempt I switched to SDDM and was able to get to the desktop, I'm so happy.
Note that TTY still does not "work", so I have to blindly type commands/use SSH... but at least I got to the desktop.
The issue probably has to do with the new version of GNOME that defaults to Wayland for newer versions of the NVIDIA Driver. Unfortunately, under Wayland nvidia-settings basically has no options... and I don't know about 3D acceleration?

Last time I used Wayland it was very bad with NVIDIA drivers... Might give it another try now...

**Comment by KaeLL** [comment] 2023-01-19 15:53
@SPAstef what did you do? Just installed sddm and rebooted?

**Comment by SPAstef** [comment] 2023-01-19 15:58
> @SPAstef what did you do? Just installed sddm and rebooted?

Yes, and remember to enable sddm.service in systemctl and disable GDM (actually, you can have both, one will be in CTRL+ALT+F1 and the other in CTRL+ALT+F2)

**Comment by KaeLL** [comment] 2023-01-19 16:17
On 37330, sddm at least gets me to the login screen, and both Wayland and X are broken. Weston works LOL.

**Comment by SPAstef** [comment] 2023-01-19 16:44
> 

eh, took me 2 hours with 100mbit/s internet, good luck

**Closed** 2023-01-30 16:20 UTC
Labels: bug, new
