### ISSUE TITLE
Failure to install VBoxGuestAdditions in VirtualBox

### ISSUE THREAD

**Issue by dzvyper** [clearlinux/distribution#23] opened 2018-03-18 14:11 UTC
Hello All,

Trying to install the ClearLinux in VirtualBox however facing a constant issue with failure in installing VBoxGuestAdditions. Followed instructions in https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox , however getting constant behavior specified here: 

![clearlinux_vboxguestadditions_issue](https://user-images.githubusercontent.com/37507581/37566809-bb3b9cc8-2ac6-11e8-8571-6aaeb29f8a02.gif)

Would you please help with the issue.

**Comment by icarus-sparry** [comment] 2018-03-28 20:27
I believe the problem is that virtualbox guest additions wants to build an out of tree kernel module, which is not supported for the stock kernels that are shipped with clearlinux.

Can you confirm you are running the lts kernel (i.e. what is the output of `uname -a` ?)

**Comment by dzvyper** [comment] 2018-03-29 07:51
@icarus-sparry for your question I do use the LTS kernel (please see below):

![clearlinux 21390 lts snapshot](https://user-images.githubusercontent.com/37507581/38076661-f467af02-333e-11e8-9d20-bc3cca29592b.jpg)

As for assumption regarding the building and installation of the out-of-tree VBox kernel modules, I'm not quite sure, since if I follow the script install-vbox-lga that is found under /usr/bin we can notice that it actually fails on check_kernel() here:

`  
    if ! modprobe vboxsf &> /dev/null; then
        die "VBOX KERNEL MODULES NOT FOUND" \
        "Please use
        swupd verify --fix
        to fix your installation."
    fi
`
after checking the /lib/modules/4.14.21-380.lts folder I couldn't find any vboxsf module.

Do you have a clue ?

**Comment by marziopulcini** [comment] 2018-03-30 07:47
Hello, same issue here. I've tried to find a vboxsf.ko module in my installed kernels but I could not find it.
Please see below.
Looking forward to have the vboxsf support back in lts.
Thanks,
Marzio.

![virtualbox_clearlinux_30_03_2018_09_43_28](https://user-images.githubusercontent.com/6493671/38129372-17ac59a2-33ff-11e8-87da-b93551d7e629.png)

**Comment by dzvyper** [comment] 2018-04-01 11:21
@icarus-sparry Great. Thanks for the update and clarification.
We are waiting for the updated release. Please update us (me and @marziopulcini ) if you can the moment it will be available.

**Comment by dzvyper** [comment] 2018-04-09 13:04
@icarus-sparry Do you have any update ?

**Comment by icarus-sparry** [comment] 2018-04-09 19:27
It is in progress.

Kernel 4.16 added some, but not all, of the virtualbox support into the mainline kernel which has complicated the issue. 

At the moment the plan is to add the rest of the code via patches to the main kernel we release and update the documentation to say to use the main kernel, rather than the lts kernel.

Sorry I don't have an ETA.

**Comment by iphutch** [comment] 2018-04-23 20:31
@bwarden  any update?

**Comment by bwarden** [comment] 2018-04-23 20:47
VBoxGuestAdditions should be back in linux-lts as of Clear Linux release 21860, right @miguelinux?

**Comment by dzvyper** [comment] 2018-04-29 19:33
Just to update all. Tested the latest release 22160 with VirtualBox 5.2.4.
Looks working after installing the VBoxAdditions with install-vbox-lga, reboting and then restarting the whole VM.

![image](https://user-images.githubusercontent.com/37507581/39410200-e38fc882-4bfc-11e8-8a31-47caed7f4c37.png)

Thanks to @icarus-sparry and @miguelinux for taking care of the issue.

**Comment by iphutch** [comment] 2018-04-30 05:32
Excellent! Closing issue. Thanks everyone!

**Closed by iphutch** 2018-04-30 05:32 UTC
