### ISSUE TITLE
When trying to enable monitoring with lvchange it fails with code 5 and logs show libdevmapper-event-lvm2thin.so can't be opened although that file exists.

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#1492] opened 2019-11-15 00:14 UTC
This issue is occurring on two systems each at Clear Linux 31640 with the `storage-utils` bundle installed. I have used `systemctl` to enable the `lvm2-lvmetad.socket`.

I am following the [Docker devicemapper guide](https://docs.docker.com/storage/storagedriver/device-mapper-driver/#manage-devicemapper) and am following the steps for configuring direct-lvm mode manually.  I installed Clear Linux with a 100GB unformatted partition at the end at `/dev/nvme0n1p4` to use.  When I get to step 7 using the `lvconvert` command I get an error that monitoring was not enabled.  When I get to step 11 and try to enable monitoring I get the following.

```
  WARNING: Monitoring docker/thinpool failed.
  Command failed with status code 5.
```

When I check `journalctl -xe` I see this error.
```
dmeventd[1148]: dmeventd libdevmapper-event-lvm2thin.so dlopen failed: libdevmapper-event-lvm2thin.so: cannot open shared object file: No such file or directory.
```
The file does exist at
```
-r-xr-xr-x 1 root root 18408 Sep 11 11:50 ./lib64/device-mapper/libdevmapper-event-lvm2thin.so
```

EDIT: I forgot to mention that this is failing on two different systems at the same build. Also, this did work on the system above when I had an older version of clear linux (maybe 1 month old but I forgot to look before I upgraded)

**Comment by hongzhanchen** [comment] 2019-11-21 00:58
Could you try ln -s /lib64 /usr/lib64 and then redo again to check if the issue disappear？  I found that soft link is broken on some version of /lib   before  with unknown reason but do not know if it is same issue.

**Comment by eadamsintel** [comment] 2019-12-03 21:27
The problem still persists when trying that command.  The file does already exist at `/lib64/device-mapper/libdevmapper-event-lvm2thin.so`  I ran that `ln` command above but it didn't fix anything. It added a path `/usr/lib64/lib64`  and there already is a `/usr/lib64`

However, I did copy `cp /lib64/device-mapper/libdevmapper-event-lvm2thin.so /lib64` and reran that monitoring command and it worked.

```
root@kata3/usr/lib64 # lvchange --monitor y docker/thinpool
  WARNING: Monitoring docker/thinpool failed.
  Command failed with status code 5.

root@kata3/lib64 # cp /lib64/device-mapper/libdevmapper-event-lvm2thin.so /lib64
root@kata3/lib64 # lvs -o+seg_monitor
  LV       VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Monitor
  thinpool docker twi-a-t--- <92.77g             0.00   1.62                             not monitored
root@kata3/lib64 # sudo lvchange --monitor y docker/thinpool
root@kata3/lib64 # lvs -o+seg_monitor
  LV       VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Monitor
  thinpool docker twi-a-t--- <92.77g             0.00   1.62                             monitored
```

**Comment by hongzhanchen** [comment] 2019-12-04 02:13
@eadamsintel, thanks for your feedback. It seems that libdevmapper-event-lvm2thin.so is missing under /lib64. According to definition in LVM2.spec , libdevmapper-event-lvm2thin.so should exist in both /usr/lib64/ and /usr/lib64/device-mapper/ but /lib64 is linked to /usr/lib64/ in clear.
![image](https://user-images.githubusercontent.com/42202712/70106429-96ce1500-167e-11ea-8d41-5d5fe466d249.png)

**Comment by hongzhanchen** [comment] 2019-12-06 01:46
Since the issue disappear after cp /lib64/device-mapper/libdevmapper-event-lvm2thin.so /lib64 ,let me close this issue.

**Comment by thiagomacieira** [comment] 2019-12-06 15:44
Is the fix in Clear itself or just on your installation? If it's just in your installation, the issue should remain open.

**Comment by eadamsintel** [comment] 2019-12-06 18:26
The fix was just local to my system. I think it still needs to be fixed in Clear Linux.

**Comment by hongzhanchen** [comment] 2019-12-09 01:04
@eadamsintel , if there is lib or file missing in you local system ,you can use "swupd diagnose" to checkout it out and then use "swupd repair" to correct the "file missing" problem. 

@thiagomacieira , if we can use "swupd repair" to fix this issue, can we close this issue?

**Comment by thiagomacieira** [comment] 2019-12-09 06:09
Yes, if a clean & up-to-date system cannot reproduce the problem, we can close. But from what I understood, the problem does happen in a clean system.

**Comment by eadamsintel** [comment] 2019-12-09 16:55
It happened on my clean system and happened on another relatively up to date system as well.

**Comment by hongzhanchen** [comment] 2019-12-10 01:28
@eadamsintel ，could help check  if  the symlink /lib64/libdevmapper-event-lvm2thin.so  is present and what it points to when issue happen?

**Comment by sunnyflunk** [comment] 2019-12-10 02:21
Looking at the .spec, some files are in the wrong subpackage. These symlinks are in the `-dev` subpackage (so don't get installed on most machines), which aren't development symlinks to versioned sonames, but make the same file availble one directory higher (without /device-mapper/ path which is being used for dlopen).

```
/usr/lib64/libdevmapper-event-lvm2mirror.so
/usr/lib64/libdevmapper-event-lvm2raid.so
/usr/lib64/libdevmapper-event-lvm2snapshot.so
/usr/lib64/libdevmapper-event-lvm2thin.so
/usr/lib64/libdevmapper-event-lvm2vdo.so
```

Moving these files into the `-lib` subpackage means that the symlinks would now be installed on machines (fixing this issue), and the files they symlink too are already part of the `-lib` subpackage (no broken links).


Possibly a better solution would be to add all the devmapper files to `lib_extras`, as I assume they won't actually work without the other devmapper libraries already in `-extras-lib` anyway (the `lvchange` command generating this bug links against them)

```
diff --git a/lib_extras b/lib_extras
index ce84ffa..e4f5925 100644
--- a/lib_extras
+++ b/lib_extras
@@ -1,3 +1,13 @@
+/usr/lib64/device-mapper/libdevmapper-event-lvm2mirror.so
+/usr/lib64/device-mapper/libdevmapper-event-lvm2raid.so
+/usr/lib64/device-mapper/libdevmapper-event-lvm2snapshot.so
+/usr/lib64/device-mapper/libdevmapper-event-lvm2thin.so
+/usr/lib64/device-mapper/libdevmapper-event-lvm2vdo.so
 /usr/lib64/libdevmapper-event-lvm2.so.2.02
+/usr/lib64/libdevmapper-event-lvm2mirror.so
+/usr/lib64/libdevmapper-event-lvm2raid.so
+/usr/lib64/libdevmapper-event-lvm2snapshot.so
+/usr/lib64/libdevmapper-event-lvm2thin.so
+/usr/lib64/libdevmapper-event-lvm2vdo.so
 /usr/lib64/libdevmapper-event.so.1.02
 /usr/lib64/libdevmapper.so.1.02
```

**Comment by hongzhanchen** [comment] 2019-12-10 02:51
storage-utils bundle does not include LVM2-dev subpackage so it will be missing /usr/lib64/libdevmapper-event-lvm2thin.so in this case.
storage-utils:LVM2
storage-utils:LVM2-extras

But devpkg-LVM2 bundle includes LVM2-dev (devpkg-LVM2:LVM2-dev)

@sunnyflunk ,Thanks for your comments. It is clear now.

@eadamsintel , please install one more bundle devpkg-LVM2 ,which will install  LVM2-dev in your case to fix this issue. I just checked my system and actually I installed devpkg-LVM2 so that I can not reproduce this issue.

**Comment by eadamsintel** [comment] 2019-12-10 18:41
@hongzhanchen  On a fresh install of Clear installing the devpkg-LVM2 bundle did fix the issue without me having to manually copy to `/lib64`

Installing `storage-utils` bundle but not `devpgk-LVM2` bundle has the following in `lib64`
```

root@kata2/lib64 # ll libdevmapper*
-r-xr-xr-x 1 root root  14368 Sep 11 11:50 libdevmapper-event-lvm2.so.2.02
-r-xr-xr-x 1 root root  26616 Sep 11 11:50 libdevmapper-event.so.1.02
-r-xr-xr-x 1 root root 294448 Sep 11 11:50 libdevmapper.so.1.02
```

After installing `devpkg-LVM2` bundle
```
root@kata2/lib64 # ll libdevmapper*
lrwxrwxrwx 2 root root     46 Sep 11 11:50 libdevmapper-event-lvm2mirror.so -> device-mapper/libdevmapper-event-lvm2mirror.so
lrwxrwxrwx 2 root root     44 Sep 11 11:50 libdevmapper-event-lvm2raid.so -> device-mapper/libdevmapper-event-lvm2raid.so
lrwxrwxrwx 2 root root     48 Sep 11 11:50 libdevmapper-event-lvm2snapshot.so -> device-mapper/libdevmapper-event-lvm2snapshot.so
lrwxrwxrwx 2 root root     31 Sep 11 11:50 libdevmapper-event-lvm2.so -> libdevmapper-event-lvm2.so.2.02
-r-xr-xr-x 1 root root  14368 Sep 11 11:50 libdevmapper-event-lvm2.so.2.02
lrwxrwxrwx 2 root root     44 Sep 11 11:50 libdevmapper-event-lvm2thin.so -> device-mapper/libdevmapper-event-lvm2thin.so
lrwxrwxrwx 2 root root     43 Sep 11 11:50 libdevmapper-event-lvm2vdo.so -> device-mapper/libdevmapper-event-lvm2vdo.so
lrwxrwxrwx 2 root root     26 Sep 11 11:50 libdevmapper-event.so -> libdevmapper-event.so.1.02
-r-xr-xr-x 1 root root  26616 Sep 11 11:50 libdevmapper-event.so.1.02
lrwxrwxrwx 2 root root     20 Sep 11 11:50 libdevmapper.so -> libdevmapper.so.1.02
-r-xr-xr-x 1 root root 294448 Sep 11 11:50 libdevmapper.so.1.02
```

Shouldn't the `storage-utils` bundle have all of these things in `/lib64` by default?

**Comment by hongzhanchen** [comment] 2019-12-11 02:21
@eadamsintel, Yes, to avoid functionality broken, storage-utils should have all of them. I already committed a patch to review.

**Comment by hongzhanchen** [comment] 2019-12-16 00:42
@eadamsintel , Version 31890  already included the fix  ,which  storage-utils bundle includes libs that was missing before.

**Comment by eadamsintel** [comment] 2019-12-16 17:09
I had just reinstalled Clear Linux and noticed it was working. Thanks for letting me know.

**Closed** 2019-12-16 17:46 UTC
Labels: bug, cloud-native
