### ISSUE TITLE
Cannot boot the native 6.5.3 kernel

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2957] opened 2023-09-16 04:55 UTC
```text
/dev/root: Can't open blockdev

List of all bdev filesytems:
ext3
ext2
ext4
squashfs
vfat
fuseblk
xfs
f2fs
btrfs

VFS: Unable to mount root fs on unknown-block(0,0)
```

![image](https://github.com/clearlinux/distribution/assets/7031085/818a593a-4627-4405-ac5f-f01a0e54d066)

I has been a long while since I ran the native kernel on this machine. The LTS 6.1.53 kernel works fine. So, I tried the prior native 6.4.13 kernel and that one boots fine. I captured dmesg hw info running LTS. Is the `ASMedia` hardware no longer supported in 6.5.x?

```text
[    3.059578] usb 8-4.4: new SuperSpeed USB device number 4 using xhci_hcd
[    3.072881] usb 8-4.4: New USB device found, idVendor=174c, idProduct=1153, bcdDevice= 1.00
[    3.072886] usb 8-4.4: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[    3.072887] usb 8-4.4: Product: External USB 3.0
[    3.072888] usb 8-4.4: Manufacturer: ASMedia
[    3.072889] usb 8-4.4: SerialNumber: 123456789115
[    3.074830] scsi host2: uas 
[    3.075239] scsi 2:0:0:0: Direct-Access     Samsung  SSD 860 EVO 250G 0    PQ: 0 ANSI: 6
[    3.076652] sd 2:0:0:0: Attached scsi generic sg0 type 0
[    3.076876] sd 2:0:0:0: [sda] 488397168 512-byte logical blocks: (250 GB/233 GiB)
[    3.077011] sd 2:0:0:0: [sda] Write Protect is off
[    3.077014] sd 2:0:0:0: [sda] Mode Sense: 43 00 00 00
[    3.077173] sd 2:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    3.077347] sd 2:0:0:0: [sda] Preferred minimum I/O size 512 bytes[    3.077349] sd 2:0:0:0: [sda] Optimal transfer size 33553920 bytes
[    3.081709]  sda: sda1 sda2
[    3.081801] sd 2:0:0:0: [sda] Attached SCSI disk
```
```text
lsusb | grep '174c:1153'
Bus 008 Device 004: ID 174c:1153 ASMedia Technology Inc. ASM1153 SATA 3Gb/s bridge
```

**Comment by marioroy** [comment] 2023-09-16 09:52
https://forums.unraid.net/topic/133816-the-all-too-common-kernel-panic-not-syncing-vs-unable-to-mount-root-fs-on-unknown-block00/

**Comment by fenrus75** [comment] 2023-09-16 12:19
ah ha USB based storage... will look into that
(USB storage has very different timing than anything else)

**Comment by marioroy** [comment] 2023-09-16 22:06
The 6.5.2 kernel on Fedora boots fine. Not sure if Fedora works due to a patch or if a bug introduced in 6.5.3.

**Comment by marioroy** [comment] 2023-09-19 22:34
It could very well be my USB drive. But, unsure as 6.4 and 6.1 boot without issues. The CL native 6.5 kernel from 39970 does not boot either.

**Comment by fenrus75** [comment] 2023-09-19 23:44
I fixed this this morning -- at least I hope I did (not easy to test)

**Comment by Aqua1ung** [comment] 2023-09-21 15:26
> I fixed this this morning -- at least I hope I did (not easy to test)

Just an FYI: if this was supposed to go away with 39980, it hasn’t. At least not for me.

**Comment by marioroy** [comment] 2023-09-21 15:43
The 6.5.4 kernel in 39980 does not boot for me either, using USB drive. My apologies, I ran out of storage options and unable to try another USB drive. The whole thing is weird. 6.1 and 6.4 kernels boot fine. And 6.5.2 boots fine on Fedora (different USB drive -- same HW and SSD manufacturers).

I searched the web and read many woes regarding USB. Perhaps, the work for USB4 / TB support that landed recently in 6.5 broke USB for the rest of us.

**Comment by fenrus75** [comment] 2023-09-21 16:01
the fix was been eaten by the typo monster unfortunately ;(
but more testing now and hopefully next build works better

the problem is complicated -- our kernel boots fast. very fast. and USB
devices show up about 100 msec to 500 msec after the USB host driver
loads...
on a slow booting kernel that's fine -- by the time you want to mount the
rootfs the device is there already.
we boot (depending on many things) pretty quick and we can be done booting
before the device is there.... and then you won't get your root fs.

so for the USB case we need to add some artificial delays in our boot and
there was a typo in a kernel patch there

**Comment by bryteise** [comment] 2023-09-21 17:30
Do you see this running a fresh kvm image? I haven't noticed an issue on my kvm image.

**Comment by fenrus75** [comment] 2023-09-21 17:39
same issue -- we applied the delay to the wrong case
(the non-usb case instead of the usb case)

**Comment by bwarden** [comment] 2023-09-21 22:58
Fix will be in https://github.com/clearlinux-pkgs/linux/releases/tag/6.5.4-1365

**Comment by marioroy** [comment] 2023-09-22 21:56
I can boot the 6.5.4-1365 kernel -- USB drive. Much appreciated. Ms. Grace and her friend Randomness sends their love.

**Closed** 2023-09-22 23:16 UTC
Labels: bug, new

**Comment by jokubasver** [comment] 2024-11-26 21:51
Experiencing this on 6.12.1-1493, previous release was fine

**Comment by bwarden** [comment] 2024-11-26 22:16
> Experiencing this on 6.12.1-1493, previous release was fine

Please open a new bug with your unique details.
