### ISSUE TITLE
clr-power.service taking a long time to start

### ISSUE THREAD

**Issue by rawsh** [clearlinux/distribution#898] opened 2019-06-15 00:15 UTC
systemd-anaylze blame:
```
         8.7326s clr-power.service
         1.7777s bolt.service
         394.9ms systemd-resolved.service
         290.8ms dev-nvme0n1p3.device
         263.4ms systemd-logind.service
         200.8ms systemd-journald.service
         200.0ms upower.service
         198.8ms systemd-udevd.service
          66.3ms accounts-daemon.service
          60.9ms systemd-udev-trigger.service
          50.7ms polkit.service
          46.4ms NetworkManager.service
          37.5ms ModemManager.service
          34.5ms user@1000.service
          34.1ms udisks2.service
          32.2ms systemd-journal-flush.service
          29.4ms colord.service
          23.8ms networkd-fallback.service
          21.1ms systemd-tmpfiles-setup.service
          17.5ms systemd-update-utmp.service
          17.3ms dev-nvme0n1p2.swap
          14.6ms systemd-rfkill.service
          13.5ms thermald.service
          12.5ms gdm.service
          11.8ms systemd-backlight@backlight:intel_backlight.service
```
status
```
● clr-power.service - Clear Linux Project for Intel Architecture power tweaks
   Loaded: loaded (/usr/lib/systemd/system/clr-power.service; static; vendor preset: disabled)
   Active: inactive (dead) since Fri 2019-06-14 19:05:09 CDT; 10min ago
 Main PID: 589 (code=exited, status=0/SUCCESS)

Jun 14 19:05:00 rawlinux systemd[1]: Starting Clear Linux Project for Intel Architecture power tweaks...
Jun 14 19:05:09 rawlinux systemd[1]: clr-power.service: Succeeded.
Jun 14 19:05:09 rawlinux systemd[1]: Started Clear Linux Project for Intel Architecture power tweaks.
```

**Comment by rawsh** [comment] 2019-06-15 00:16
Also having an issue opening power settings, it hangs but runs smoothly after about 15 seconds. No errors running the gnome-control-center from console.

**Comment by rawsh** [comment] 2019-06-15 19:49
Using refind boot manager
```
         4.8031s systemd-localed.service
         4.3606s rtkit-daemon.service
         391.1ms systemd-resolved.service
         362.2ms dev-nvme0n1p3.device
         329.8ms systemd-hostnamed.service
         249.0ms systemd-logind.service
         224.7ms systemd-udevd.service
         178.0ms systemd-journald.service
         176.7ms upower.service
          90.8ms clr-power.service
          70.0ms systemd-rfkill.service
          68.9ms systemd-udev-trigger.service
          53.6ms polkit.service
          47.7ms user@311.service
          39.2ms NetworkManager.service
          38.8ms ModemManager.service
          34.7ms udisks2.service
          34.3ms user@1000.service
          31.1ms systemd-journal-flush.service
          28.2ms colord.service
          22.0ms bolt.service
          20.3ms systemd-update-utmp.service
          19.9ms systemd-tmpfiles-setup.service
lines 1-23
```

**Comment by thac0** [comment] 2019-06-24 15:31
@rawsh - I cannot reproduce this issue on my machines. Doesn't mean it isn't an issue, just that I need your help to root cause and verify fixes.

[clr_power](https://github.com/clearlinux/clr-power-tweaks) performs a series of simple writes to various sysfs nodes to enable [runtime power management](https://www.kernel.org/doc/html/v5.1/driver-api/pm/devices.html#runtime-power-management) on a per-device basis. Likely one of those writes is triggering an unexpected delay, so we need to determine which-- one or many-- are slowing us down. (It takes single-digit milliseconds to run on my primary machine). If inserting some simple debug instrumentation into the code, before and after `fprintf()`, is something you're able and willing to do, go right ahead and let me know what you find.

Meanwhile, I'll see about adding a `debug` argument to clr_power for these sorts of exercises. If you happened to patch it yourself during that time, I'll happily roll in your contribution.

**Comment by thac0** [comment] 2019-06-26 21:26
I merged a -d/--debug option for clr_power. One could rebuild clr_power manually and install, or wait for a Clear Linux release that includes it. In either case, one would also need to change `/usr/lib/systemd/system/clr-power.service` to invoke clr_power with the "-d" argument. Then, upon reboot, journald should capture which clr_power operations are the long poles.

**Comment by phmccarty** [comment] 2019-06-26 23:47
Also, note that instead of modifying `/usr/lib/systemd/system/clr-power.service` directly, you could add a drop-in unit by running `sudo systemctl edit clr-power.service`, and add this content:

```
[Service]
ExecStart=
ExecStart=/usr/bin/clr_power -d
```

**Comment by thac0** [comment] 2019-07-01 16:31
@rawsh - I am unable to make progress on this issue due to lack of data/response. See @phmccarty 's comment just before this one on what we'd like you to do to help move this forward. To summarize, we'll need you to run clr_power with the "-d" flag at boot, and let us know the journald output. That will help us determine the long pole(s). This issue will be closed until that time.

**Closed by thac0** 2019-07-01 16:31 UTC
Labels: bug
