### ISSUE TITLE
vlc(flatpak) doesnot save subtitle in clear linux.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1412] opened 2019-10-29 14:03 UTC
![image](https://user-images.githubusercontent.com/12841320/67774230-13b90e00-fa85-11e9-89ef-3638a6e8347c.png)

**Comment by ahkok** [comment] 2019-10-29 15:50
Duplicate of upstream:

https://github.com/flathub/org.videolan.VLC/issues/70

**Closed by ahkok** 2019-10-29 15:50 UTC
Labels: bug

**Comment by nazar2sfive** [comment] 2019-10-30 04:02
@ahkok 
`mkdir ~/.var/app/org.videolan.VLC/cache/vlc`

just above solved problem for me
