### ISSUE TITLE
Gnome desktop does not remember audio mute after restart

### ISSUE THREAD

**Issue by yerbestpal** [clearlinux/distribution#819] opened 2019-05-29 14:10 UTC
Not a huge issue, but after a restart, Gnome will not remember if your audio was muted.
Current OS version: 29660

**Comment by skewty** [comment] 2019-06-09 16:08
It would be nice if this investigation also checked into saving and restoring the currently set volume level after restart.

**Comment by puneetse** [comment] 2020-01-24 21:22
Closing this as duplicate of https://github.com/clearlinux/distribution/issues/696

**Closed by puneetse** 2020-01-24 21:22 UTC
Labels: bug
