### ISSUE TITLE
Broken intel-compute-runtime

### ISSUE THREAD

**Issue by Airplaneless** [clearlinux/distribution#1347] opened 2019-10-12 10:26 UTC
Clear Linux fresh installed on laptop with Intel i3-7100

I have installed `intel-compute-runtime` with `computer-vision-basic`  bundle.

Can't run clinfo
`$ clinfo`
`>> Abort was called at 99 line in file: /builddir/build/BUILD/compute-runtime-19.38.14237/runtime/built_ins/built_ins.cpp`
`Aborted (core dumped)`

`$ cat /usr/share/OpenCL/vendors/intel.icd`
`>> /usr/lib64/intel-opencl/libigdrcl.so`

**Comment by bryteise** [comment] 2019-10-12 16:21
@chivakker Would you be able to take a look at this?

**Comment by ahkok** [comment] 2019-10-13 05:46
Works for me - does this require Intel Graphics? Does @Airplaneless have Intel HD graphics in that system?

**Comment by Airplaneless** [comment] 2019-10-13 08:50
> Works for me - does this require Intel Graphics? Does @Airplaneless have Intel HD graphics in that system?

Yes, I have used [https://github.com/intel/compute-runtime/releases](url) to work with OpenCL on Intel HD Graphics on Ubuntu 18.04.

It seems this problem was already reported: [https://github.com/intel/compute-runtime/issues/161](url), but in my case the problem is in `libigc.so`

```
$ LD_DEBUG=libs clinfo
      ....
      3955:	calling init: /usr/lib64/../lib64/../lib64/libclangCodeGen.so.9
      3955:	
      3955:	
      3955:	calling init: /usr/lib64/../lib64/libclangFrontendTool.so.9
      3955:	
      3955:	
      3955:	calling init: /usr/lib64/libopencl-clang.so.9
      3955:	
      3955:	
      3955:	calling init: /usr/lib64/librt.so.1
      3955:	
      3955:	
      3955:	calling init: /usr/lib64/libigdfcl.so.1
      3955:	
      3955:	find library=libigc.so.1 [0]; searching
      3955:	 search cache=/var/cache/ldconfig/ld.so.cache
      3955:	  trying file=/usr/lib64/libigc.so.1
      3955:	
      3955:	
      3955:	calling init: /usr/lib64/libigc.so.1
      3955:	
Abort was called at 99 line in file:
/builddir/build/BUILD/compute-runtime-19.38.14237/runtime/built_ins/built_ins.cpp
Аварийный останов (стек памяти сброшен на диск)
```

**Comment by ahkok** [comment] 2019-10-13 19:45
`Аварийный останов` - I assume this is "segmentation fault" in russion? :)

**Comment by Airplaneless** [comment] 2019-10-14 17:49
I have managed to solve this issue by replacing `libigc.so` from DEB package from Intel compute-runtime repository:
```
$ wget https://github.com/intel/compute-runtime/releases/download/19.38.14237/intel-igc-core_1.0.11-2500_amd64.deb
$ ar x intel-igc-core_1.0.11-2500_amd64.deb 
$ tar -xvf data.tar.xz 
$ cd ./usr/local/lib
$ sudo cp -a libigc* /usr/lib64
```
But this is not the Clear Linux way)

**Comment by chivakker** [comment] 2019-10-14 18:17
I can reproduce on Clear Linux 31290, I'll take a look; recently an update to igc was produced with llvm-9.  Need to follow up on that

**Comment by gogazago** [comment] 2019-10-14 20:19
could be related with this one?
https://github.com/intel/compute-runtime/issues/217

**Comment by chivakker** [comment] 2019-10-22 21:02
clinfo problem got fixed in version 31360, compute-runtime had a broken dependency with gmmlib that was fixed successfully.

**Closed by chivakker** 2019-10-22 21:02 UTC
Labels: bug
