### ISSUE TITLE
Proper transition from `systemd-networkd` to `NetworkManager` needed

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#755] opened 2019-05-18 17:58 UTC
In #289, @busykai mentioned the transition from `systemd-networkd` to `NetworkManager`, more details are available in `man stateless`.

To finish the switching, the user needs to execute the following
```
sudo systemctl disable systemd-networkd
sudo systemctl stop systemd-networkd
sudo rm /etc/NetworkManager/conf.d/systemd-networkd-unmanaged.conf
sudo systemctl restart NetworkManager
```

Well, this is fine. But it turns out that I have to do this after every reboot, or many gnome components won't work properly, including `gnome-weather` not finding my location and `gnome-software` warning of no internet connection.

I'm wondering what is bringing the deleted `systemd-networkd` back?

**Comment by markc** [comment] 2019-05-19 00:26
I have not checked this to be sure but perhaps you need to add this as well...

    sudo systemctl enable NetworkManager

**Comment by lebensterben** [comment] 2019-05-19 00:56
>I have not checked this to be sure but perhaps you need to add this as well... ...

@markc This makes sense!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by busykai** [comment] 2019-05-19 01:26
@lebensterben could you please check the directory /var/lib/swupd/one-shot-updates and let me know if there’s anything in it (you’ll need sudo for that)? We were observing cases where the migration did not happen. According to what you describe, there should be an .out file, please post its contents here.

**Comment by lebensterben** [comment] 2019-05-19 02:04
@busykai 

`201904-reconfigure-network-manager.sh.done`
```
ls: cannot access '/etc/systemd/network/*.network': No such file or directory
Created symlink /etc/systemd/system/dbus-org.freedesktop.network1.service → /usr/lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service → /usr/lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket → /usr/lib/systemd/system/systemd-networkd.socket.
Created symlink /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /usr/lib/systemd/system/systemd-networkd-wait-online.service.
Executed /usr/lib/swupd/one-shot-updates/201904-reconfigure-network-manager.sh on Sat 18 May 2019 12:21:59 AM EDT
```

`ls: cannot access '/etc/systemd/network/*.network': No such file or directory` is due to that I've deleted it already.
And interestingly this hot-fix is applied today at 12 am, just before I started this issue.

**Comment by busykai** [comment] 2019-05-19 02:32
thank you, @lebensterben! I'd appreciate if you'd try to reboot and see if the problem persists. because it should not, according to this. we can ignore the `ls` error, it does not impact anything.

also, there's no need to explicitly enable `NetworkManager`. it's enabled via "vendor" configuration in `/usr/lib/systemd`. enabling it with `systemctl` will create similar files in `/etc/systemd`.

**Comment by busykai** [comment] 2019-05-19 04:33
@lebensterben, just some more information to make sure you understand the mechanism and can make your own judgements:

The network migration script is designed to preserve historic behavior: ethernet is managed by systemd-networkd and the rest is managed by NetworkManager. The script is not very friendly in a sense that it does not address the situations where the user configured the ethernet to be managed by NetworkManager. Every time it's run, your system will be retrofitted back to the historic behavior.

Now, the migration script attempts to run when an update happens (`swupd update` triggers it). It is not run on reboot. Once it has run successfully, a `.done` file is created. If `.done` file is present, it will not be run again.

In your specific situation, the `.done` file was created today. We do not know if it existed before. That means that if you follow the `man stateless` procedure once again (sigh), you should get to the state where `systemd-networkd` is disabled and `NetworkManager` manages all the interfaces.

If you could do that and observe the behavior going forward, it would be of great help!

**Comment by lebensterben** [comment] 2019-05-21 04:05
@busykai 

Thanks for your detailed explanations!

I can verify that `systemd-networkd` is disabled now and `NetworkMangager` works as expected.

> also, there's no need to explicitly enable NetworkManager. it's enabled via "vendor" configuration in /usr/lib/systemd. enabling it with systemctl will create similar files in /etc/systemd.

I do find a `dbus-org.freedesktop.NetworkManager.service` is created under `/etc/systmd/system`, and it has identical contents as the on under `/usr/lib/systemd/...` has, and I can safely remove it now.

**Comment by busykai** [comment] 2019-05-21 18:14
@lebensterben, enabling `NetworkManager` via `systemctl` will do no harm. it creates the files in `/etc/systemd/...` you mention which are the exact same configuration which exist in `/usr/lib/systemd/...` already. even if you run `systemctl disable NetworkManager`, it will still be enabled: disabling only removes files in `/etc`. systemd is confusing this way and some commands, such as `is-enabled` will produce misleading output.

anyway, can this issue you be closed, you think?

**Comment by lebensterben** [comment] 2019-05-25 06:23
@busykai 
Well, the same problem comes back again. For unknown reason `systemd-networkd` service is active. Let me know how I can help you to diagnose this issue.

**Comment by busykai** [comment] 2019-05-25 06:43
@lebensterben that's too bad. :( could you please check if the content of done file has changed? specifically the date line. i'm wondering if there's something that i'm not aware of that cleans `/var/lib/swupd` thus removing the state. i assume you didn't explicitly removed the contents of `/var`, correct?

**Comment by lebensterben** [comment] 2019-05-25 06:53
@busykai 
```
ls: cannot access '/etc/systemd/network/*.network': No such file or directory
Created symlink /etc/systemd/system/dbus-org.freedesktop.network1.service → /usr/lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service → /usr/lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket → /usr/lib/systemd/system/systemd-networkd.socket.
Created symlink /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /usr/lib/systemd/system/systemd-networkd-wait-online.service.
Executed /usr/lib/swupd/one-shot-updates/201904-reconfigure-network-manager.sh on Thu 23 May 2019 06:52:37 PM EDT
```

Notice that, in https://github.com/clearlinux/distribution/issues/755#issuecomment-493720640 the timestamp was **Sat 18 May 2019 12:21:59 AM EDT**, but now the timestamp becomes **Thu 23 May 2019 06:52:37 PM EDT**.

Also, via `stat`, I found this log file is created on **May 23 06:52pm**, but it was there on on May 18. Thus, this hot-fix is applied on my system for more than onetime, and for some reason, the log file was deleted.

**Comment by busykai** [comment] 2019-05-25 06:58
@lebensterben, thank you! apparently, there's an issue and i will get back to you as soon as i discover the root cause. if you could keep an eye on it to try and identify the moment the state directory is wiped, it'd be very helpful. do you have autoupdate on, by the way?

**Comment by lebensterben** [comment] 2019-05-25 07:02
@busykai , I have autoupdate enabled. Do I need to disable it for diagnostic purpose?

**Comment by busykai** [comment] 2019-05-25 07:18
@lebensterben, disabling it would require you to run update manually. it could potentially help the diagnostics, but i'm not sure if deletion happens as the result of running swupd. so please keep autoupdate setting to your liking...

**Comment by lebensterben** [comment] 2019-05-25 07:19
> @lebensterben, disabling it would require you to run update manually. it could potentially help the diagnostics, but i'm not sure if deletion happens as the result of running swupd. so please keep autoupdate setting to your liking...

I will disable it for now and update manually. In the meantime, I will keep an eye on the `systemd-networkd`.

**Comment by pceiley** [comment] 2019-05-26 08:52
I'm almost certain this occurs as part of a swupd update. When I get a chance I'll check my logs to the timestamps of the files.

**Comment by lebensterben** [comment] 2020-05-02 07:12
Unfortunately, after updating to `32990`, the problem re-appeared.
I fixed this manually following instructions in `Network interface management`
section in `man stateless`.

I'm reopening this issue.

**Comment by busykai** [comment] 2020-05-11 17:47
hey @lebensterben. thanks for the report. it did not happen on my system... at first glance, non of the previous troublemakers sneaked back in. could you take a look at the last time migration state was created?
```bash
sudo ls -l /var/lib/swupd/one-shot-updates
```
If it's new[ish] could you also look at when `/var/lib/swupd` was modified (and files within it).

I think it's about time we remove the migration script in the first place. We gave enough time to upgrade for everybody.

**Comment by lebensterben** [comment] 2020-05-11 19:47
@busykai 
It happened around 10 days ago and I've modified the permission for `/var/lib/swupd` because I was experimenting with something that needs to read the MoM file.

If no other user ever reported this, you can close this issue when you think it's appropriate.

**Comment by busykai** [comment] 2020-05-13 18:20
thanks, @lebensterben. i will close it as i have not seen other reports, suspecting corrupt local state, especially since you tweaked `/var/lib/swupd`.

**Closed by busykai** 2020-05-13 18:20 UTC
Labels: bug
