### ISSUE TITLE
Clear Linux on older Intel CPUs?

### ISSUE THREAD

**Issue by gshamov** [clearlinux/distribution#961] opened 2019-06-30 20:25 UTC
Hi All,

Is it possible to have a build of clearlinux that would work on Nehalem CPUs? These do have SSE4,2 but lack AES , nested KVM etc.

Grigory

**Comment by ahkok** [comment] 2019-07-01 21:56
Duplicate of #785

**Closed by ahkok** 2019-07-01 21:56 UTC
Labels: enhancement, new
