### ISSUE TITLE
Daisy chain doesn't seem to work on GTX1070

### ISSUE THREAD

**Issue by leopck** [clearlinux/distribution#372] opened 2019-01-21 16:53 UTC
**Describe the bug**
Daisy Chain multiple monitors doesn't seem to work with GTX1070 and Clear Linux. Other monitors are not showing any display.

**To Reproduce**
1. Get a daisy chain setup (multiple monitors + compatible GPU)
2. Boot up Clear Linux without plugging in the secondary monitor (due to bug #371)
3. Plug in DP or USB Type C with daisy chain monitors
4. Unable to get any display on second/third monitor

**Expected behavior**
GDM should detect the other 2 monitors from one cable (DP or USB Type C) and then perform daisy chain. All three monitor at this point will display GDM.

**Environment (please complete the following information):**
 - Clear Linux OS version: 27000 onwards

**Comment by ahkok** [comment] 2019-01-21 18:44
Likely upstream gdm bug.

**Comment by ahkok** [comment] 2019-01-21 18:49
Duplicate of #371

**Closed by ahkok** 2019-01-21 18:49 UTC
