### ISSUE TITLE
ClearLinux baremetal install failure

### ISSUE THREAD

**Issue by ganeshmaharaj** [clearlinux/distribution#452] opened 2019-02-14 22:08 UTC
**Describe the bug**
ClearLinux release 27790 installer image failed to install on a baremetal.

**To Reproduce**
1.  Download image from https://download.clearlinux.org/releases/27790/clear/clear-27790-installer.img.xz
2.  `dd` the image to an USB stick
3.  Install on a NUC.
4. 

**Expected behavior**
The installation will complete and will prompt to reboot the OS.

**Screenshots**
![image](https://user-images.githubusercontent.com/5544378/52820807-e72da500-3061-11e9-925e-23b82c51238f.png)

**Environment (please complete the following information):**
NA

**Additional context**

**Comment by mdhorn** [comment] 2019-02-14 23:16
@gabibeyer Can you please attach the /root/clr-installer.log and the /root/pre-install-clr-installer.yaml files?

**Comment by ganeshmaharaj** [comment] 2019-02-15 00:32
@mdhorn guessing youi are asking me that. Unfortunately i blew away the usb stick, threw in an older version `27750` and got the install complete. i doubt i can get those logs now.

**Comment by mdhorn** [comment] 2019-02-15 01:05
@ganeshmaharaj  Thanks, autocomplete pulled up the wrong name and I didn't notice.

Based on the error message, I would have guessed you were attempting to install onto a mmcblk device -- we have a known bug which is fixed in the master branch, but being built today -- hoping it should make a release tomorrow.

But without more log information or the pre-install configuration file, I'm only guessing.

We are planning on updating the "crash/panic" flow to present information about error reporting include saving the log and pre-install configuration file; also information on enabling advanced logging if the problem persists.

We will probably end up closing this Issue if you were able to install with an older release without problems.

**Comment by ganeshmaharaj** [comment] 2019-02-15 04:13
@mdhorn that's fair. Just thought you ought to know about it. If you think this will be addressed by that patch, feel free to close the bug.

**Comment by mdhorn** [comment] 2019-02-15 22:56
Appears to be a duplicate of https://github.com/clearlinux/clr-installer/issues/195
Fixed in clr-installer 1.1.5 release today in Clear Linux OS 27820

**Closed by mdhorn** 2019-02-15 22:56 UTC
Labels: bug
