### ISSUE TITLE
Power settings freeze

### ISSUE THREAD

**Issue by MattiaVerticchio** [clearlinux/distribution#558] opened 2019-03-20 10:00 UTC
**Describe the bug**
The power settings freeze (for ~20sec) when selected.
```Shell
# gnome-control-center 

(gnome-control-center:5167): libupower-glib-WARNING **: 09:52:05.665: Couldn't connect to proxy: Errore nel chiamare StartServiceByName per org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.UPower': timed out (service_start_timeout=25000ms)

(gnome-control-center:5167): libupower-glib-CRITICAL **: 09:52:05.700: up_client_get_devices2: assertion 'UP_IS_CLIENT (client)' failed

(gnome-control-center:5167): GLib-CRITICAL **: 09:52:05.700: g_ptr_array_set_free_func: assertion 'array' failed

(gnome-control-center:5167): GLib-GObject-WARNING **: 09:52:05.702: invalid (NULL) pointer instance

(gnome-control-center:5167): GLib-GObject-CRITICAL **: 09:52:05.702: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gnome-control-center:5167): GLib-GObject-WARNING **: 09:52:05.702: invalid (NULL) pointer instance

(gnome-control-center:5167): GLib-GObject-CRITICAL **: 09:52:05.702: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gnome-control-center:5167): libupower-glib-CRITICAL **: 09:52:05.702: up_client_get_devices2: assertion 'UP_IS_CLIENT (client)' failed

(gnome-control-center:5167): GLib-GObject-CRITICAL **: 09:52:30.706: g_object_get: assertion 'G_IS_OBJECT (object)' failed
```

**To Reproduce**
1. Open Settings app;
2. Select Power settings;

**Expected behavior**
Regular opening of the power settings.

**Environment:**
 - Clear Linux OS version:
```Shell
# cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28400
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
 - Bundles:
```Shell
# sudo swupd bundle-list
Password: 
NetworkManager
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
boot-encrypted
bootloader
bootloader-extras
c-basic
cheese
cloc
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
devpkg-base
devpkg-llvm
diffutils
docutils
dosfstools
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gdb
gedit
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-native
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
make
minicom
mutt
nasm
nautilus
network-basic
nfs-utils
notmuch
offlineimap
openblas
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
pmdk
polkit
powertop
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
samba
seahorse
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
user-basic
valgrind
vim
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
znc
zsh
zstd
```

**Comment by ahkok** [comment] 2019-03-20 15:35
Duplicate of #541

**Closed by ahkok** 2019-03-20 15:35 UTC
Labels: bug, duplicate
