### ISSUE TITLE
vsock support is broken on clearlinux due to upstream bug

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/distribution#399] opened 2019-02-07 00:28 UTC
**vsock support broken in clearlinux**
Kata containers uses vsock to support firecracker. However the upstream kernel changes broke vsock support. There is an upstream patch to fix this issue. Can we include this as part of all Clearlinux kernels till the fix makes it upstream

https://kernel.ubuntu.com/git/ubuntu/ubuntu-bionic.git/commit/?h=master-next&id=90865e0a59e9474da046e91ac14c2cc0c22acfc9

/cc @miguelinux @bryteise

**Comment by miguelinux** [comment] 2019-04-29 18:42
The patch is already in upstream at https://github.com/torvalds/linux/commit/7fbe078c37aba3088359c9256c1a1d0c3e39ee81 in v5.0

Is the issue still seen?
or Can we close the issue?

**Comment by hnanni** [comment] 2019-04-29 19:02
yep, it is still failing (maybe the problem is not fixed by [the patch)](https://kernel.ubuntu.com/git/ubuntu/ubuntu-bionic.git/commit/?h=master-next&id=90865e0a59e9474da046e91ac14c2cc0c22acfc9)
```
root@master ~ # modprobe vhost_vsock ;  echo $?                                                                                                                                               
modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy
1
root@master ~ # swupd info
Installed version: 29100
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
root@master ~ # uname -a
Linux master 5.0.9-328.kvm #2 SMP Sat Apr 20 13:11:51 UTC 2019 x86_64 GNU/Linux

dmesg:
[  245.041840] calling  vhost_vsock_init+0x0/0x1000 [vhost_vsock] @ 582
[  245.041843] initcall vhost_vsock_init+0x0/0x1000 [vhost_vsock] returned -16 after 0 usecs

```

**Comment by miguelinux** [comment] 2019-04-30 21:56
Pleas try with `linux-kvm-5.0.10-331`

**Comment by miguelinux** [comment] 2019-04-30 22:04
sorry my bad, please try with `linux-kvm-5.0.10-332`

**Comment by miguelinux** [comment] 2019-05-02 15:28
@hnanni Coud you check with the new kernel please.

**Comment by hnanni** [comment] 2019-05-02 16:07
Thanks @miguelinux  The module loads without issues

**Comment by miguelinux** [comment] 2019-05-02 18:32
Ok, clossing this and if a new issue is showed, let us known by opening a new one please.

**Closed by miguelinux** 2019-05-02 18:32 UTC
Labels: bug, high priority
