### ISSUE TITLE
Spotify cannot play a song.

### ISSUE THREAD

**Issue by HuiTheng124** [clearlinux/distribution#695] opened 2019-05-08 07:27 UTC
**Description**
Spotify can be opened, however, after a song has been selected, it cannot be played.

**To Reproduce**
1. Boot up Live Desktop image
2. Open "Show Applications" from the left tool bar.
3. Select "Spotify" and open.

**Current behavior**
Spotify
![spotify](https://user-images.githubusercontent.com/44960524/57357210-fde92100-71a4-11e9-9091-aaa7197e3737.png)

**Expected behavior**
Spotify able to play song with sound. 

**Environment:**
Clear Linux OS version: [cat /usr/lib/os-release]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29280
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

Bundles: [e.g. sudo swupd bundle-list]
NetworkManager
NetworkManager-extras
R-basic
acpica-unix2
alsa-utils
atom
baobab
bc
big-data-basic
binutils
bison
boot-encrypted
bootloader
bootloader-extras
c-basic
cheese
cloc
cloud-native-basic
clr-network-troubleshooter
containers-basic
containers-virt
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
devpkg-R
devpkg-base
devpkg-llvm
diffutils
docutils
dosfstools
dpdk
editors
elasticsearch
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gdb
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
iperf
iproute2
iptables
java-runtime
java11-basic
joe
kbd
kernel-install
kernel-native
kernel-native-dkms
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-dev
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
make
man-pages
minicom
mutt
nasm
nautilus
net-tools
network-basic
nfs-utils
notmuch
openblas
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
parted
patch
perl-basic
pmdk
polkit
powertop
procps-ng
pulseaudio
pygobject
python3-basic
qemu-guest-additions
qt-basic
qt-core
samba
seahorse
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
syslinux
telemetrics
thermal_daemon
thunderbird
tmux
totem
tzdata
uget
unzip
user-basic
valgrind
vim
virt-manager
virt-viewer
vlc
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
znc
zsh
zstd

**Additional Context:**
Can play video and audio with sound in Youtube and VLC media player.

**Comment by mrkz** [comment] 2019-05-08 16:40
@HuiTheng124  Are you behind a proxy?

If that's the case, Spotify will require special proxy setup to work correctly.

Besides, this appears to be a network issue from your side as I'm using (and I've been using) Spotify for a long time now on ClearLinux via Flatpak app.

Tried to reproduce your issue, without success (e.g: it works). Please try in another network. 

I'm closing this now as I'm unable to reproduce, should you still experience the same issue, please
create a new issue with the following command line output:
```
flatpak run com.spotify.Client --show-console
```

**Closed by mrkz** 2019-05-08 16:40 UTC
Labels: bug, new
