### ISSUE TITLE
Calling GNU Emacs with graphical frame support XEmacs is wrong

### ISSUE THREAD

**Issue by tealeg** [clearlinux/distribution#725] opened 2019-05-14 08:35 UTC
It seems that clear linux distinguishes between two version of GNU Emacs installed by the `emacs` bundle based on whether they are graphical or command line only.  This is fine, however the naming is bad - `xemacs` is the name of well known, incompatible fork of GNU Emacs, and using the command `xemacs` to make GNU Emacs run in graphical mode is deeply confusing.  No experienced GNU Emacs user would assume they have to run `xemacs` to make Emacs start in a graphical frame.  When GNU Emacs is compiled with graphical support it is possible to specify on the command line that you want it to run in the terminal instead in a graphical frame.    

This is especially weird with regard to `emacsclient` which can be used to connect to Emacs when it is running in daemon mode.  There's no `xemacsclient` so even if you know about `xemacs` you have to run `emacsclient` instead.  `emacsclient` actually *requires* you pass a command line options specifying if you want a graphic frame or a terminal - however for this to actually make any difference you have to have run the server process as `xemacs`. 

As the bundle is installing both versions of emacs I don't see any advantage in having the terminal-only version at all.  If there were separate `emacs-nox` and `emacs` bundles that would make more sense.

**Comment by mrkz** [comment] 2019-05-14 15:07
Hello @tealeg,  thanks for your first bug report! :tada: 

We could rename properly the bundle, however this requires a bit of work on our side (i.e: deprecating old bundle name, and later on removing it) so it may require a bit of time to get this done, however I agree that the name may be confusing for emacs users.

(CC @bryteise @gtkramer  this is a change that requires format bump, as well as https://github.com/clearlinux/distribution/issues/643)

**Comment by thiagomacieira** [comment] 2019-05-14 15:20
The problem is not the bundle, it's the binary. I thought that /usr/bin/xemacs *was* XEmacs, not GNU Emacs.

Anyway, we could implement a solution just like the one I implemented for dbus-launch: https://github.com/clearlinux-pkgs/dbus/blob/master/0002-Make-the-non-X11-dbus-launch-exec-the-X11-enabled-on.patch

**Comment by bryteise** [comment] 2019-05-14 15:23
While the bundle xemacs does pull in emacs, emacs without x support can be installed without the xemacs bundle. Having the non-x emacs launch the x enabled emacs if reasonable is a reasonable alternative. Cleaning up the bundle names is still something we would want to do though.

**Comment by thiagomacieira** [comment] 2019-05-14 17:53
We can deprecate `xemacs` and replace with `emacs-nox` and `emacs-x11` (or just `emacs` for the latter).

We can also provide actual XEmacs in the `xemacs` bundle. It's available in Fedora (https://src.fedoraproject.org/rpms/xemacs), openSUSE (https://build.opensuse.org/package/show/openSUSE:Factory/xemacs), Gentoo (https://packages.gentoo.org/packages/app-editors/xemacs), Debian (https://packages.debian.org/stretch/xemacs21), but apparently not Arch Linux.

**Comment by thiagomacieira** [comment] 2019-05-14 23:20
Proposed patch
```diff
--- a/src/emacs.c
+++ b/src/emacs.c
@@ -1384,6 +1384,12 @@ Using an Emacs configured with --with-x-toolkit=lucid does not have this problem
 
     skip_args = count_before;
   }
+
+  if (!noninteractive && !inhibit_window_system)
+  {
+    /* attempt to launch the X11-capable version, if it is present */
+    (void) execvp ("emacs-x11", argv);
+  }
 #endif
 
   /* argmatch must not be used after here,
```

**Comment by bryteise** [comment] 2019-05-15 04:01
That patch seems reasonable to me.

**Comment by tealeg** [comment] 2019-05-15 06:25
> Hello @tealeg, thanks for your first bug report! :tada:

An absolute pleasure - great to see the rapid responses.  If there's anything I can do to help do let me know.

**Comment by mrkz** [comment] 2019-06-05 15:28
@thiagomacieira As per https://github.com/clearlinux/clr-bundles/commit/0edfb385b4c56b2bbf697d971b2525fda466179e I guess we can close this now?

**Comment by thiagomacieira** [comment] 2019-06-06 21:10
Yes, thanks for the reminder.

**Closed by thiagomacieira** 2019-06-06 21:10 UTC
Labels: bug
