### ISSUE TITLE
Include GNOME Boxes

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#740] opened 2019-05-15 23:54 UTC
Please consider including GNOME Boxes.

**Comment by bryteise** [comment] 2019-05-16 18:11
Alrighty, I'll give it a spin.

**Comment by znmeb** [comment] 2019-05-22 01:35
It's in - but it segfaults :-(

```
$ sudo swupd info gnome-boxes
Installed version: 29540
$ gnome-boxes

(gnome-boxes:6658): Gtk-WARNING **: 18:34:44.525: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:6658): Gtk-WARNING **: 18:34:44.526: GtkListBox with a model will ignore sort and filter functions
Segmentation fault (core dumped)
```

**Comment by bryteise** [comment] 2019-05-22 01:37
Oh boy. Well guess that's what I'm doing tomorrow.

**Comment by bryteise** [comment] 2019-06-03 17:21
Hrm I see there was a potential fix introduced. Might be in tomorrow's release.

**Comment by RobertBuhren** [comment] 2019-06-21 21:37
It still segfaults. Maybe just remove it then?

**Comment by sta7chase7** [comment] 2019-07-08 22:52
Unfortunately I have the same issue. After checking into logs, it looks like the segfault is happening with the libosinfo-1.0.so dependency.

**Comment by fenrus75** [comment] 2019-07-13 17:34
fixed the segfault just now; should be in the monday release

**Comment by sta7chase7** [comment] 2019-07-13 17:48
Thank you very much for your work! I'm excited to give it a try on Monday :)

**Comment by sta7chase7** [comment] 2019-07-16 18:39
> fixed the segfault just now; should be in the monday release

I can confirm that the issue is now fixed for me (Clear Linux version 30390)! Thank you again :)

**Closed** 2020-01-22 17:58 UTC
Labels: package-request
