### ISSUE TITLE
/usr/local contents removed after updates

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#206] opened 2018-09-19 20:23 UTC
I've seen this happen now and then, after performing update manually and rebooting the machine.

Last update was from X to 25080. X is some release from the previous days (Sep 18 or Sep 17).

**Comment by phmccarty** [comment] 2018-09-19 20:31
@cmarcelo I've run into this issue, too, but I think it's related to reboot, not update. I have seen my /usr/local/bin content get wiped as well, but only after a reboot.

**Comment by ahkok** [comment] 2018-09-19 21:15
I tried several things, reboot, update, verify fix `--picky`, but the files under /usr/local that I have remain on the system.

**Comment by miguelinux** [comment] 2018-09-25 18:50
I don't have this issue.

what did you do before reboot?

**Comment by cmarcelo** [comment] 2018-10-08 20:49
I haven't done nothing special between the update and reboot (just closing emacs and mutt processes). The files in question are in /usr/local/bin/ (the directory bin itself it's also removed).

For the record: got it again when updating this Monday (I rebooted just after the update).

**Comment by cmarcelo** [comment] 2018-10-08 20:50
OK. At least for this last instance, I know what might have happened:

```
.d..	0000000000000000000000000000000000000000000000000000000000000000	25440	/usr/local/bin
.d..	0000000000000000000000000000000000000000000000000000000000000000	25440	/usr/local/bin/kata-collect-data.sh
.d..	0000000000000000000000000000000000000000000000000000000000000000	25440	/usr/local/bin/kata-runtime
```

Sometime in the past we mistakenly shipped extra stuff in /usr/local, and now we are deleting it.

**Comment by cmarcelo** [comment] 2018-10-08 20:50
```
$ swupd-inspector cat clear/25470 Manifest.full | grep /usr/local
D...	6c27df6efcd6fc401ff1bc67c970b83eef115f6473db4fb9d57e5de317eba96e	25440	/usr/local
.d..	0000000000000000000000000000000000000000000000000000000000000000	25440	/usr/local/bin
.d..	0000000000000000000000000000000000000000000000000000000000000000	25440	/usr/local/bin/kata-collect-data.sh
.d..	0000000000000000000000000000000000000000000000000000000000000000	25440	/usr/local/bin/kata-runtime
D...	6c27df6efcd6fc401ff1bc67c970b83eef115f6473db4fb9d57e5de317eba96e	25440	/usr/local/share
```

**Comment by ahkok** [comment] 2018-10-08 20:55
looks like 25080 and 25440 both had these files.

We should be able to reproduce this, then, and, of course, if this is actually the cause of other files being deleted, that needs to be fixed.

**Comment by ahkok** [comment] 2018-10-08 20:56
@clearlinux/swupd-team

**Comment by cmarcelo** [comment] 2018-10-08 20:58
These files are in containers-virt bundle, so it seems everytime that bundle gets update, we get the issue. That would explain why the issue only happens "now and then".

**Comment by ahkok** [comment] 2018-10-08 21:00
And not for me - I never had that bundle installed.

**Comment by fenrus75** [comment] 2018-10-08 21:22
we need to do to /usr/local to what we do with kernels... never do a "d"

**Comment by cmarcelo** [comment] 2018-10-08 21:43
Reproduction steps follow, 25440 will bring a new version of the deleted file.

```
# swupd-extract clear/25430 containers-virt
# mkdir output/usr/local/bin
# touch output/usr/local/bin/hello
# swupd update --statedir $PWD/swupd-state --path output -m 25440 --no-scripts --no-boot-update
# file output/usr/local/bin/hello
```

Both hello and the bin directory will be missing after the update. You can use the swupd client for the first step too, just fix the update call accordingly.

**Comment by phmccarty** [comment] 2018-10-08 23:51
@cmarcelo I think this is a mixer bug... The deleted file versions should not be updated as part of a minversion bump, ever. I will file a bug.

**Comment by phmccarty** [comment] 2018-10-09 00:01
Bug filed: https://github.com/clearlinux/mixer-tools/issues/455

**Comment by cmarcelo** [comment] 2018-10-09 01:54
@phmccarty thanks for filing that. The mixer issue you raise aggravates this issue. But I think it is possible the issue could've occurred at the first version the file was deleted (no minversions involved).

Regardless of that, Clear Linux currently has a content bug: we shouldn't be shipping anything to /usr/local, and not marking anything as deleted.

**Comment by phmccarty** [comment] 2018-10-09 01:59
@cmarcelo Yes, it would have happened for the first version at which the file was deleted, too. You're right.

**Comment by phmccarty** [comment] 2019-04-16 19:52
The mixer considerations for `/usr/local` are currently tracked at https://github.com/clearlinux/mixer-tools/issues/548. Please follow up on that issue if there are any missing details.

I am tracking this issue as a bug in the `common` developer tooling, as it should check generated RPMs for blacklisted paths, and exit with an error in this case. The location of the blacklist should also be made configurable.

**Comment by phmccarty** [comment] 2019-04-16 19:58
I decided to open a new feature request for clearlinux/common instead. See https://github.com/clearlinux/common/issues/11

Closing

**Closed by phmccarty** 2019-04-16 19:58 UTC
Labels: bug, medium priority
