### ISSUE TITLE
libncurses looks like has an issue

### ISSUE THREAD

**Issue by shaoyuta** [clearlinux/distribution#1130] opened 2019-08-15 01:12 UTC
1, clearlinux version is 30690

2, A simple code to test libncurses

[main.c]
```
#include <ncurses.h>
#include <string.h>

#define MYPAD_X 100
#define MYPAD_Y 100

static void show_all(WINDOW *my_pad)
{
    (void) wattrset(my_pad, (A_BOLD));
    clear();
    wprintw(my_pad,"hello world\n");
    wnoutrefresh(stdscr);
    pnoutrefresh(my_pad, 0, 0, 0,  0, LINES - 1, COLS - 1);
    doupdate();
}
int main()
{	
    int i;
    WINDOW *my_pad;
    initscr();			
    keypad(stdscr, TRUE);		
    my_pad=newpad(MYPAD_X,MYPAD_Y);
    show_all(my_pad);
    getch();
    endwin();			
    return 0;
}
```
```
Build this file
$ gcc main.c -o test_app1 -lncurses
$ gcc main.c -o test_app2 -lncurses -D_GNU_SOURCE
```
a) Execute test_app1 and test_app2, found test_app1 is OK and test_app2 will panic due to 'Segmentation fault'

b) Same operation in Centos7, they are all OK

3, https://github.com/clearlinux/distribution/issues/1083 is same issue.

**Comment by phmccarty** [comment] 2019-08-15 03:32
@shaoyuta Are you working on a fix for this issue?

**Comment by shaoyuta** [comment] 2019-08-15 04:05
@phmccarty yes, I'm trying to fix it.

**Comment by bryteise** [comment] 2019-09-16 23:27
@shaoyuta The issue is caused by linking against `-lncurses` and not `-lncursesw`. The GNU_SOURCE flag will cause the wide character code to be run and so it needs to use the wide version of the library.

**Closed by bryteise** 2019-09-16 23:27 UTC
Labels: bug
