### ISSUE TITLE
Group ownership issue with stateless cups config files

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#650] opened 2019-04-30 00:35 UTC
**Describe the bug**
Whenever `cupsd.service` is started on my system, `swupd verify` reports hash mismatches for 4 cups config files:
```
/usr/share/defaults/etc/cups/cups-files.conf
/usr/share/defaults/etc/cups/cups-files.conf.default
/usr/share/defaults/etc/cups/cupsd.conf
/usr/share/defaults/etc/cups/cupsd.conf.default
```
Here is the long listing:
```
$ ls -l /usr/share/defaults/etc/cups/ | grep cups
-rw-r----- 2 root nobody 6273 Dec  7 12:51 cupsd.conf                             
-rw-r----- 2 root nobody 6273 Dec  7 12:51 cupsd.conf.default
-rw-r----- 2 root nobody 2878 Dec  7 12:51 cups-files.conf
-rw-r----- 2 root nobody 2878 Dec  7 12:51 cups-files.conf.default
```
After running `swupd verify --fix`, here is the same listing:
```
$ ls -l /usr/share/defaults/etc/cups/ | grep cups
-rw-r----- 2 root root 6273 Dec  7 12:51 cupsd.conf
-rw-r----- 2 root root 6273 Dec  7 12:51 cupsd.conf.default
-rw-r----- 2 root root 2878 Dec  7 12:51 cups-files.conf
-rw-r----- 2 root root 2878 Dec  7 12:51 cups-files.conf.default
```
It appears that the packaging of these config files does not match what `cupsd` expects at runtime. I confirmed that the file contents did not change, so the hash mismatches are detected only due to the group ownership changes. 

**Steps to reproduce**
1. `sudo swupd verify --fix`
2. `sudo systemctl start cupsd.service`
3. `sudo swupd verify`

**Environment (please complete the following information):**
 - Clear Linux OS version: 29100

**Comment by sunnyflunk** [comment] 2019-04-30 00:56
While the cups build sets a system group for printing, it doesn't set the non-privileged user/group for cups.

` --with-cups-user= --with-cups-group=`

Without it set it may try for common names of groups like `lp` but eventually ends up as `nobody` https://github.com/apple/cups/blob/master/configure#L9531 as shown in `/usr/share/defaults/etc/cups/cups-files.conf` That's likely changing the permissions to the group it's meant to be used for so that the group has access (which is nobody in this case).

**Comment by sunnyflunk** [comment] 2019-04-30 02:32
To confirm, it does indeed change the permissions to whatever group the configuration is set to (it didn't work when setting it as my username though, but `test` is a valid, non-logged in user). 

```
$ sudo cat /usr/share/defaults/etc/cups/cups-files.conf | grep -E "User|Group" | head -n2
#User nobody
#Group nobody
```

Changing the user and group:

```
$ sudo cat /usr/share/defaults/etc/cups/cups-files.conf | grep -E "User|Group" | head -n2
User test
Group cdrom
```

Results in a different group set after starting `cupsd.service`

```
$ sudo ls -l /usr/share/defaults/etc/cups/ | grep cups
-rw-r----- 3 root cdrom 6273 Dec  8 07:51 cupsd.conf
-rw-r----- 3 root cdrom 6273 Dec  8 07:51 cupsd.conf.default
-rw-r----- 3 root cdrom 2873 Apr 30 11:53 cups-files.conf
-rw-r----- 3 root cdrom 2873 Apr 30 11:53 cups-files.conf.default
```

**Comment by ahkok** [comment] 2019-04-30 16:22
Looks like there's a bad interaction between an upstream bug (it should never chgrp these files) and some half-done stateless integration.

**Comment by ahkok** [comment] 2019-04-30 16:24
confirmed

**Comment by ahkok** [comment] 2019-04-30 19:56
Fix merged.

- /usr/share configs will be untouched by cups
- default configs will be globally readable (since they're not secret anyway)

**Closed by ahkok** 2019-04-30 19:56 UTC
Labels: bug
