### ISSUE TITLE
Realtek RTL8812AU not recognized

### ISSUE THREAD

**Issue by fixerivan** [clearlinux/distribution#1206] opened 2019-09-09 23:02 UTC
Hi, 

my usb wifi adapter 

(lsusb output): 

Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter

was not recognized, swupd bundle-add hardware-wifi didn't help 

please advise 

Thanks

**Comment by puneetse** [comment] 2019-09-09 23:38
These drivers for that USB wifi adapter are not upstream part of the Linux kernel.
See this previous issue with advice on manually installing it: https://github.com/clearlinux/distribution/issues/869

**Comment by ahkok** [comment] 2019-09-10 15:40
duplicate of #869

**Closed by ahkok** 2019-09-10 15:40 UTC
Labels: bug, new
