### ISSUE TITLE
Clear linux - install postgres11

### ISSUE THREAD

**Issue by V-H-R-Oliveira** [clearlinux/distribution#1338] opened 2019-10-11 01:36 UTC
Good Night everyone.

I'm new to the system, and i cannot install postgresql11 ou postgresql bundle

I have installed the bundle with swupd, but when i do:

 psql, it returns this message below
psql: could not connect to server: Arquivo ou diretório inexistente
	Is the server running locally and accepting
	connections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?

If anyone have the same problem and have already solved, please i would like to solve it too.

**Comment by ahkok** [comment] 2019-10-11 03:15
@bwarden was working on a fix for this, which should be available soon. I'll let him check on that and respond.

**Comment by ahkok** [comment] 2019-10-11 03:17
Looks like a duplicate of #1335 

Are you sure you didn't forget to start the server once?

**Comment by V-H-R-Oliveira** [comment] 2019-10-11 14:59
I have already started the server:

$ systemctl status postgresql11.service 
● postgresql11.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql11.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-10-11 11:48:05 -03; 9min ago
     Docs: man:postgres(1)
 Main PID: 3999 (postgres)
    Tasks: 7
   Memory: 20.6M
   CGroup: /system.slice/postgresql11.service
           ├─3999 /usr/libexec/postgresql11/postgres -D /var/lib/pgsql11/data
           ├─4001 postgres: checkpointer
           ├─4002 postgres: background writer
           ├─4003 postgres: walwriter
           ├─4004 postgres: autovacuum launcher
           ├─4005 postgres: stats collector
           └─4006 postgres: logical replication launcher

Oct 11 11:48:04 clr-a553646a65d34b0ca6790a685bb3f3db systemd[1]: Starting PostgreSQL database server...
Oct 11 11:48:04 clr-a553646a65d34b0ca6790a685bb3f3db postgres[3999]: 2019-10-11 11:48:04.547 -03 [3999] LOG:  listening on IPv4 address "127.0.0.1", port 5432
Oct 11 11:48:04 clr-a553646a65d34b0ca6790a685bb3f3db postgres[3999]: 2019-10-11 11:48:04.604 -03 [3999] LOG:  listening on Unix socket "/run/postgresql11/.s.PGSQL.5432"
Oct 11 11:48:04 clr-a553646a65d34b0ca6790a685bb3f3db postgres[3999]: 2019-10-11 11:48:04.841 -03 [4000] LOG:  database system was shut down at 2019-10-10 22:12:41 -03
Oct 11 11:48:04 clr-a553646a65d34b0ca6790a685bb3f3db postgres[3999]: 2019-10-11 11:48:04.939 -03 [3999] LOG:  database system is ready to accept connections
Oct 11 11:48:05 clr-a553646a65d34b0ca6790a685bb3f3db systemd[1]: Started PostgreSQL database server.

But it doesn't work. But thanks for the answer.

**Comment by bwarden** [comment] 2019-10-11 16:03
This is a distinct issue. Looks like the psql app is version 9, and just isn't connecting to the postgreql11 instance.

**Comment by bwarden** [comment] 2019-10-11 16:13
Root cause: postgresql11 is placing its socket file in /run/postgresql11/ instead of /run/postgresql/

This patch was adapted from the main postgresql package:
https://github.com/clearlinux-pkgs/postgresql11/blob/master/0001-Move-socket-to-run-postgresql.patch

It should point to /run/postgresql as with the original patch, and additionally, we should probably define a different PGPORT for postgresql11.

**Comment by bwarden** [comment] 2019-10-11 16:15
Workaround is to use:
`psql -h /run/postgresql11`

**Comment by V-H-R-Oliveira** [comment] 2019-10-11 16:51
thanks, but also, another issue (maybe not), is in pg_hba.conf.
it has the "Method" set up to "reject" by default, but when i used postgres in ubuntu, the default method was "ident", is it a bug or not?

**Comment by bwarden** [comment] 2019-10-11 17:00
Not a bug. You're expected to create a pg_hba.conf (see https://www.postgresql.org/docs/10/auth-pg-hba-conf.html) according to your specific needs. "ident" is particularly archaic and insecure, and 

> When specified for local connections, peer authentication will be used instead.

so "peer" is probably what you really want anyway.

**Comment by bryteise** [comment] 2019-10-11 19:20
I think the intent is to have each postgres socket location versioned so multiple instances can be run at once. How to handle psql is an open though. Maybe consider adding psql versioned wrappers I guess but I think stateless documentation probably makes sense too.

**Comment by V-H-R-Oliveira** [comment] 2019-10-11 19:40
The solution provided worked for me, thanks for the quick support, also, in future if you could add some bundle which contains proxychains or torsocks, and otr for irssi, it would be great. Thanks again.

**Comment by ahkok** [comment] 2019-10-15 17:41
Please open separate requests for things unrelated to this topic. This item will be closed since there was a solution.

**Closed by ahkok** 2019-10-15 17:41 UTC
Labels: bug, new
