### ISSUE TITLE
Kernel version 5.3.8-867.native don't boot

### ISSUE THREAD

**Issue by PieroSimonet** [clearlinux/distribution#1487] opened 2019-11-13 19:57 UTC
Hi after updating the kernel to 5.3.8-867 ( I have the same problem with 5.3.8-859)  my pc refuse to boot.

When I reverted the default in the loader config file back to load the previous kernel (5.3.8.854.native) the system booted fine again.
 
I have a ideapad 330s-arr with an rayzen 5 2500U processor. I hope that's non a problem.

**Comment by JSEHV** [comment] 2019-11-13 20:41
Any message when your boot stalled? Or just a blank screen?

**Comment by ahkok** [comment] 2019-11-13 21:31
Looks like a duplicate of #1486

**Closed by ahkok** 2019-11-13 21:31 UTC
Labels: bug, new

**Comment by sriiora** [comment] 2019-11-14 23:24
Warm reboot will fail, example if you use 'reboot' in terminal to reboot the system. But if you shutdown the system totally and cold boot the system up, it will boot successfully. I tested on both clear-linux-native-5.3.11-868 and clear-linux-native-5.3.10-687

**Comment by PieroSimonet** [comment] 2019-11-16 10:26
It's  just a blank screen
And the "cold boot" doesn't work at all

> Any message when your boot stalled? Or just a blank screen?
