### ISSUE TITLE
kernel-lts -> linux-lts2019

### ISSUE THREAD

**Issue by Tornado-Tim** [clearlinux/distribution#1857] opened 2020-03-26 08:10 UTC
Hi team,

Could a linux-lts2019-dev bundle be made or migrate linux-lts from the 2018 kernel to the 2019 kernel?

The 2018 LTS kernel is too old for my machine as it doesnt support my AMD GPU and I need to make and load dkms modules which does not work on the native kernel.

**Comment by ahkok** [comment] 2020-03-26 17:33
Given the time frame (we're in march), we're at the point where we need to obsolete the 2017 lts kernel and bring in the 2019 lts kernel. That then would solve your issue here.

**Comment by mdhorn** [comment] 2020-03-26 17:37
@miguelinux @ahkok The installer still offers the 2017 kernel, so please keep me in the loop if it is depreciated.

**Comment by bryteise** [comment] 2020-03-26 17:52
@miguelinux We should consider only carrying a single lts kernel too.

**Comment by mdhorn** [comment] 2020-03-26 18:00
> @miguelinux We should consider only carrying a single lts kernel too.

How "long" are we considering is "long term support"?
I'd think we'd need at least the previous two years?

**Comment by bryteise** [comment] 2020-03-26 18:11
Well it isn't our long term support, just the kernel.org name (we'd just keep the newest "longterm" kernel in that case).

**Comment by fenrus75** [comment] 2020-03-26 19:00
likely the installer should only offer (in gui) the latest lts


we offer the older ones as long as they are maintained, but we wouldn't
want new installs accidentally picking a kernel that's going away too
quickly
(and users can always post install switch)

**Comment by mdhorn** [comment] 2020-03-26 19:35
> likely the installer should only offer (in gui) the latest lts we offer the older ones as long as they are maintained, but we wouldn't want new installs accidentally picking a kernel that's going away too quickly (and users can always post install switch)

The installer currently allows for selecting from the native kernel or any of the LTS options, but we could change that to just `kernel-native` and `kernel-lts` options.

**Comment by ahkok** [comment] 2020-03-26 20:09
> we could change that to just kernel-native and kernel-lts options.

I would +1 that.

**Comment by bwarden** [comment] 2020-03-26 20:15
The kernel-lts bundle just includes the kernel-lts2018 bundle. We already have a kernel-lts2019 bundle, so we should just change the include, right?

**Comment by mdhorn** [comment] 2020-03-26 21:08
> The kernel-lts bundle just includes the kernel-lts2018 bundle. We already have a kernel-lts2019 bundle, so we should just change the include, right?

@miguelinux Was waiting on something before changing that definition -- not sure if it was just communications, or testing, or ???

**Comment by mdhorn** [comment] 2020-03-26 21:47
> > we could change that to just kernel-native and kernel-lts options.
> 
> I would +1 that.

Installer change in the works
https://github.com/clearlinux/clr-installer/pull/693

**Comment by KyleSanderson** [comment] 2020-03-30 19:15
@mdhorn NAK. Not sure what you guys are thinking... There were massive fuse bugs in LTS that were only just fixed in the last 2 weeks but still broken for months. https://github.com/trapexit/mergerfs/issues/686

Please resolve this terrible regression immediately, I purposely installed lts2018 for this reason.

**Comment by ahkok** [comment] 2020-03-30 19:28
@KyleSanderson 

If there is a kernel patch we can merge on top of the 2019-lts, then we can (e.g. because it's in `fuse-next` already) just potentially do that. 

Also: You cannot "force" us to maintain a kernel beyond their life span. We will remove it. That was always the plan. Better work on a fix for the future now.

**Comment by bryteise** [comment] 2020-03-30 19:40
@KyleSanderson we do want to ensure a good kernel version is being picked for the default. That said the 5.4 series has been around for about 4 months and so moving over default versions doesn't seem obviously problematic. While we would like to support kernels for as as long as they are supported upstream there is a cost to doing so. We aren't removing 4.19 immediately but stopping providing it as a target for the installer is the start of getting removed. I think do owe the community a timeline for the removal from the distro though.

**Comment by miguelinux** [comment] 2020-04-02 07:29
The change is already done

**Comment by jonahbron** [comment] 2020-04-04 10:10
I'm glad this update was done. However, the dkms bundle has not been updated. There needs to be a kernel-lts2019-dkms bundle added, and the kernel-lts-dkms bundle needs to point to it. 

Not having that has broken my ability to install the Nvidia driver.

**Comment by jonahbron** [comment] 2020-04-05 18:37
Since there are other people upvoting my comment, it seems worth it to describe how I've worked around this. 

tl;dr the native kernel works fine, switch to it for now.

First run `sudo swupd bundle-install kernel-native`

Then run `sudo clr-boot-manager list-kernels`

Find the full name of the native kernel in that list. Use it to run `sudo clr-boot-manager set-kernel {name of kernel here}`

Reboot and go through the normal installation steps.

**Comment by bryteise** [comment] 2020-04-06 17:26
A new kernel-lts2019-dkms bundle (and corresponding changes to kernel-lts-dkms) should be in the next day or so.

**Closed by bryteise** 2020-04-06 17:26 UTC
Labels: package-update

**Comment by jonahbron** [comment] 2020-04-10 02:12
Confirmed that kernel-lts2019-dkms has been added.  If you (like me) switched to native for NVidia drivers, I recommend doing the following:

```bash
sudo swupd update
sudo swupd bundle-add kernel-lts kernel-lts-dkms
sudo clr-boot-manager set-kernel $(sudo clr-boot-manager list-kernels | grep lts2019 | tr -d ' ')
reboot
# Manually install NVidia drivers if desired
sudo swupd bundle-remove kernel-lts2018 kernel-lts2018-dkms
```
