### ISSUE TITLE
Desktop fails to boot all the way into the gnome desktop

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#35] opened 2018-03-30 17:23 UTC
I updated my dell xps 13 this morning and after rebooting my system boots into the console log-in and is unresponsive.   I tried booting my own customer kernel and see the same issue so assuming this wasn't caused by the kernel update.

I then booted off a usb key and edited my kernel's command line args to turn off i915 modesetting and i915 fastboot.  This enables me to actually log into the console and see that gdm is not running, but i haven't got any further in debugging

**Comment by cmarcelo** [comment] 2018-03-30 17:52
Another data point: I have the same machine and same issue. I get to boot to console by using ALT-F3 (or 4) and move to a different tty.

**Comment by rustylynch** [comment] 2018-03-30 17:53
[journal-issue-35.log](https://github.com/clearlinux/distribution/files/1864337/journal-issue-35.log)

**Comment by rustylynch** [comment] 2018-03-30 17:54
one suspicious new entry: 

systemd-udevd[254]: invalid key/value pair in file /usr/lib/udev/rules.d/61-gdm.rules on line 2, starting at character 175 ('[')

**Comment by cmarcelo** [comment] 2018-03-30 18:21
Removing the gdm rules doesn't help me here, so maybe unrelated.

As a workaround you can rollback (at your own risk) with: `swupd verify --fix -m 21530 --force`.

Also worth disabling auto updates until the issue is sorted: `swupd autoupdate --disable`.

**Comment by cmarcelo** [comment] 2018-03-30 18:22
(Forgot to mention: the rollback worked for me)

**Comment by seanvk** [comment] 2018-03-30 19:21
I've had this issue happen on releases at least twice, forcing me to make a rollback.

**Comment by cmarcelo** [comment] 2018-03-30 19:53
Arjan fixed the underlying issue (gnome-settings). Some upcoming release should have it.

**Comment by seanvk** [comment] 2018-03-30 20:19
Added a gdm test for desktop-autostart to catch this in the future.

**Comment by ahkok** [comment] 2018-03-30 20:20
Will post an update once i know which version includes the fix

**Comment by ahkok** [comment] 2018-03-30 20:25
gnome-settings-daemon 3.28.0-24 will be in 21580+

**Closed by ahkok** 2018-03-30 20:25 UTC
