### ISSUE TITLE
libtool build only shared library object and skip static library object

### ISSUE THREAD

**Issue by erezgeva** [clearlinux/distribution#2366] opened 2021-05-28 14:48 UTC
Basiclly the idea of the libtool, is that it builds both.
See example here:
https://www.gnu.org/software/libtool/manual/html_node/Creating-object-files.html#Creating-object-files

That is why the tool use the special folder ".libs", so it can builds both.

Running on Clear Linux

builder@d0178415e037~/libpmc $ libtool --mode=compile --tag=CXX  g++ -c -Wdate-time -Wall -std=c++11 -g -Og -MT bin.o -MMD -MP -MF bin.d -fdiagnostics-color=always bin.cpp -o bin.o

libtool: compile:  g++ -c -Wdate-time -Wall -std=c++11 -g -Og -MT bin.o -MMD -MP -MF bin.d -fdiagnostics-color=always bin.cpp  -fPIC -DPIC -o .libs/bin.o

Running on other Linux

debian@tsnlaptop:~/TSN/build/libpmc (master)$ libtool --mode=compile --tag=CXX  g++ -c -Wdate-time -Wall -std=c++11 -g -Og -MT bin.o -MMD -MP -MF bin.d -fdiagnostics-color=always bin.cpp -o bin.o

libtool: compile:  g++ -c -Wdate-time -Wall -std=c++11 -g -Og -MT bin.o -MMD -MP -MF bin.d -fdiagnostics-color=always bin.cpp  -fPIC -DPIC -o .libs/bin.o
libtool: compile:  g++ -c -Wdate-time -Wall -std=c++11 -g -Og -MT bin.o -MMD -MP -MF bin.d -fdiagnostics-color=always bin.cpp -o bin.o >/dev/null 2>&1

* If you wish Clear Linux version, leave a normal instruction, how to fetch it.

**Comment by phmccarty** [comment] 2021-06-02 21:38
@erezgeva Which other Linux distro (or distros) did you test where libtool didn't exhibit the bug?

**Comment by ahkok** [comment] 2021-06-03 17:56
We don't carry any meaningful patches to libtool that should affect this (one avx2 one, but that's irrelevant here).

Try unsetting CFLAGS and relevant environment options and seeing if this makes a difference. I've never seen the double compile line from debian. Is this also happening on e.g. fedora or suse or others?

**Comment by thiagomacieira** [comment] 2021-06-08 22:21
Check autoconf and automake. Clear Linux disables static libraries for all its packages, there may be something there.

**Comment by erezgeva** [comment] 2022-03-31 15:42
> We don't carry any meaningful patches to libtool that should affect this (one avx2 one, but that's irrelevant here).
> 
> Try unsetting CFLAGS and relevant environment options and seeing if this makes a difference. I've never seen the double compile line from debian. Is this also happening on e.g. fedora or suse or others?

I build on fedora and archlinux and both do 2 compilations.

**Comment by erezgeva** [comment] 2022-03-31 15:50
> Check autoconf and automake. Clear Linux disables static libraries for all its packages, there may be something there.

I do not use autoconf and automake.
Disabling static libraries for packages, should not apply to libtool.
The static libraries are used during build and not necessarily part of the packages.
Some times we build a shared library,
 and a tool that contain the same code, but we do not want to use the shared library with the tool,
 we simply link the tool with the static library during the package build.
Another technique, is to split a big code to few folders. Create a static library for each folder.
And than link all into a tool or few.

I principle, though, you do not want to have static libraries in the packages.
The libtool, should regardless compile both objects for static library (normal compilation) and shared 
objects.
Just remove the static libraries from the packages.

**Comment by phmccarty** [comment] 2022-03-31 19:07
After testing this issue, I see the expected behavior using `libtool` from Arch Linux, and the buggy behavior when running it on Clear Linux OS.

Passing the `--debug` flag to libtool produces shell trace output, and comparing the output from both distros hinted about the root cause. It was a problem with how libtool was being built... I will add more detail to the commit when I integrate the fix.

**Comment by phmccarty** [comment] 2022-04-06 23:54
Fixed in release [36130](https://cdn.download.clearlinux.org/releases/36130/clear/RELEASENOTES) ([commit](https://github.com/clearlinux-pkgs/libtool/commit/f1fc946c8017ad5d765e4876e276ff54926c3b22)).

**Closed by phmccarty** 2022-04-06 23:54 UTC
Labels: bug
