### ISSUE TITLE
QEMU/KVM stopped working after the last system update

### ISSUE THREAD

**Issue by mariojuniorjp** [clearlinux/distribution#784] opened 2019-05-22 20:10 UTC
Hi. When I try to boot a Windows 10 ISO, i get this error:

`Error starting an installation:constructor returned NULL` 

`Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/create.py", line 1999, in _finish_clicked
    self._start_install(self._guest)
  File "/usr/share/virt-manager/virtManager/create.py", line 2092, in _start_install
    progWin.run()
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 284, in run
    Gdk.Cursor.new_from_name(gdk_window.get_display(), "progress"))
TypeError: constructor returned NULL`

`Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details.py", line 372, in get_instance
    key = "%s+%s" % (vm.conn.get_uri(), vm.get_uuid())
AttributeError: 'NoneType' object has no attribute 'conn'`

Reinstalled kvm-host and kvm-extras but this problem persists.

**Comment by znmeb** [comment] 2019-05-22 21:07
I can confirm this - I thought it was a kvm kernel module problem but it is probably something else. Intel folks - are there changelogs we can look at if we want to try troubleshooting this ourselves?

**Comment by bryteise** [comment] 2019-05-22 21:23
Oo there might not be. @gtkramer @phmccarty thoughts on getting release notes published on the website. Would you prefer release notes on the mailing list? Since we try to release twice a day it seems like it might be just noise a lot of folks would rather avoid. Perhaps a separate mailing list though.

**Comment by mrkz** [comment] 2019-05-22 21:37
Hello, This is a duplicate of https://github.com/clearlinux/distribution/issues/782

As stated in a comment there, we'll have virt-manager downgraded while I get the new version to work out of the box.

> are there changelogs we can look at if we want to try troubleshooting this ourselves?

@znmeb Please consider opening a new issue with this request, so it's not lost once I close this report.

**Closed by mrkz** 2019-05-22 21:37 UTC
Labels: bug, duplicate, new

**Comment by mrkz** [comment] 2019-05-23 19:36
@znmeb @mariojuniorjp release **29590** (or later) should have virt-manager back to a working state.

thanks for your bug report :tada:

**Comment by mariojuniorjp** [comment] 2019-05-23 19:53
> @znmeb @mariojuniorjp release **29590** (or later) should have virt-manager back to a working state.
> 
> thanks for your bug report tada

You're welcome!
