### ISSUE TITLE
Add JWM please

### ISSUE THREAD

**Issue by davidpaulos** [clearlinux/distribution#1666] opened 2020-01-14 14:35 UTC
not much just wanted joes window manager so i don't have to use gnome or awesome thanks

it has very few dependencies and it is still pretty popular

i mean awesome and i3 are great but icewm jwm and openbox are still staples of the linux desktop

**Comment by ahkok** [comment] 2020-01-23 19:28
Dupe of #1647

**Closed by ahkok** 2020-01-23 19:28 UTC
Labels: package-request
