### ISSUE TITLE
Installing 'gitk' bundle doesn't draw required 'wish' dependency ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#385] opened 2019-01-24 23:40 UTC
When trying to run 'gitk', that is not yet installed, we are instructed to install a bundle that doesn't seem to draw the needed dependency 'wish'

1. First try to run (non-installed) gitk, we get the expected error : 
$ gitk
gitk: command not found
To install gitk use:  swupd bundle-add dev-utils
2.  Install required bundle :
$ sudo swupd bundle-add dev-utils
Downloading packs...
        ...12%
Extracting dev-utils pack for version 27410
        ...50%
Extracting bc pack for version 27210

Extracting cloc pack for version 27210

Extracting cpio pack for version 27210
        ...62%
Extracting docutils pack for version 27350
        ...75%
Extracting icdiff pack for version 27350
        ...87%
Extracting inotify-tools pack for version 27210
        ...100%

Extracting linux-tools pack for version 27380
Starting download of remaining update content. This may take a while...
        ...100%
Finishing download of update content...
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
3. Try to run gitk again :
$ gitk
/usr/bin/gitk: line 3: exec: wish: not found
nsauzede@clr-nsauzede-MOBL4 ~/intel/methodo/appsim/git/ptmf $ wish
wish: command not found
To install wish use:  swupd bundle-add tcl-basic

We could expect that the 'gitk' required 'wish' dependency would be automatically drawn, when installing the initial instructed bundle.

 - Clear Linux OS version: [`cat /usr/lib/os-release`]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27420
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
 - Bundles: [e.g. `sudo swupd bundle-list`]
acpica-unix2 alsa-utils bc bootloader c-basic cloc cloud-api cloud-control clr-installer containers-basic cpio cryptography curl darktable desktop desktop-apps desktop-assets desktop-autostart desktop-gnomelibs desktop-locales dev-utils diffutils docutils dosfstools editors emacs ethtool file findutils firefox fuse fwupdate gdb git go-basic gzip htop icdiff inotify-tools iproute2 irssi java-basic joe kbd kernel-install kernel-lts kernel-native kvm-host less libX11client libva-utils linux-tools llvm locales make meld nasm network-basic nfs-utils openssh-server openssl os-core os-core-update os-core-webproxy os-utils-gui p11-kit parallel patch perl-basic pmdk powertop python3-basic smartmontools storage-utils strace sudo sysadmin-basic telemetrics thunderbird tmux tzdata unzip valgrind vim weechat which wpa_supplicant x11-server xemacs xfce4-desktop xfsprogs xz znc zstd

Note : running CLR in VirtualBox, but should not matter with this issue

**Comment by ahkok** [comment] 2019-01-25 18:20
Duplicate of #377

**Closed by ahkok** 2019-01-25 18:20 UTC
Labels: bug
