### ISSUE TITLE
Missing dependency in tilix bundle

### ISSUE THREAD

**Issue by xaverh** [clearlinux/distribution#2199] opened 2020-11-17 14:03 UTC
The tilix bundle has a missing dependency:
```
object.Exception@generated/gtkd/gtkd/Loader.d(125): Library load failed (libvte-2.91.so.0): libvte-2.91.so.0: cannot open shared object file: No such file or directory
[1]    16468 illegal hardware instruction (core dumped)  tilix
```

**Comment by phmccarty** [comment] 2020-11-18 02:32
I'm not sure when `tilix` broke, but I added several runtime dependencies (specifically, `vte`, `gtk3`, and `librsvg`) to the package, since rpm does not add them manually in this case. I've confirmed that with these changes, `tilix` no longer crashes at startup.

I also updated `ldc` to the latest release and rebuilt `GtkD` and `tilix` with it.

Changes should be merged for the next release (33970 or newer).

**Comment by phmccarty** [comment] 2020-11-19 19:52
In release 33970, this issue appears to be fixed.

There is a warning at initial startup, but it does not appear fatal to tilix main operation: `Library libsecret-1.so.0 cannot be loaded, related functionality will not be available`. I just added `libsecret` as a runtime dependency to `tilix`, so that warning should disappear in 33980 or newer.

We also observed that the tilix suggests some fixes for vte configuration, linking to https://gnunn1.github.io/tilix-web/manual/vteconfig/. I'm not sure what the best configuration would be for Clear Linux, but perhap the `vte` package should install a `/usr/share/defaults/etc/profile.d/vte.sh` that would properly support tilix and still work with gnome-terminal, etc.

If you run into any more issues with tilix, please reopen, and or a new issue.

**Closed by phmccarty** 2020-11-19 19:52 UTC
Labels: bug

**Comment by phmccarty** [comment] 2020-11-19 20:21
After another look at the `vte.sh`, I think it should be installed by default. I just updated `vte` to install it under `/usr/share/defaults/etc/profile.d`, so that should fix the vte complaint from tilix. Fix available in 33980 or newer.
