### ISSUE TITLE
Get TLS error while trying to connect to various online accounts in gnome settings

### ISSUE THREAD

**Issue by curantes** [clearlinux/distribution#476] opened 2019-02-22 19:50 UTC
**Describe the bug**
When I try to to connect my google account to gnome-online-accounts i get below error. I have also tried some other account providers and some works and some does not. The ones that does not work get the same error.

- Google and Facebook does not work
- Microsoft and Foursquare works

```
Error writing data to TLS socket: The specified session has been invalidated for some reason.
```

**To Reproduce**
1.  Go to Gnome Settings
2.  Choose Online Accounts
3.  Try to add a Google or Facebook

**Expected behavior**
All available online accounts in the list in Gnome Settings -> Online Accounts should work.

**Screenshots**
This screenshot illustrates the issue.
![screenshot from 2019-02-22 20-45-27](https://user-images.githubusercontent.com/6643262/53267088-724e1100-36da-11e9-9db7-5bbe852bd927.png)

**Environment (please complete the following information):**
 - Clear Linux OS version: `27970`
 - Bundles: 
```
acpica-unix2
alsa-utils
baobab
binutils
bison
bootloader
c-basic
cheese
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
eog
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gedit
git
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gvim
gzip
htop
iproute2
kbd
kernel-install
kernel-native
less
libX11client
libglib
libstdcpp
libva-utils
llvm
make
nasm
nautilus
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
pygobject
python3-basic
seahorse
strace
sudo
sysadmin-basic
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
vim
which
wpa_supplicant
x11-server
xemacs
xz
zstd
```

**Comment by ahkok** [comment] 2019-02-23 03:34
smells like a possible certificate issue. Any relevant output in `journalctl` perhaps?

**Comment by curantes** [comment] 2019-02-23 21:31
> smells like a possible certificate issue. Any relevant output in `journalctl` perhaps?

I was also thinking of certificate issue, but there was no entry in `journalctl` that had anything to do with this.

**Comment by lebensterben** [comment] 2019-02-25 04:06
@ahkok I've the same error message, i.e. `Error writing data to TLS socket: The specified session has been invalidated for some reason.`, for Google and Facebook.

Furthermore, by executing `/usr/bin/gnome-control-center` from the shell, I got the following messages for:

Flick:
```
(gnome-control-center:21409): libsoup-WARNING **: 23:00:24.915: Could not set SSL credentials from '/var/cache/ca-certs/anchors': Error reading file “/var/cache/ca-certs/anchors”: Is a directory
```

Pocket:
```
** (gnome-control-center:21409): CRITICAL **: 23:01:41.972: void webkit_web_view_load_uri(WebKitWebView*, const gchar*): assertion 'uri' failed
```

**Comment by AthenasJimenez** [comment] 2019-04-01 13:01
@curantes are you still facing this issue? Can't reproduce on release (28560).

**Comment by curantes** [comment] 2019-04-01 19:12
@AthenasJimenez no, I don't have this issue anymore can't tell you from which version it started to work again. I think this issue can be closed if no other have this issue.

**Comment by AthenasJimenez** [comment] 2019-04-01 19:35
Great! closing it!

**Closed by AthenasJimenez** 2019-04-01 19:35 UTC
Labels: bug, high priority

**Comment by ironbone** [comment] 2019-05-14 21:32
Still the same issue.

**Comment by krashekspres** [comment] 2019-05-19 17:16
Online account's don't work on 29480.
