### ISSUE TITLE
Kernel doesn't boot after 5.3+

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#1272] opened 2019-09-25 19:11 UTC
I'm raising this here based off of a thread in the community where multiple folks are reporting that Clear Linux stopped booting somewhere between 5.2 kernel and 5.3

I'm not sure if there is a bug introduced by the Clear Linux changes or somewhere upstream.

https://community.clearlinux.org/t/bios-freezes-upon-boot-message-sha256-validated/1710

**Comment by nesiusra** [comment] 2019-09-25 20:35
@miguelinux - Do you have a Coffeelake NUC to test this on?

**Comment by dorileo** [comment] 2019-09-25 22:09
I managed to reproduce the issue, I replaced `kernel-native` by `kernel-lts` and the issue went away, managed to do the reverse to check if the issue was still there (just to make sure it's the kernel itself and not any post-install processing) - turns out the reversing brought back the issue, having said that I can assume the root cause is with the kernel-native bundle.

**Comment by 11h10** [comment] 2019-09-26 02:01
I have a NUC5CPYH (CELERON N3050): it boot very well with kernel 5.3.1-838.native

**Comment by puneetse** [comment] 2019-09-26 03:35
To keep in sync some discussions/progress in various places:
- The issue is being noticed particularly on Coffee Lake devices
- A symptom seems to be getting stuck at a message ""SHA256 validated".
- **Workaround:** Interrupt the bootloader by holding `SPACE` key as the system boots and select an older 5.2.x kernel to boot.
- A more permanent fix is still being discussed/implemented

**Comment by miguelinux** [comment] 2019-09-26 21:52
California found the root cause and Brett add the fix to kernel-config

**Comment by miguelinux** [comment] 2019-09-26 21:54
The  ""SHA256 validated", is only a successful message from systemd-boot. It was fixed to not show that message

**Comment by bwarden** [comment] 2019-09-26 22:36
Fix has been applied to all of our 5.3.x kernel packages and should make it into our next release. This issue will be updated automatically some time afterward.

**Closed** 2019-10-11 19:46 UTC
Labels: bug, high priority
