### ISSUE TITLE
No sound from HDMI audio on NUC board

### ISSUE THREAD

**Issue by jmrushing** [clearlinux/distribution#2396] opened 2021-07-01 00:19 UTC
I just installed Clear Linux on a new Gen 10 Intel Nuc. However I am unable to produce sound from the HDMI port.

According to the System > Sound GUI, sound is going to "Dummy Output" (even shows the sound meter bouncing when sound should be playing). Volume is all the way too, but no sound is produced. I can't imagine Dummy Output is right, seems like it should be something more specific.

According to `alsamixer`, Pulse is the default audio device and volume is all the way up. I can F6 and change to HDA Intel PCH, but that only gives me 2 S/PDIF devices, which this box doesn't even have. 

`speaker-test -twav` appears to cycle through speakers, but there is no sound there either.

Interestingly, this model is NUC10i3FNKN1 (a kit specifically without a 3.5mm audio jack). And I've tested with the base FNK model (has 3.5mm jack) and audio works on that, but not this one. I've done a ton of digging but most similar issues don't seem to match up to my specific case. For what it's worth, audio on this board doesn't seem to work with any Linux distro (Windows works though...go figure). 
I am a little surprised that a distro owned by Intel, designed specifically for Intel hardware, doesn't have working on-board audio on an Intel Nuc kit though. ;P

Here's some terminal output that might be useful based on my research:

`aplay -L`
```
null
    Discard all samples (playback) or generate zero samples (capture)
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
```

`lspci | grep "Audio"`
```
00:1f.3 Audio device: Intel Corporation Device 02c8
```

`cat /proc/asound/cards`
```
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0x6023110000 irq 150
```

`cat /proc/asound/devices`
```
  2: [ 0- 3]: digital audio playback
  3: [ 0- 7]: digital audio playback
  4: [ 0- 2]: hardware dependent
  5: [ 0]   : control
 33:        : timer
```

`dmesg | grep "audio"` (this actually seems promising)
```
[    2.126065] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops)
[    2.266222] calling  ledtrig_audio_init+0x0/0x1000 [ledtrig_audio] @ 263
[    2.266232] initcall ledtrig_audio_init+0x0/0x1000 [ledtrig_audio] returned 0 after 2 usecs
[ 1298.655562] snd_hda_codec_hdmi hdaudioC0D2: HDMI: pin NID 0x5 not registered
[ 1571.701134] snd_hda_codec_hdmi hdaudioC0D2: HDMI: pin NID 0x5 not registered
[ 2363.563248] snd_hda_codec_hdmi hdaudioC0D2: HDMI: pin NID 0x5 not registered

```

Let me know if I need to provide any additional information.

**Comment by ahkok** [comment] 2021-07-01 06:24
I've put some feelers out internally at Intel to see what we can come up with. Give me some time to find the right folks.

As a general rule, we can't really test on every Intel Platform. We do try to get NUC's but as you found, there are many skews that have subtle differences. Obviously we'll try and see if we can get one, but I may have to ask you to do some digging for me.

**Comment by jmrushing** [comment] 2021-07-01 07:45
> I've put some feelers out internally at Intel to see what we can come up with. Give me some time to find the right folks.
> 
> As a general rule, we can't really test on every Intel Platform. We do try to get NUC's but as you found, there are many skews that have subtle differences. Obviously we'll try and see if we can get one, but I may have to ask you to do some digging for me.

I appreciate the help! 

While I was waiting, I did some digging on my own with some promising results.

Funny enough, not long after I posted this. Audio started working for some reason. I happened to notice the kernel version changed, and realized that the auto-update system must've kicked in while I was away for a few hours.

Curious about this incident, I re-installed Clear Linux fresh with the same ISO. Back to no audio as expected. 
So I issued `swup update` let it update the bundles, kernel, etc. Now fully updated, the audio is STILL not working. Very strange, I'm not sure what could have caused the first accidental fix, as I'm fairly certain I only looked through basic info at that early point.

Whatever the case, I was back to square one. After re-reading [this kernel doc](https://www.kernel.org/doc/html/latest/sound/hd-audio/notes.html) I decided to install `alsa-tools` and run `hdajackretask`. This worked!

In the GUI, I had to check "show unconnected" from the top right side options. 
That's where it showed pins 0x05 , 0x06, and 0x07 as being "unconnected". 
I checked the box for "Override" next to 0x05. At this point, I realized that this might be what the dmesg error from earlier was referencing - `HDMI: pin NID 0x5 not registered`. 
After checking "Override", the GUI let me select the output device. There was only one option available "HDMI". 
I selected that and "Apply changes" and now audio works!

I tried to use the option in `hdajackretask` to "Apply Boot Override" (I think that's what it was called, maybe misremembering the exact wording). But it threw an error about not being able to write the .conf file because /etc/modprobe.d/ didn't exist (Where should modprobe .conf files live in Clear Linux?)

But I think the path to fix is much clearer at this point: there needs to be a firmware patch.fw in /lib/firmware and `options snd-hda-intel patch=patch.fw` in a modprobe .conf file. 
I think the patch might need to look something like this:
```
[codec]
0x8086280b 0x80860101 2

[pincfg]
0x05 0x18560070
0x06 0x58560020
0x07 0x58560030

```
...at least according to the hdajackretask output.

I'm still not sure what 0x06 and 0x07 would need to be for this to work with all outputs.

I'm going to check more deeply into the firmware patch & modprobe conf tomorrow after some much needed rest.

**Comment by kv2019i** [comment] 2021-07-01 18:13
@jmrushing hdajackretask should not be needed. This is pretty regular hw and should just work out-of-the-box. Can you provide output of "alsa-info"? (ref: https://www.alsa-project.org/wiki/AlsaInfo ). That might provide some clues what is happening.

**Comment by jmrushing** [comment] 2021-07-02 02:07
@kv2019i 
I re-installed Clear from the original clear-34700-live-desktop.iso

On first boot, before any updates, this is the result from alsa-info: https://pastebin.com/kvKnBVRk
At this point sound is not working (tested with `speaker-test -c6 -twav`)

After a full update (`sudo swupd update`) from 34700 to 34810 and a reboot, here's the newer alsa-info results: https://pastebin.com/HS1fPeEX 
Sound is still not working.

However, this procedure seems to fix it:
As root or sudo, create file `/lib/firmware/hda-intel-fix.fw` with content:
```
[codec]
0x8086280b 0x80860101 2

[pincfg]
0x05 0x18560070
0x06 0x18560070
0x07 0x18560070
```
Then, as root/sudo, create file `/lib/modprobe.d/hda-intel-fix.conf` with content:
```
options snd-hda-intel patch=hda-intel-fix.fw,hda-intel-fix.fw,hda-intel-fix.fw,hda-intel-fix.fw
```
(The filenames don't matter as long as they end in .fw and .conf, respectively, and the .conf file must reference the .fw filename on the patch= parameter)

After adding those files and rebooting, sound is working. 

I have no idea why the firmware patch file need be listed four times. The kernel doc on HD-Audio I referenced in my last comment seems to suggest that patchs need to be specified for each "card instance". Maybe that's relevant. Whatever the case, those patch options (with the file listed four times) is what `hdajackretask` spit out as valid module options, and it works so I'm not complaining. 
I'm not so sure about using the `0x18560070` bytecode value for all three pin configurations. I feel like maybe those should all be different. But I don't have Thunderbolt cables (or a Thunderbolt-capable monitor for that matter) to test with, and a colleague tested this exact configuration on another NUC (identical Model & SKU to mine) and said that Thunderbolt audio was working fine. So that's good enough for us at the moment.

Oh and in case you need it, here's another pastebin for the most recent alsa-info results post-update and post-firmware patch with working HDMI audio: https://pastebin.com/s8juxS6n

At this point, I'm assuming that this issue obviously isn't with Clear Linux proper, since we've also had this issue on other Linux distros and patched it with similar solutions. Any ideas where this should go? Maybe whoever maintains the HDA-Intel drivers? I'm unsure.

**Comment by kv2019i** [comment] 2021-07-02 07:19
Thanks @jmrushing for the extensive logs. It seems the problem is this line in alsa-info output:
"Pin Default 0x58560010: [**N/A**] Digital Out at Int HDMI"

.. the Linux hdmi codec driver will ignore this pin due to the "N/A" setting.

Could you try following kernel patch:

```
diff --git a/sound/pci/hda/patch_hdmi.c b/sound/pci/hda/patch_hdmi.c
index 4b2cc8cb55c4..71f6b5a41e7d 100644
--- a/sound/pci/hda/patch_hdmi.c
+++ b/sound/pci/hda/patch_hdmi.c
@@ -2953,6 +2953,7 @@ static int intel_hsw_common_init(struct hda_codec *codec, hda_nid_t vendor_nid,
        spec->port_map = port_map;
        spec->port_num = port_num;
        spec->intel_hsw_fixup = true;
+       spec->force_connect = true;
        spec->dev_num = dev_num;
 
        intel_haswell_enable_all_pins(codec, true);
```

**Comment by kv2019i** [comment] 2021-07-02 09:01
And https://github.com/thesofproject/linux/pull/3023 is potentially a more clean fix. I can send upstream if you can verify this works.

**Comment by jmrushing** [comment] 2021-07-02 21:04
@kv2019i Yes, I'll be happy to test. I'm running a little behind today due to work obligations, but I can test and get back to you within the next 12 hours or so. Thanks!

**Comment by jmrushing** [comment] 2021-07-09 23:37
@kv2019i Sorry for the delays. Your kernel patch worked on my NUC10 device and sound is now working.
Building a kernel from source was new territory for me, but I followed [this guide](https://docs.01.org/clearlinux/latest/guides/kernel/kernel-development.html#) without any issue.

**Comment by jmrushing** [comment] 2021-07-10 03:56
@kv2019i I just tested your fix for thesofproject/linux#3023 and that worked for me as well. Thanks!

**Comment by kv2019i** [comment] 2021-07-19 15:09
@jmrushing  Thank you! And sorry for the delay as well, I was out last week. I'll now proceed and send this patch upstream.

**Comment by kv2019i** [comment] 2021-07-20 15:46
Patch sent upstream and merged today: https://mailman.alsa-project.org/pipermail/alsa-devel/2021-July/187558.html

**Comment by ahkok** [comment] 2021-07-20 16:44
The patch also just got merged into our linux kernel as well. Thanks @miguelinux

**Closed by ahkok** 2021-07-20 16:44 UTC
Labels: bug

**Comment by Retro64** [comment] 2021-09-18 10:08
@jmrushing thanks - your fix helped me to gain back sound via HDMI on a HP Prodesk 400 G4 with stock Ubuntu. The problem came in with a BIOS update bundled with Intel firmware package

**Comment by barisoztop** [comment] 2022-04-27 15:03
@jmrushing one more thanks from me for suggesting `hdajackretask` to override ports. I was also on a HP ProDesk 400 G4 with Ubuntu (all was fine at windows) (even updated the kernel for this problem to 5.14.21-051421-generic but didn't help). Web was full of unrelated answers.
