### ISSUE TITLE
Cannot set Daylight Saving Time

### ISSUE THREAD

**Issue by haiqu** [clearlinux/distribution#2244] opened 2021-01-10 12:55 UTC
Clear Linux 2.7.1 (34000)

No checkbox to set DST. My clock is running one hour slow, yet is synchronized to the internet.

**Comment by lebensterben** [comment] 2021-01-10 16:29
this is a known bug in gnome. it has been reported already

**Comment by mdhorn** [comment] 2021-01-11 22:17
Closing as duplicate of https://github.com/clearlinux/distribution/issues/2168

**Closed by mdhorn** 2021-01-11 22:17 UTC
Labels: bug, duplicate
