### ISSUE TITLE
Firefox in Plasma Desktop - Issues

### ISSUE THREAD

**Issue by rbharathkumar** [clearlinux/distribution#498] opened 2019-03-01 16:42 UTC
Hi All,
As per suggestion in #414,  I am opening a new issue regarding the firefox issue I had faced with the requested information.

The following are some of the issues that I am facing with Firefox. I am currently up to date on all bundles. I have attached the bundle list for your reference.

1. Remove Firefox bundle and restart.
2. Install Firefox bundle.
3. Start Firefox from Konsole.
3.1. Warning Messages in Terminal.

```
(firefox:1186): Gtk-WARNING **: 21:44:41.283: Could not find the icon 'window-minimize-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
```
3.2. No Minimize Maximize button. This is not limited to Firefox. Even when I had installed the Chrome rpm, using the GTK style gives out this issue. The buttons are there, but not visible.

![buttons_not_visible](https://user-images.githubusercontent.com/38585383/53652050-f15cbf80-3c6d-11e9-881c-a822388c0b03.jpeg)

3.3. Whenever I try to save a file or image using the Right Click --> Save Link, firefox crashes. Any kind of interaction with the file system or even outside of the browser seems to make it crash. Since we had started firefox through the terminal, the following are the logs that were available.

```
(firefox:1186): GLib-GIO-ERROR **: 22:05:49.659: No GSettings schemas are installed on the system
ExceptionHandler::GenerateDump cloned child 1966
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Exiting due to channel error.
[Child 1271, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 349
Exiting due to channel error.
[Child 1336, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 349
Exiting due to channel error.
Trace/breakpoint trap (core dumped)

```
 - Clear Linux OS version: [`cat /usr/lib/os-release`]

```
cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28070
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```

 - Bundles: [e.g. `sudo swupd bundle-list`]
[20190301_Bundle_List.txt](https://github.com/clearlinux/distribution/files/2920266/20190301_Bundle_List.txt)
```
acpica-unix2            icdiff                  parallel
ark                     inotify-tools           patch
bc                      iproute2                perl-basic
binutils                iptables                pmdk
bison                   irssi                   polkit
bootloader              joe                     powertop
c-basic                 kate                    pygobject
ceph                    kbd                     python2-basic
cloc                    kde-frameworks5         python3-basic
cpio                    kdiff3                  qt-basic
curl                    kernel-install          samba
desktop-gnomelibs       kernel-lts              shells
desktop-kde             konsole                 smartmontools
desktop-kde-libs        ksysguard               spectacle
dev-utils               kvm-host                storage-utils
devpkg-base             less                    strace
devpkg-llvm             libX11client            sudo
diffutils               libglib                 sysadmin-basic
dnf                     libstdcpp               tmux
docutils                libxslt                 tzdata
dolphin                 linux-tools             unbundle
dosfstools              llvm                    unzip
editors                 mail-utils              user-basic
emacs                   make                    valgrind
ethtool                 mutt                    vim
file                    nasm                    weechat
findutils               network-basic           which
firefox                 nfs-utils               wpa_supplicant
flatpak                 offlineimap             x11-server
flex                    openblas                x11-tools
fonts-basic             openldap                xfsprogs
fuse                    openssh-server          xterm
gdb                     openssl                 xz
git                     os-core                 znc
glibc-locale            os-core-update          zsh
gpgme                   os-core-webproxy        zstd
gzip                    p11-kit
```

Please let me know for any further information.

**Comment by ahkok** [comment] 2019-03-01 19:42
Firefox seems unrelated - plasma desktop bundle should include `hicolor` icon theme I think?

@anselmolsm @thiagomacieira does it need explicit adding to the plasma bundle?

**Comment by thiagomacieira** [comment] 2019-03-01 20:04
Why is Gtk using the hicolor theme, instead of breeze? That is the problem, since breeze has it. And hicolor doesn't, so hicolor wouldn't help.

On the crash (3.3): that's a Firefox packaging bug. It needs to Requires: the package that provides those schemas.

**Comment by bryteise** [comment] 2019-03-01 22:57
@mrkz Are you aware what generates the schemas (it looks like it is done by glib-compile-schemas I assume by gnome at some point during bringing up the desktop but I don't know)? I can add the dependencies to firefox but if the cache isn't generated by something the crash won't go away.

**Comment by mrkz** [comment] 2019-03-01 23:22
@bryteise yes, our glib also provides systemd triggers to create the cache on firstboot and on update.

**Comment by bryteise** [comment] 2019-03-01 23:33
Thanks, firefox update pushed, should be in the next update.

**Comment by rbharathkumar** [comment] 2019-03-02 17:35
Hi all,
thank you for your response.

Today I had followed the same steps to install the 28090 version of firefox - the latest the swupd command returns. Unfortunately all the issues still persist.

And regarding the window options, can you please guide on how to fix it too ? Please find the current GTK Application style settings.

![image](https://user-images.githubusercontent.com/38585383/53685351-503e3980-3d3f-11e9-8840-37a862f3913e.png)


Also one more feature request.

When the firefox icon is right clicked, would be nice to have the option to enter into the Private Browsing Window option. Chrome seems to have it. Would be nice to have the option in the Application Menu as well as the panel.

**Comment by anselmolsm** [comment] 2019-03-08 21:16
Hey @rbharathkumar , I've been dealing with some other stuff lately, hopefully will be able to dive into this issue next week. Just a comment for now:

> When the firefox icon is right clicked, would be nice to have the option to enter into the Private Browsing Window option. Chrome seems to have it. Would be nice to have the option in the Application Menu as well as the panel.

That's a nice idea, I'd recommend you to send a feature request upstream at [Mozilla bugzilla](https://bugzilla.mozilla.org/)

**Comment by rbharathkumar** [comment] 2019-03-09 01:30
Hi @anselmolsm , that is ok...Please take your time...

Regarding the feature request, what I had meant is when you right click the firefox icon on the Application Menu or in the Plasma Panel, the context menu that appears has only the add to desktop or Add to Panel option. It would be useful if it had a "New Window" or "New Private Window" option. I think it has to do with the KDE settings ? I am not sure about... My apologies if it isn't.

Thank you.

**Comment by thiagomacieira** [comment] 2019-03-09 03:21
Plasma supports this and as you say Chrome has it. Sounds like Firefox's .desktop files are missing the actions.

Can someone verify that it show on GNOME?

**Comment by anselmolsm** [comment] 2019-03-09 03:56
Yep, Firefox's .desktop file does not contain the actions. Adding something like:
```
Actions=new-window;new-private-window;`

[Desktop Action new-private-window]
Name=New Private Window
Exec=/usr/bin/firefox --private-window
```
in the end of Firefox's .desktop file does what @rbharathkumar suggested.

**Comment by anselmolsm** [comment] 2019-03-09 21:13
@rbharathkumar considering your screenshot of "GTK Application style settings" I see you are not using the default theme for Qt/KDE widgets (Breeze) and it seems darker than Breeze Dark. Which theme is that? Probably not related, but just to make sure I'm reproducing the env completely. Thanks.

**Comment by rbharathkumar** [comment] 2019-03-10 05:57
> Yep, Firefox's .desktop file does not contain the actions. Adding something like:
> 
> ```
> Actions=new-window;new-private-window;`
> 
> [Desktop Action new-private-window]
> Name=New Private Window
> Exec=/usr/bin/firefox --private-window
> ```
> in the end of Firefox's .desktop file does what @rbharathkumar suggested.

Hi @anselmolsm , thank you for your response.
As per your suggestion, I tried adding the above mentioned lines of code to the firefox.desktop file.
Not sure if I did it correctly. I found the .desktop file in the /usr/share/applications path. Opened it up with nano and added the above lines to it. Logged out and logged back in.

Now I am able to see the "New Private Window" option alone when I right click on the icon in the panel.
New Window option is still missing. I guess adding another without the --private-window with a new Name would add that option.

Another point of note is that the options are still not visible in the application menu.
When I go to Application Menu -> Internet -> Firefox (Right Click) 
It still does not give out the options. Only the option to add to desktop or panel.

Would be really nice if these were packaged as part of the bundle itself. If possible that is...
I am not aware of the complexity and intricacies involved
If the behavior is something specific to Plasma, then it is ok...

**Comment by rbharathkumar** [comment] 2019-03-10 06:02
> @rbharathkumar considering your screenshot of "GTK Application style settings" I see you are not using the default theme for Qt/KDE widgets (Breeze) and it seems darker than Breeze Dark. Which theme is that? Probably not related, but just to make sure I'm reproducing the env completely. Thanks.

Hi @anselmolsm ,
The following are the various settings I have tried and currently in place.
**Workspace Theme:**
Look and Feel: Breeze Dark
Plasma Theme: Oxygen
Colors: Zion Reversed
Icons: Flat-Remix-Dark

Application Style:
Widget Style: Breeze
Window Decorations: Breeze
GTK Application Style: Screenshot above.

Not really sure what information you had requested.. I hope the above details are sufficient.

**Comment by anselmolsm** [comment] 2019-06-24 17:45
> Firefox seems unrelated - plasma desktop bundle should include `hicolor` icon theme I think?
> 
> @anselmolsm @thiagomacieira does it need explicit adding to the plasma bundle?

#681 , #818 were also about the icon issue, both fixed.

> Would be really nice if these were packaged as part of the bundle itself. If possible that is...
> I am not aware of the complexity and intricacies involved
> If the behavior is something specific to Plasma, then it is ok...

WRT the desktop file. No, it is not specific to Plasma, that's really about adding the activities to the .desktop file, which is used across desktop environments. Upstream provides a desktop file with such actions (with i18n data). This update is on its way and will get published soon.

I tried again to reproduce - without success - the missing minimize, maximize and close buttons. In fact those buttons are related to the window manager decoration, that is not something affected by the GTK/GNOME style configuration but by kwin's decoration. A fresh Clear Linux install + bundle desktop-kde and firefox did not trigger the issue (as of release 30000), if you can still reproduce this, please report again.

---

This issue contains so many things (some of them unrelated to each other) that makes it hard to track the work. I recommend filling separate issues in case of updates about each of the problems discussed here.

**Comment by rbharathkumar** [comment] 2019-06-25 13:04
ok let me try with a fresh install of clear linux + desktop-kde + firefox and let you know in case of any issues.

**Comment by rbharathkumar** [comment] 2019-06-25 15:57
Tried out a fresh install of Clear Linux with desktop-kde and firefox bundles.
Unfortunately the issue still persists.

With the title bar - On, the window controls are visible. When we remove the title bar via the Customize option in Firefox, the minimize, maximize and close buttons disappear. I mean they are there, but invisible.

**Comment by anselmolsm** [comment] 2019-06-25 17:37
> With the title bar - On, the window controls are visible. When we remove the title bar via the Customize option in Firefox, the minimize, maximize and close buttons disappear. I mean they are there, but invisible.

OK, so that step of the customization was not clear, thanks for adding that info. It works on my env, but I'll retest on the reference one to check if I manage to reproduce it.

Removing the title bar turns client side decorations on, so my previous comment about kwin window decoration are not applicable in this case as csd is handled by GTK, so it sounds like a problem with GNOME/GTK icons / themes.

**Comment by anselmolsm** [comment] 2019-06-26 00:21
Adwaita is the default icon theme for GTK, and it is not installed by desktop-kde bundle. At first, GTK applications fail to show icons, but that gets fixed upon changes in GNOME/GTK application style menu.

Adding adwaita to desktop-bundle-kde prevents "missing icons" effect (ando also allows users to actually use the GTK default icon theme). In terms of plasma integration, it would be nice to have a trigger to generate proper settings.ini set to Breeze themes.

**Comment by rbharathkumar** [comment] 2019-06-27 13:40
Thank you for working on this issue.
You are right, Adwaita is not installed by default.
I see only Breeze and Breeze-Dark installed.

So for an existing install, is this something that could be fixed via an update ?
I would also suggest including the hicolor and gnome as well since I have heard that some applications specifically look for these themes. Not sure though...

**Comment by anselmolsm** [comment] 2019-06-27 15:04
Fix for this was pushed yesterday, an existing install will get that via an update soon. 

hicolor is the default fallback theme when the current active one does not have an icon. Need to check about the gnome theme, isn't it adwaita too?

**Comment by rbharathkumar** [comment] 2019-06-27 15:13
Thanks for pushing out the fix.
I actually see gnome and adwaita as separate themes in some of the other distributions. Please ignore if not relevant.

But the point I was trying to make was that besides breeze and breeze-dark, the hicolor and adwaita can also be provided for a smooth "Clean Install" experience...

**Comment by anselmolsm** [comment] 2019-06-27 17:43
> I actually see gnome and adwaita as separate themes in some of the other distributions. Please ignore if not relevant.

You're correct, they are indeed separate themes.

> Does KDE itself provide a breeze-gtk theme ? I have seen its mention in a couple of other forum comments.

Yes, it does. That's what provides "Breeze" entries in "GNOME/GTK Application style" settings.

**Comment by rbharathkumar** [comment] 2019-07-02 11:54
After yesterday's update, I can confirm that Mozilla now sports Adwaita's window controls when the title bar has been removed. Works as expected. Thank you for the update.

**Comment by mrkz** [comment] 2019-07-02 21:44
Thanks for confirming the fix! :tada:  closing now

**Closed by mrkz** 2019-07-02 21:44 UTC
Labels: bug
