### ISSUE TITLE
clr-installer-gui not using system-wide proxy settings

### ISSUE THREAD

**Issue by dvarnai** [clearlinux/distribution#903] opened 2019-06-17 09:42 UTC
Hi,

I'm on a network where all outside network traffic is prohibited and I can only access the network via a HTTP(S) proxy. I set the proxy in the network configuration and I can confirm it was working properly in the browser and even got the proper environmental variables set in terminal after I restarted it. However, no matter what I did, running clr-installer-gui from the gnome launcher always failed with network connectivity issues. Launching it from terminal with the correct environmental variables set solved the issue. 

I'm using the latest live desktop iso (29930).

Best,
Daniel

**Comment by mrkz** [comment] 2019-06-17 14:12
This seems like a duplicate of https://github.com/clearlinux/clr-installer/issues/392

@dvarnai I suggest you to follow the previous link to the bug report and track the progress there.

Closing as duplicate now.

(CC @mdhorn )

**Closed by mrkz** 2019-06-17 14:12 UTC
Labels: bug, duplicate, new
