### ISSUE TITLE
Install surprisingly destroys partition

### ISSUE THREAD

**Issue by MRustad** [clearlinux/distribution#123] opened 2018-07-16 05:18 UTC
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

I installed onto a bare metal machine. I had a number of partitions and had intended to have Clear Linux format only the root filesystem. When it asked me for a /boot partition, I was kind of surprised, so I gave it my /extra partition to use for that purpose. I figured I would sort it out later. I did *not* allow it to format the partition, but apparently it did reformat it as an ext4 (which is what it had been) anyway.

It appears that it really wanted an EFI system partition, which I did have, but it was not clear to me that was what /boot was supposed to be.

So I see two problems here:
1) reformatting a partition with neither permission nor a warning
2) not being clear what /boot is intended to be

A subsequent install using my existing EFI System partition for "/boot" worked fine, but of course my /extra partition content was gone.

**Comment by bryteise** [comment] 2018-07-17 17:23
Could you add the steps you went through to install? Was this a manual setup of the disk?

**Comment by MRustad** [comment] 2018-07-18 05:32
On Jul 17, 2018, at 10:23 AM, William Douglas <notifications@github.com>  
wrote:

> Could you add the steps you went through to install? Was this a manual  
> setup of the disk?

Yes, it was a manual install, because I wanted to preserve a number of  
partitions. I had expected to format only / and swap. I was not expecting  
the /boot it requested to be formatted.

Fortunately it wasn't a disaster, but I wasn't happy about it. I thought I  
should try Clear Linux since I work at Intel. One thing is for sure, it  
really boots fast! And I learned to mount my other partitions with systemd.  
Now if only firmware could initialize things as quickly (I have a Xeon with  
ECC memory).

-- 
Mark Rustad, MRustad@mac.com

**Comment by bryteise** [comment] 2018-07-18 18:42
So I'm not able to reproduce the formatting of the boot partition if it wasn't set to be formatted previously. I see it creating two folders EFI and loader. The partitions content and type are otherwise left alone.

Clear does need an EFI boot partition for Clear Linux which can be shared between distributions though Clear will add systemd-boot content which could conflict with other distros as far as defaults go at least.

There is a new version of the installer UI in the works and this feedback would be useful for @dorileo to see at least.

**Comment by mrkz** [comment] 2019-03-21 19:29
Probably related with https://github.com/clearlinux/clr-installer/issues/180#issuecomment-444593717:

> Currently, clr-installer will always rewrite the partition table and recreate all file systems regardless if it was pre-partitioned with another tool or partitioned within the TUI -- All Data will always be lost as it is currently implemented. This is why there is a secondary warning message which states this.

**Comment by miguelinux** [comment] 2019-03-21 23:06
I have the same issue here :(,

If you have a defined partition table clr-installer drop it.

**Comment by mdhorn** [comment] 2019-05-08 16:42
This was a known issue in the installer for some time -- the mitigation was the Warning message before starting installation that clearly states that the disk will be erased.

The problem was addressed in the 1.2.0 release. We not have "Safe Installs" that will only use unallocated disks or free space on a drive to deploy the default partitions required for Clear Linux OS, "Destructive" which will wipe the selected disk the default partitions required for Clear Linux OS, or Advanced Configuration which will let you manually add the required partitions.

I think this issue can be closed.

**Comment by zilogat0r** [comment] 2019-07-10 16:03
Actually,
now it's even worse! It has REWRITTEN w/o any warning/confirmation the whole system disk /dev/nvme0n1, although I selected "safe" install into unused space on that device. Although the distro is marvelous, the installer is horrible. Hell, TALK TO THE USER, when modifying HDDs!

Sorry, no log, it's a deep problem of the whole concept. No confirmation of disk repartition, no summary to be acknowledged - are you kidding? Even back in dark 90s distros didn't dare to do that!

Linux clr-live 5.1.16-794.native #1 SMP Wed Jul 3 10:56:51 PDT 2019 x86_64 GNU/Linux
clr-installer-gui: 2.0.8, built on 2019-07-03_19:07:21_UTC

**Comment by tjad** [comment] 2019-12-18 14:35
*BUMP*

This is a top priority for IPX installations where a preinstall script does the partitioning (for raid etc)

Please allow for clr-installer to not required "size" property, when left out, it should assume that the partition already exists. - I think all above would concur to this behaviour.

**Comment by mdhorn** [comment] 2019-12-18 19:10
@tjad The original problem noted here was resolve long ago. This should have been transferred to the https://github.com/clearlinux/clr-installer project.

I'm planning to close issue here in the distribution.

If there is some requirement we are missing, please open an issue in the clr-installer project. It will be help to have your requirements more so than proposed solution. For example, we already have a meaning when the size is not present -- One partition the size can be left off to allow for the remainder of the free space to be used for that partition.

**Comment by tjad** [comment] 2019-12-18 21:37
@mdhorn I see. Thanks.
So that would mean there are 2 ways to activate that feature.. The alternative being to set the size to  "0"

I'll create an issue. My requirement should be clear from above.
I want to do my own partition management (creation), and have clearos installed on the partitions I've  already setup.

**Closed** 2019-12-18 22:03 UTC
Labels: bug, high priority
