### ISSUE TITLE
Hard to position mouse so that resize of window is possible

### ISSUE THREAD

**Issue by Meai** [clearlinux/distribution#642] opened 2019-04-24 19:49 UTC
The area for when the mouse turns into a draggable mouse is too tiny. Please make the borders more easily resizable. I tried to add my own decoration modifications to `/usr/share/themes/Adwaita/gtk-3.0/gtk.css` but it doesnt seem to do anything. Most of the online suggestions around Gnome 3 seem to reference some kind of MetaCity xml file that doesnt exist here on clearlinux. 
I dont know why Gnome 3 on Centos 7 and Opensuse Leap 15 dont have this problem, maybe because it's an older version.

**Comment by ahkok** [comment] 2019-04-24 21:23
@markz @ikeyd ?

**Comment by mrkz** [comment] 2019-04-24 21:29
@Meai Thanks for your your bug report :tada: 

it sounds a lot like a duplicate of https://github.com/clearlinux/distribution/issues/572, mind to verify if this is what you're seeing as well?

**Comment by Meai** [comment] 2019-04-24 21:44
@mrkz yeah I see that problem too, but mine may not be related or maybe it is likewise solved with that one. It's just generally quite hard to get the corner

**Comment by mrkz** [comment] 2019-04-24 23:08
@Meai can you confirm if this issue is present only on Xorg GNOME session and not it a Wayland GNOME session?

**Comment by Meai** [comment] 2019-04-25 08:28
@mrkz yeah I tested Wayland Gnome and it works perfectly there. How do I make this the default?

**Comment by tpleavitt** [comment] 2019-04-30 18:00
a duplicate of #572, closing

**Closed by tpleavitt** 2019-04-30 18:00 UTC
Labels: bug
