### ISSUE TITLE
swupd is slow

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#77] opened 2018-06-02 03:04 UTC
Installing bundles via swupd is very slow.

What is happening behind the scenes that takes so long?

Isn’t swupd just based on rpm?

**Comment by matthewrsj** [comment] 2018-06-02 03:18
Can you provide some more information? 

How long does it take? 
What does the output look like when it starts taking a long time? 
What bundle? 
Can you do another bundle add with '-t' flag supplied (and post the output)?

Also what is the output of 'swupd info' and what is your geolocation (generally)?

Sorry for the poor formatting, I'm on mobile.

**Comment by sirredbeard** [comment] 2018-06-02 03:32
I would be glad to. I hope my original comment does not seem too hostile or flippant. I just wanted to find out more.

I am a distro-hopper and have worked with most Linux distros. swupd feels, to me, significantly slower compared to apt, yum, dnf, zupper, eopkg.

It just seems odd such a fast distro would have such a sluggish package manager.

It is in general and applies across bundles at all times. Perhaps there is a very reasonable explanation, like it's performing optimizations in the background or verifying builds.

I fully admit it could just be me and I could be wrong here.

Here is some data as requested.

https://gist.github.com/sirredbeard/d84cdc9256118a9b5aa60615380c91e9

Installed version: 22690
Version URL:       https://download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/

I am in the SE US.

**Comment by fenrus75** [comment] 2018-06-02 04:40
we've had reports that our CDN is slow; swupd is by design in theory a lot
more efficient than rpm based package managers and we do track download
sizes etc.

**Comment by fenrus75** [comment] 2018-06-02 04:48
thanks for the data, part of it seems to be download time and part hash
checking time.

download time is a mix of size and CDN performance

we'll get some folks working on checking this from a few parts in the
world.. and there might just be a performance bug lurking as well..

**Comment by fenrus75** [comment] 2018-06-02 06:45
it's supposed to be like this

```
Update started.
Preparing to update from 22720 to 22750
Downloading packs...

Extracting R-extras pack for version 22730
        ...4%
Extracting desktop pack for version 22730
        ...17%
Extracting desktop-dev pack for version 22730
        ...73%
Extracting sysadmin-basic pack for version 22730
        ...88%
Extracting vim pack for version 22730
        ...100%

Statistics for going from version 22720 to version 22750:

    changed bundles   : 9
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 62
    new files         : 122
    deleted files     : 131

Starting download of remaining update content. This may take a while...

File /usr/bin/firefox was not in a pack
        ...100%
Finishing download of update content...
Staging file content
Applying update
        ...100%
Update was applied.
Calling post-update helper scripts.
Update took 2.7 seconds
Update successful. System updated from version 22720 to version 22750
41 files were not in a pack

```

**Comment by ahkok** [comment] 2018-06-02 19:39
It seems that in the pasted log output, that something unexpected occurred when you installed the `containers-basic` bundle, and `swupd` went into full `verify --fix` mode to recover the error and repair the system. This is an expensive and unusual operation that should normally not happen, and costs time because all the files on disk are being verified.

As to what is the actual cause of this problem, that remains unclear, but it explains the time needed.

BTW, we're always looking for ways to improve performance and correct issues, so bug reports like these are highly appreciated.

**Comment by matthewrsj** [comment] 2018-06-04 16:11
> @sirredbeard I hope my original comment does not seem too hostile or flippant. I just wanted to find out more.

Not at all, we love getting reports.

> swupd feels, to me, significantly slower compared to apt, yum, dnf, zupper, eopkg.

Well, you should keep a couple things in mind. First, you are doing a bundle-add, which brings in more than one package. The ansible bundle (https://download.clearlinux.org/update/22690/Manifest.ansible) pulls in quite a few dependencies. In Clear Linux we try to provide a complete functional use-case with our bundles, not just a single package. Keep in mind that swupd is **not a package manager** and you are getting far more than what is provided in the ansible RPM.

Our main goal is fast updates (or at least update speeds *proportional* to the size of the update), which is reflected in @fenrus75's update speed posted above. Performance for bundle-adds are a secondary concern.

But they are a concern nonetheless. There are a few shortcomings in distribution policy that can cause some overlap in files between what you download for a bundle-add and what you actually need on the system for a bundle-add (you downloaded the complete pack of files needed for your bundle yet you may have already had some of those files on your filesystem). The solution to this is a bit of a change to how we work as a distro so that will need to be discussed internally before any work is done on that.

As for the `containers-basic` bundle-add, @ahkok was correct, something went wrong that put the bundle-add on an error path, which takes considerably longer.

Also, a little more data: when I bundle-added ansible it took me about 20 seconds total. Not fast but not unexpected considering how much dependencies are being pulled in.

Thanks for the report and I have a couple ideas on how to improve bundle-add performance.

**Comment by fenrus75** [comment] 2018-06-07 14:58
ok so I tihnk we have multiple problems

a user interface issue (no visibility in progress)

downloading takes long potentially (and does not overlap with other operations currently)

we download "too much" versus expectations
(this is a size statement)


on the 3rd element I have a python script to at least help us analyze where size is coming from; will work with @matthewrsj and co to get that shipped as part of swupd so we can do broader analysis


also @matthewrsj what do you think about printing the total downloaded amount on each update, similar to how we already print the total time?

**Comment by matthewrsj** [comment] 2018-06-12 22:37
Ok, so some things have happened over the last several days. Some of this is distro policy and some is implementation changes

We no longer allow packages to be listed in bundles if there is a corresponding pundle. These must instead be listed as bundle includes. This allows file subtraction to occur in mixer and make individual bundles smaller and more modular overall. It also makes pack sizes smaller for bundles meaning download time could decrease if you already have an included bundle on your system.

We defined several more pundles from packages that showed up in 5 or more different bundles. This also helped with bundle bloat, decreased individual bundle size, and made them more modular. Same result as above.

@fenrus75 has been working on trimming our existing bundles down considerably by removing large dependencies from several bundles.

@fenrus75 also implemented an improvement to bundle-add code that allows small bundle additions to forego the full zero-pack download and only download the necessary full files when it will be faster to do so.

Bundle-add is still not perfect, but it has improved a lot recently. More changes are coming wrt UI enhancements. @ahkok I'm comfortable closing this as the specific issue is around bundle-add.

**Closed** 2018-06-18 15:09 UTC
