### ISSUE TITLE
Plugging in secondary monitor with GTX1070 gets funky results....

### ISSUE THREAD

**Issue by leopck** [clearlinux/distribution#373] opened 2019-01-21 17:03 UTC
**Describe the bug**
Plugging a secondary monitor after boot up of Clear Linux to a GTX1070 will get some weird output. Please view screenshot below regarding the issue.

**To Reproduce**
1. Boot up Clear Linux
2. Plug a secondary display (HDMI or DP)
3. Wait for the flickering to occur

**Expected behavior**
Display GDM on the secondary display on GTX1070.

**Screenshots**
![image](https://user-images.githubusercontent.com/4161783/51488653-0f1e4580-1de1-11e9-9c94-a8ed02bb30a8.png)
![image](https://user-images.githubusercontent.com/4161783/51488666-1d6c6180-1de1-11e9-83d8-91fda94cebed.png)

**Environment (please complete the following information):**
 - Clear Linux OS version: 27200

**Comment by ahkok** [comment] 2019-01-21 18:48
Even though they're slightly different, I'm marking these duplicate since they're all about the same hardware configuration issues.

**Comment by ahkok** [comment] 2019-01-21 18:49
Duplicate of #371

**Closed by ahkok** 2019-01-21 18:49 UTC

**Comment by thiagomacieira** [comment] 2019-01-22 16:20
I haven't used NVidia for 8 years, but when I did, you needed to run one of their tools to make the system detect a monitor being added or removed. It was not automatic like with Intel drivers.
