### ISSUE TITLE
Invalid LC_CTYPE

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#36] opened 2018-04-03 00:38 UTC
With today's update I am seeing new bash shells complain about LC_TYPE via the following:
"bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)"

**Comment by fenrus75** [comment] 2018-04-03 02:22
looks like something weird happened

I just added a BBT regression test for this case at least

**Comment by phmccarty** [comment] 2018-04-03 17:39
I'm working on this.

**Comment by phmccarty** [comment] 2018-04-06 00:31
This issue was fixed in 21640.

**Closed** 2018-04-09 18:39 UTC
