### ISSUE TITLE
Megatools GPLv2

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#1404] opened 2019-10-27 13:33 UTC
Could you please add a bundle for [Megatools](https://megatools.megous.com/)?

> Megatools is a collection of programs for accessing Mega.nz service from a command line of your desktop or server.

> Megatools allow you to copy individual files as well as entire directory trees to and from the cloud. You can also perform streaming downloads for example to preview videos and audio files, without needing to download the entire file.

It interacts with duplicity and is available on debian, for example. It is a good tool for backups.

Thanks

**Comment by ahkok** [comment] 2019-10-27 18:14
Duplicate of #1304

**Comment by ahkok** [comment] 2019-10-27 18:15
Also, I suspect `rclone` properly supports mega.

**Closed by ahkok** 2019-10-27 18:14 UTC
Labels: new, package-request

**Comment by nazar2sfive** [comment] 2019-11-01 16:02
rclone is too "terminal". i hate terminal.
i hope megasync to work someday in clear linux.

**Comment by anselmolsm** [comment] 2019-11-01 16:16
> rclone is too "terminal". i hate terminal.

@nazar2sfive Could you please elaborate? Megatools' website title says: "Megatools - **command line client** for Mega.nz". The showcase video shows it is a command line (terminal) tool...

> Also, I suspect rclone properly supports mega.

BTW, rclone has a web UI - https://rclone.org/gui/

**Comment by nazar2sfive** [comment] 2019-11-01 16:22
```
android@clr  ~ 
$ rclone rcd --rc-web-gui
Error: unknown flag: --rc-web-gui
Usage:
  rclone rcd <path to files to serve>* [flags]

Flags:
  -h, --help   help for rcd

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2019/11/01 22:06:06 Fatal error: unknown flag: --rc-web-gui
android@clr  ~ 
$ 

```
