### ISSUE TITLE
"$ yarnpkg --version" return error

### ISSUE THREAD

**Issue by liujianjunhq** [clearlinux/distribution#1189] opened 2019-09-05 11:20 UTC
After I have nodejs-basic bundle installed, I tested to run yarnpkg via "$ yarnpkg --version". It reports below error message, instead of the version number. 
$ yarnpkg --version
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/yarn/bin/../lib/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ahkok** [comment] 2019-09-05 22:51
Confirmed.

**Comment by ahkok** [comment] 2019-09-05 22:53
Possibly upstream `yarnpkg` bug.

**Comment by lebensterben** [comment] 2019-10-22 23:58
On my system with `yarnpkg` version 1.19.1, it's fixed.

**Comment by AthenasJimenez** [comment] 2019-10-23 15:29
Confirmed on latest release: 31370. I'll take a look to it

**Comment by AthenasJimenez** [comment] 2019-11-25 18:32
Error caused by wrong build process, but won't fix it since it would be removed from Clear Linux by November 29th.

**Closed by AthenasJimenez** 2019-11-25 18:32 UTC
Labels: bug
