### ISSUE TITLE
nginx-mainline failing to start after an update

### ISSUE THREAD

**Issue by ljmccarthy** [clearlinux/distribution#2171] opened 2020-10-27 22:55 UTC
I had a working configuration for nginx-mainline, but since an update it is now failing to start. I have not made any changes to the configuration. The error reported is:

```
nginx-mainline[140806]: 2020/10/27 22:45:40 [emerg] 140806#140806: unknown header/footer kind "asf" in /etc/nginx-mainline/conf.d/site.conf:3
nginx-mainline[140806]: nginx: configuration file /usr/share/nginx-mainline/conf/nginx.conf test failed
```

The offending line in the configuration file is:

`fancyindex_header       /.theme/header.html;`

**Comment by phmccarty** [comment] 2020-10-27 23:27
Looks like this was a regression introduced with https://github.com/clearlinux-pkgs/ngx-fancyindex/commit/b20571a1525edccffc1343549c66b552b20aa1c7.

We updated the package to 0.5.1 this morning, which [appears to fix the issue](https://github.com/aperezdc/ngx-fancyindex/releases/tag/v0.5.1). 0.5.1 will be included in the next build.

**Comment by phmccarty** [comment] 2020-10-29 23:23
ngx-fancyindex was updated in release [33910](https://cdn.download.clearlinux.org/releases/33910/clear/RELEASENOTES).

**Closed by phmccarty** 2020-10-29 23:23 UTC
Labels: bug
