### ISSUE TITLE
Can't log in as "root" through GDM

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#445] opened 2019-02-12 17:20 UTC
Even though I set a password for "root", I can't log in as "root" through the Gnome Desktop Manager.  

Steps to repro:
1) Set root's password.
2) At GDM login screen, select "Not listed?"
3) Enter "root" as the username.
4) Enter root's password.

Result: Unable to log in.

**Comment by mdhorn** [comment] 2019-02-12 18:53
@bktan8 This is by design. In general, it is bad to log into the environment as root.
There is a default rule in the gdm-password to prevent direct login of any account with a UID of <= 1000; preventing all system accounts from login.

See line 6 
```
$ cat -n /usr/share/pam.d/gdm-password
     1	# Begin /etc/pam.d/gdm-password
     2
     3	auth     requisite      pam_nologin.so
     4	auth     required       pam_env.so
     5
     6	auth     required       pam_succeed_if.so uid >= 1000 quiet
     7	auth     include        system-auth
     8	auth     optional       pam_gnome_keyring.so
     9
    10	account  include        common-account
    11	password include        common-password
    12
    13	session  required       pam_limits.so
    14	session  include        common-session
    15	session  optional       pam_gnome_keyring.so auto_start
    16
    17	# End /etc/pam.d/gdm-password

```

If for some reason one truly needs to login as root, create a local copy of this file in /etc/pam.d with line 6 removed or commented out. 
**Note:** You might have to restart gmd (reboot) for the change to take effect.

**Comment by nesiusra** [comment] 2019-02-12 19:05
These settings are part of our security architecture, and there is a workaround available if people really want to be insecure. :)  I'm going to close this one.

**Closed by nesiusra** 2019-02-12 19:05 UTC
Labels: bug
