### ISSUE TITLE
NVidia Driver: Unable to load nvidia-drm module

### ISSUE THREAD

**Issue by jonahbron** [clearlinux/distribution#1994] opened 2020-05-26 20:34 UTC
I have a fresh install of Clear Linux on my machine.  I've installed the Nvidia driver previously with success.  However this time, I'm getting an error:

```
ERROR: Unable to load the 'nvidia-drm' kernel module.
```

This happens when running the NVidia .run driver file, and the install fails.  I've tried several different kernel versions (lts2018, lts2019, native), and several different versions of the Nvidia driver (long-lived and short-lived).  All scenarios have the exact same result.  What might prevent the installer from loading the drm kernel module?  The only info I've found by searching suggested it has to do with UEFI, so I tried disabling that too and booting in legacy mode.  No change.

I've already raised this on the [NVidia forum](https://forums.developer.nvidia.com/t/clear-linux-error-unable-to-load-the-nvidia-drm-kernel-module-gtx-970/124836), but I'm bringing it here too in case someone with more Clear Linux-specific knowledge knows a solution.  Also for future documentation purposes of any solution.

Here is the full nvidia-installer.log output.

```
nvidia-installer log file '/var/log/nvidia-installer.log'
creation time: Mon May 25 21:06:11 2020
installer version: 440.82

PATH: /usr/bin/haswell:/usr/local/bin:/usr/bin:/opt/3rd-party/bin

nvidia-installer command line:
    ./nvidia-installer
    --utility-prefix=/opt/nvidia
    --opengl-prefix=/opt/nvidia
    --compat32-prefix=/opt/nvidia
    --compat32-libdir=lib32
    --x-prefix=/opt/nvidia
    --x-module-path=/opt/nvidia/lib64/xorg/modules
    --x-library-path=/opt/nvidia/lib64
    --x-sysconfig-path=/etc/X11/xorg.conf.d
    --documentation-prefix=/opt/nvidia
    --application-profile-path=/etc/nvidia/nvidia-application-profiles-rc.d
    --no-precompiled-interface
    --no-nvidia-modprobe
    --no-distro-scripts
    --force-libglx-indirect
    --glvnd-egl-config-path=/etc/glvnd/egl_vendor.d
    --egl-external-platform-config-path=/etc/egl/egl_external_platform.d
    --dkms
    --silent

Using built-in stream user interface
-> Detected 16 CPUs online; setting concurrency level to 16.
WARNING: Unable to determine the default library path. The path /opt/nvidia/lib will be used, but this path was not detected in the ldconfig(8) cache, and no directory exists at this path, so it is likely that libraries installed there will not be found by the loader.
WARNING: Unable to determine the default X library path. The path /opt/nvidia/lib will be used, but this path was not detected in the ldconfig(8) cache, and no directory exists at this path, so it is likely that libraries installed there will not be found by the loader.
-> Installing NVIDIA driver version 440.82.
-> Would you like to register the kernel module sources with DKMS? This will allow DKMS to automatically build a new module, if you install a different kernel later. (Answer: Yes)
-> Install NVIDIA's 32-bit compatibility libraries? (Answer: Yes)
Looking for install checker script at ./libglvnd_install_checker/check-libglvnd-install.sh
   executing: '/bin/sh ./libglvnd_install_checker/check-libglvnd-install.sh'...
   Checking for libglvnd installation.
   Checking libGLdispatch...
   Can't load library libGLdispatch.so.0: libGLdispatch.so.0: cannot open shared object file: No such file or directory
Will install libglvnd libraries.
Will install libEGL vendor library config file to /etc/glvnd/egl_vendor.d
-> Searching for conflicting files:
-> done.
-> Installing 'NVIDIA Accelerated Graphics Driver for Linux-x86_64' (440.82):
   executing: '/usr/bin/ldconfig'...
-> done.
-> Driver file installation is complete.
-> Installing DKMS kernel module:
-> done.
ERROR: Unable to load the 'nvidia-drm' kernel module.
ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.
```

**Comment by jonahbron** [comment] 2020-05-27 15:28
This can be reportedly fixed by rolling back to system version 32990

https://github.com/lebensterben/awesome-clear-linux/issues/9#issuecomment-634556854

**Comment by jonahbron** [comment] 2020-05-27 15:29
According to a comment on the Nvidia forum thread, it's possible the kernel headers aren't installed.  Does this sound plausible?  What swupd package would those be in?  I've used `repair --picky`, so it's definitely not a problem with a bundle I already have installed.

**Comment by puneetse** [comment] 2020-05-27 16:21
If you have the dkms bundles installed and got this far, you have the kernel headers. You can verify with `sudo swupd bundle-list | grep linux-dev`.

A good troubleshooting step to get more information would be to manually try manually load the problematic module with `modprobe --verbose` while watch the output of the command, dmesg, and journal.

**Comment by jonahbron** [comment] 2020-05-27 20:16
Thanks for the reply. Greping for the linux-dev bundle yielded no results. There is a bundle called linux-dev, but it wasn't installed. I tried installing it and running the driver installer again, but it had no effect. 

Can you give more info around the commands you mentioned? Modprobe, dmesg, journal. I tried running, `modprobe --verbose nvidia` but it says module not found. There problem is it isn't installing, not that it's not working.

**Comment by thiagomacieira** [comment] 2020-05-27 23:12
There is a bundle called `linux-dev` but that's not what you're looking for. You want `kernel-native-dkms` (or `kernel-lts2019-dkms`).

**Comment by jonahbron** [comment] 2020-05-27 23:34
@thiagomacieira I do have the `-dkms` bundles for the kernels I've tried.

**Comment by Boulotaur2024** [comment] 2020-05-28 05:37
I'm having the exact same issue here.
Will follow closely this topic.
(I had to reinstall everything from scratch yesterday night as I had no idea how to restore old Nouveau driver...)

I don't know if it's relevant but could something be done in order to simplify the NVIDIA proprietary driver: the whole process seems ridiculously painful

Thanks a lot Clear Linux team !

**Comment by insilications** [comment] 2020-05-28 07:10
Same issue here.

**Comment by insilications** [comment] 2020-05-28 08:03
Could be because of gcc 10. Someone was saying the problem disappears with gcc 10 test version https://aur.archlinux.org/packages/nvidia-390xx-dkms/

**Comment by jonahbron** [comment] 2020-05-28 16:51
@Boulotaur2024 At the very least I recommend using the [awesome-clear-linux](https://github.com/lebensterben/awesome-clear-linux) NVidia installer scripts.  It _was_ working before something in Clear Linux changed and broke it 🤕

**Comment by jonahbron** [comment] 2020-05-28 16:52
@insilications Any idea how to get the test version installed on Clear Linux?  I don't suppose there's a bundle...

**Comment by aluo-x** [comment] 2020-05-29 00:44
[same issue? ](https://github.com/clearlinux/distribution/issues/1835#issuecomment-628886769) You can build your own kernel with `CONFIG_SECTION_MISMATCH_WARN_ONLY=y`, someone in that same thread reports it working.

**Comment by jonahbron** [comment] 2020-05-29 02:08
@aluo-x Hm, somebody in the NVidia forum thread mentioned that too.  Are there instructions on how do do that in Clear Linux?  I've never built a kernel before.  And while I'm happy to do that to find the cause of the problem, we should definitely try to figure out a more user-friendly upstreamed solution.

**Comment by aluo-x** [comment] 2020-05-29 02:31
The process is pretty easy: https://docs.01.org/clearlinux/latest/guides/kernel/kernel-development.html

But its not sustainable, I'm also not familiar enough with clear's update behavior to know if it will override the custom kernel (or how to disable/re-enable this behavior). 

I think it would be best to report this to Nvidia, with the details about `CONFIG_SECTION_MISMATCH_WARN_ONLY=y` being a required flag when using GCC 10 on the clear linux kernel. 

You could also roll back (and lock clear linux to a specific version), or potentially ask the clear team to [add the flag in the kernel config](https://github.com/clearlinux-pkgs/linux/blob/master/config#L8548). I believe debian [sets the flag by default](https://salsa.debian.org/kernel-team/linux/-/blob/master/debian/config/config), not sure why clear linux doesn't.

**Comment by jonahbron** [comment] 2020-05-29 17:23
If I need to compile the kernel with that flag set, why would I report it to NVidia?  Can the flag be set on _either_ the kernel _or_ the module, and both ways would hypothetically fix it?

**Comment by aluo-x** [comment] 2020-05-29 17:32
Isn't this an Nvidia bug? Or at least a consequence of them not being open source like Intel/amd.

I think getting Nvidia to fix this would be the user friendly upstream solution.

**Comment by lebensterben** [comment] 2020-05-29 17:52
>Isn't this an Nvidia bug? Or at least a consequence of them not being open source like Intel/amd. ...

@aluo-x We at least need to first pin down the cause of this issue in the current release of CL.

Have you verified that a kernel with aforementioned options would work with NVIDIA driver?

**Comment by aluo-x** [comment] 2020-05-29 18:30
Ther is this report [here](https://github.com/clearlinux/distribution/issues/1835#issuecomment-633109385). My machine is currently running a GPU task that cannot be halted.

**Comment by lebensterben** [comment] 2020-05-29 18:39
>Ther is this report [here](https://github.com/clearlinux/distribution/issues/1835#issuecomment-633109385). My machine is currently running a GPU task that cannot be halted. 

@aluo-x But that is caused by an entirely different issue, that kernel was built by a different GCC version, which is no longer the case.

**Comment by aluo-x** [comment] 2020-05-29 18:45
I cannot imagine what other kernel flag he could be referencing

**Comment by aluo-x** [comment] 2020-05-29 18:47
Also this [report](https://forums.developer.nvidia.com/t/clear-linux-error-unable-to-load-the-nvidia-drm-kernel-module-gtx-970/124836/8).

**Comment by hnanni** [comment] 2020-05-29 18:49
Got the drivers loaded, though without dkms.

The process is a bit involved, but it seems to be the only option while the clr developers sorts out the implications of their compiler update
1. Follow the [https://docs.01.org/clearlinux/latest/guides/kernel/kernel-development.html](clear linux documentation) to build a custom kernel. Have `CONFIG_SECTION_MISMATCH_WARN_ONLY=y` set
2. Once you have your kernel installed and booted, install also the -dev rpm that is left along your kernel's rpm:
`rpm2cpio linux-dev-5.6.15-957.x86_64.rpm | (cd /; sudo cpio -i -d -u -v);`

3. As described in [https://docs.01.org/clearlinux/latest/tutorials/nvidia.html] (clear linux's doc) run the nvidia installer, drop the` --dkms `option and instead, pass your kernel source path:
`--kernel-source-path=/usr/lib/modules/5.6.15-957.nanni/build/`

Have the nvidia drivers loaded:

```
[hnanni hnanni-desk3 ~] cat /proc/version ; lsmod | grep ^nvidia
Linux version 5.6.15-957.nanni (mockbuild@047d0eb03d6a42da98a6eef4310e892c) (gcc version 10.1.1 20200527 releases/gcc-10.1.0-86-g50cd4503e5 (Clear Linux OS for Intel Architecture)) #1 SMP Fri May 29 11:49:11 CDT 2020
nvidia_drm             45056  3
nvidia_modeset       1114112  5 nvidia_drm
nvidia              20463616  171 nvidia_modeset
nvidiafb               53248  0
```

**Comment by insilications** [comment] 2020-05-30 12:27
After two days trying to solve this, I've finally managed to install 440.82 with the latest kernel-native (custom built with SECTION_MISMATCH_WARN_ONLY). Perhaps nvidia or intel staff will clarify what's at fault here, but there is some problematic interaction between 5.6.15 kernel vs GCC 10.1 vs nvidia 440.92 installer in 1) creating the proper dkms build and source tree in "/var/lib/dkms/nvidia/440.82/" and 2) issuing the proper install command to the /usr/bin/dkms tool.

Using the following installation command (per https://docs.01.org/clearlinux/latest/tutorials/nvidia.html plus "--no-cc-version-check" just as a guarantee and "--expert" instead of "--silent" for a more verbose installation)

sudo ./NVIDIA-Linux-x86_64-440.82.run \
    --utility-prefix=/opt/nvidia \
    --opengl-prefix=/opt/nvidia \
    --compat32-prefix=/opt/nvidia \
    --compat32-libdir=lib32 \
    --x-prefix=/opt/nvidia \
    --x-module-path=/opt/nvidia/lib64/xorg/modules \
    --x-library-path=/opt/nvidia/lib64 \
    --x-sysconfig-path=/etc/X11/xorg.conf.d \
    --documentation-prefix=/opt/nvidia \
    --application-profile-path=/etc/nvidia/nvidia-application-profiles-rc.d \
    --no-precompiled-interface \
    --no-distro-scripts \
    --force-libglx-indirect \
    --glvnd-egl-config-path=/etc/glvnd/egl_vendor.d \
    --egl-external-platform-config-path=/etc/egl/egl_external_platform.d \
    --dkms \
    --no-cc-version-check \
    --expert

Using the "--expert" options reveals why the installer issues "ERROR: Unable to load the 'nvidia-drm' kernel module" without any explanation at all:

-> Driver file installation is complete.
-> Installing DKMS kernel module:
-> done.
ERROR: Unable to load the 'nvidia-drm' kernel module: 'modprobe: ERROR: ctx=0x5646828152a0 path=/lib/modules/5.6.15-957.native/kernel/drivers/video/nvidia-modeset.ko error=No such file or directory
modprobe: ERROR: ctx=0x5646828152a0 path=/lib/modules/5.6.15-957.native/kernel/drivers/video/nvidia-modeset.ko error=No such file or directory
modprobe: ERROR: could not insert 'nvidia_drm': Unknown symbol in module, or unknown parameter (see dmesg)'

The DKMS kernel modules are being built, but they are not being finally installed from the proper build directory to the corresponding kernel modules path. That is why they are not being loaded by modprobe. ls /var/lib/dkms/nvidia/440.82/ reveals the following:

source/
build/

The correct source symlink directory pointing to the nvidia kernel modules sources. And the build symlink directory which after the successful build should hold the resulting binaries, make.log, etc. And that is not happening. build/ is an empty directory. The solution is to manually build and install the dkms nvidia source tree. Here is the fix, after rebuilding the kernel with "SECTION_MISMATCH_WARN_ONLY". Start by installing the driver again, this time with the --silent flag instead of the --expert flag:

sudo ./NVIDIA-Linux-x86_64-440.82.run \
    --utility-prefix=/opt/nvidia \
    --opengl-prefix=/opt/nvidia \
    --compat32-prefix=/opt/nvidia \
    --compat32-libdir=lib32 \
    --x-prefix=/opt/nvidia \
    --x-module-path=/opt/nvidia/lib64/xorg/modules \
    --x-library-path=/opt/nvidia/lib64 \
    --x-sysconfig-path=/etc/X11/xorg.conf.d \
    --documentation-prefix=/opt/nvidia \
    --application-profile-path=/etc/nvidia/nvidia-application-profiles-rc.d \
    --no-precompiled-interface \
    --no-distro-scripts \
    --force-libglx-indirect \
    --glvnd-egl-config-path=/etc/glvnd/egl_vendor.d \
    --egl-external-platform-config-path=/etc/egl/egl_external_platform.d \
    --dkms \
    --no-cc-version-check \
    --silent

Go to the same /var/lib/dkms/nvidia/440.82/ directory. Enter source/, where dkms.conf and Makefile is. Try this:

sudo dkms autoinstall

All nvidia modules will be successfully build, added and installed. ls /var/lib/dkms/nvidia/440.82/ will now correctly show a proper dkms compilation tree:
source/
5.6.15-957.native/

The kernel should be custom rebuild with SECTION_MISMATCH_WARN_ONLY (Kernel hacking -> Compile-time checks and compiler options -> Make section mismatch errors non-fatal), following the simple guide: https://docs.01.org/clearlinux/latest/guides/kernel/kernel-development.html

**Comment by SPAstef** [comment] 2020-05-30 18:30
I fail to understand why in 2020 we still have such problems, it's the third update in a row I have to use the workaround of the unofficial workaround of the official workaround of the standard installation method to get a working GUI (for some reason, Nouveau seems to be giving issues, and I don't want to reinstall the whole system)

**Comment by SPAstef** [comment] 2020-05-31 11:03
A faster workaround which doesen't require building a new kernel:
1) Download latest NVIDIA driver
2) cd to the driver location, and enter in superuser mode with `sudo -s`
3) Execute the command: `export SECTION_MISMATCH_WARN_ONLY=y`
3) Compile with all the flags specified in the official guide, minus `--dkms` (so, no dynamic module)
4) enjoy

Maybe it works with DKMS too, I didn't try it, but at least you don't need to reinstall the kernel

**Comment by aluo-x** [comment] 2020-05-31 17:46
@SPAstef I'm confused, I thought `SECTION_MISMATCH_WARN_ONLY` was a kernel config option. Why would setting it as an env variable do anything?

**Comment by SPAstef** [comment] 2020-05-31 17:50
> @SPAstef I'm confused, I thought `SECTION_MISMATCH_WARN_ONLY` was a kernel config option. Why would setting it as an env variable do anything?

Maybe it can be set dynamically at runtime? IDK really, I just know that it got me back to my desktop, and I'm happy with that 😂

**Comment by jonahbron** [comment] 2020-05-31 22:56
I can confirm this worked for me too.

**Comment by GustavoPeredo** [comment] 2020-06-01 01:21
> A faster workaround which doesen't require building a new kernel:
> 
>     1. Download latest NVIDIA driver
> 
>     2. cd to the driver location, and enter in superuser mode with `sudo -s`
> 
>     3. Execute the command: `export SECTION_MISMATCH_WARN_ONLY=y`
> 
>     4. Compile with all the flags specified in the official guide, minus `--dkms` (so, no dynamic module)
> 
>     5. enjoy
> 
> 
> Maybe it works with DKMS too, I didn't try it, but at least you don't need to reinstall the kernel

That did not worked for me. I tried using the LTS kernel version and had the same issue, then tried newest kernel with Long Life nVidia driver and LTS kernel with Long Life nVidia driver, all scenarios resulted in Unable to load nvidia-drm kernel module. Running without --dkms resulted in other errors... I guess it is either a problem with my computer or a problem with the gcc compiler

**Comment by jonahbron** [comment] 2020-06-01 15:38
It took a little bit of playing around @GustavoPeredo to get it right.  Please inspect my diff closely.  Also, the correct name for the env name is `CONFIG_SECTION_MISMATCH_WARN_ONLY`

**Comment by lebensterben** [comment] 2020-06-01 15:46
>It took a little bit of playing around @GustavoPeredo to get it right.  Note that the correct name for the env name is `CONFIG_SECTION_MISMATCH_WARN_ONLY`

@jonahbron This doesn't make sense. This is a kernel config option not an environment variable checked when running the installer.

**Comment by SPAstef** [comment] 2020-06-01 15:53
> > It took a little bit of playing around @GustavoPeredo to get it right.  Note that the correct name for the env name is `CONFIG_SECTION_MISMATCH_WARN_ONLY`
> 
> @jonahbron This doesn't make sense. This is a kernel config option not an environment variable checked when running the installer.

Can you explain then why it works? I wasn't expecting it to work too, but it did :P

**Comment by thiagomacieira** [comment] 2020-06-01 16:07
Make inherits variables from the environment, so I'm guessing setting it made it set for KConfig too.

**Comment by bwarden** [comment] 2020-06-01 16:46
Setting `CONFIG_SECTION_MISMATCH_WARN_ONLY=y` makes `modpost` run without the `-E` option, which would otherwise set `sec_mismatch_fatal`, and trigger this section:
```
2662         if (sec_mismatch_count && sec_mismatch_fatal)
2663                 fatal("modpost: Section mismatches detected.\n"
2664                       "Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.\n");
```
It doesn't look like it actually affects any other part of the kernel compilation, so it's probably safe to set just when compiling troublesome modules. It might be worth adding to @lebensterben's scripts.

**Comment by bwarden** [comment] 2020-06-01 17:28
Looking at the bigger picture, though, I want to clarify a few points:
* The section mismatch warning indicates a potential problem between the kernel and the module. Setting this flag doesn't fix the problem, it just makes the warning non-fatal. Disabling it for the whole kernel may mask problems elsewhere.
* The underlying issue is that this particular driver is out-of-tree and doesn't move in lockstep with the upstream kernel itself.
* Problems like this will occur again in the future as long as this driver is out-of-tree.
* The proper solution is for this driver to be upstreamed so it can be maintained by the kernel community.
* We (the Clear Linux team) have no control over that, and can only provide limited support for this driver.

**Comment by SPAstef** [comment] 2020-06-01 17:40
@bwarden I completely agree with your point, and I do hope Nvidia makes the driver open or at least guarantees to keep it up to date (damn, they're not a startup or an indie team!).  Alas, nouveau drivers just are useless for CUDA programming and they perform not even comparably in 3D graphics, so having those drivers working is not a whim, but a need that determines the usefulness of the OS for this use-case

**Comment by jonahbron** [comment] 2020-06-01 18:43
> The section mismatch warning indicates a potential problem between the kernel and the module. Setting this flag doesn't fix the problem, it just makes the warning non-fatal. Disabling it for the whole kernel may mask problems elsewhere.

Agreed, NVidia needs to fix the root of the issue

> The proper solution is for this driver to be upstreamed so it can be maintained by the kernel community.  Fortunately, it seems to be working properly for me, haven't noticed any issues.

Good luck getting NVidia to open-source their driver. 😞 

> It might be worth adding to @lebensterben's scripts.

I would definitely settle for a programatic solution that can be added to the scripts.  Sounds like there might be a way to do that mentioned in the NVidia thread by editing a dkms conf file.

https://forums.developer.nvidia.com/t/clear-linux-error-unable-to-load-the-nvidia-drm-kernel-module-gtx-970/124836/19

I'll try to test this later.

**Comment by aluo-x** [comment] 2020-06-01 18:45
Has anyone reported this to Nvidia yet? 
Might be helpful to get them to fix this for their monthly release.

**Comment by jonahbron** [comment] 2020-06-01 18:46
There's a thread on the NVidia forum.  I don't know if there's a more official way to report things than that.

**Comment by aluo-x** [comment] 2020-06-01 18:53
I just shot `linux-bugs@nvidia.com` an email pointing to this thread and the `CONFIG_SECTION_MISMATCH_WARN_ONLY` work around. Hopefully they can sort this out for their next release.

**Comment by GustavoPeredo** [comment] 2020-06-05 00:29
> It took a little bit of playing around @GustavoPeredo to get it right. Note that the correct name for the env name is `CONFIG_SECTION_MISMATCH_WARN_ONLY`

Oh noes, lole!! Well, I might test this workaround next time... Thanks for the reply, btw.

**Comment by aluo-x** [comment] 2020-06-29 14:00
Are people still experiencing this? Are there any new work arounds?

**Comment by jonahbron** [comment] 2020-06-29 21:01
I haven't tried debugging updating anything since, I have no reason to believe the problem has gone away.

**Comment by SPAstef** [comment] 2020-06-29 21:03
I tried installing the new drivers (450.51) today. They seem to install successfully without DKMS, and don't need any trick, but I cannot get in the GUI. So... IDK...

**Comment by aluo-x** [comment] 2020-07-01 17:37
According to email correspondence with Nvidia, the problem has been fixed in [450.51 release](https://www.nvidia.com/Download/driverResults.aspx/160555/en-us). Perhaps people can test it out and report back if the `CONFIG_SECTION_MISMATCH_WARN_ONLY` flag is still needed.

I currently have a long running GPU compute task that I can't terminate :(

**Comment by SPAstef** [comment] 2020-07-01 17:40
> According to email correspondence with Nvidia, the problem has been fixed in [450.51 release](https://www.nvidia.com/Download/driverResults.aspx/160555/en-us). Perhaps people can test it out and report back if the `CONFIG_SECTION_MISMATCH_WARN_ONLY` flag is still needed.
> 
> I currently have a long running GPU compute task that I can't terminate :(

I did the update a couple days ago. This workaround is not needed anymore, but I had a different issue (with consequent workaround): [here](https://github.com/clearlinux/distribution/issues/2042#issuecomment-651832656)

**Comment by aluo-x** [comment] 2020-07-01 17:47
That's great to hear. Does the issue have anything to do with secure boot? I recall encountering a similar issue in the past, and having to disable secure boot in UEFI to avoid having sign a driver. But due to unrelated reasons I usually keep secure boot always disabled.

**Comment by aluo-x** [comment] 2020-07-01 17:48
Also I guess if the original bug is resolved in the newer drivers, this issue could be closed.

**Comment by SPAstef** [comment] 2020-07-01 17:49
> That's great to hear. Does the issue have anything to do with secure boot? I recall encountering a similar issue in the past, and having to disable secure boot in UEFI to avoid having sign a driver. But due to unrelated reasons I usually keep secure boot always disabled. 

IDK since I have it disabled and the issue is there anyway. I can't say if enabling it will cause the OS not to boot.

**Comment by jonahbron** [comment] 2020-07-01 22:18
As I posted in the forum thread, the solution was _not_ fixed for me.

https://forums.developer.nvidia.com/t/clear-linux-error-unable-to-load-the-nvidia-drm-kernel-module-gtx-970/124836/26

I ran the installer and I got the nvidia-drm error until I disabled dkms.

**Comment by SPAstef** [comment] 2020-07-01 22:37
> As I posted in the forum thread, the solution was _not_ fixed for me.
> 
> https://forums.developer.nvidia.com/t/clear-linux-error-unable-to-load-the-nvidia-drm-kernel-module-gtx-970/124836/26
> 
> I ran the installer and I got the nvidia-drm error until I disabled dkms.

Wait, we were talking about CONFIG_MISMATCH, not DKMS. That is still broken also for me

**Comment by lebensterben** [comment] 2020-07-08 17:43
It seems that someone on our forum figured this out
> adding directory path for my kernel during advanced setup options of NVIDIA, it somehow manages to create directory and resolve that error.

https://community.clearlinux.org/t/anyone-get-the-nvidia-drivers-working/4783/5?u=doct0rhu

**Comment by aluo-x** [comment] 2020-07-08 18:08
I'm a little confused by the comment. What does it mean?

**Comment by lebensterben** [comment] 2020-07-08 18:12
>I'm a little confused by the comment. What does it mean? 

@aluo-x This user successfully compiled the driver. At first he has same issue on "nvidia-drm" module not found, but it was solved by his workarounds.

**Comment by aluo-x** [comment] 2020-07-08 18:13
Sorry, I meant I was confused by his workaround.

**Comment by lebensterben** [comment] 2020-07-08 18:21
>Sorry, I meant I was confused by his workaround. 

@aluo-x I'm confused right from seeing nvidia-drm not found.

**Comment by aluo-x** [comment] 2020-08-02 01:06
Just as an update, I was able to install Nvidia's 450.57 driver w/ DKMS, and CUDA 11 on clear linux with the 5.7.11 kernel successfully using the scripts provided by @lebensterben

**Comment by lebensterben** [comment] 2020-08-02 01:07
>Just as an update, I was able to install Nvidia's 450.57 driver w/ DKMS, and CUDA 11 on clear linux with the 5.7.11 kernel successfully using the scripts provided by @lebensterben 

@aluo-x Thanks, I can also confirm this.

**Comment by brucethemoose** [comment] 2020-11-30 02:54
Running into this same issue, on an RTX 2060 laptop.

Currently trying different permutations of all the workarounds, no luck so far.

**Comment by aluo-x** [comment] 2020-11-30 03:17
Manually apply this patch:
https://github.com/Frogging-Family/nvidia-all/blob/master/patches/kernel-5.9.patch

Worked for me. 
Extract the nvidia driver package, apply the patch, then manually install using the clear linux flags.

**Comment by brucethemoose** [comment] 2020-11-30 04:25
> Manually apply this patch:
> https://github.com/Frogging-Family/nvidia-all/blob/master/patches/kernel-5.9.patch
> 
> Worked for me.
> Extract the nvidia driver package, apply the patch, then manually install using the clear linux flags.
> 
> Edit: the patch above is incorrect. Use this one instead -- https://github.com/Frogging-Family/nvidia-all/blob/master/patches/5.9-gpl.diff
> 
> Edit 2:
> To extract the driver, run the driver with the `--extract-only` flag.
> 
> You can then manually find the files mentioned in the `.diff`, I don't think the line numbers match, but you can easily find the correct lines by searching within the two files.
> 
> Finally, run the `nvidia-installer` with the usual flags.

Interesting fix... the lines *and* the file paths are, indeed, wrong.

I manually changed the lines, but it didn't seem to make any difference. At the end of the installation, the (modded) installer errors out with "Unable to load the 'nvidia-drm' kernel module"

**Comment by aluo-x** [comment] 2020-11-30 04:29
My understanding is the bug we are encountering is the following: https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-Linux-5.9-Delayed

I modified the awesome-clear-linux Nvidia installer/updater to use the nvidia-installer file instead.

**Comment by SPAstef** [comment] 2020-11-30 08:38
I had some issues too, but I'm the end got the driver installed. The steps I did were the following:
1) Uninstall the NVIDIA driver.
2) Check that the /opt/nvidia folder is removed. For some reason, the installation had problems if this folder was not removed.
3) Reinstall the driver,following the usual procedure you find on the CL docs (or you could try to use the bash scripts... I disabled DKMS, so I can't assure you that it will work with DKMS on)

**Comment by brucethemoose** [comment] 2020-11-30 21:12
> I had some issues too, but I'm the end got the driver installed. The steps I did were the following:
> 
> 1. Uninstall the NVIDIA driver.
> 2. Check that the /opt/nvidia folder is removed. For some reason, the installation had problems if this folder was not removed.
> 3. Reinstall the driver,following the usual procedure you find on the CL docs (or you could try to use the bash scripts... I disabled DKMS, so I can't assure you that it will work with DKMS on)

Still no luck, with or without dkms :(

Beyond the installer log, where should I be looking to troubleshoot the "Unable to load the 'nvidia-drm' kernel module" issue? The dkms driver seems to be correctly installed in  `/var/lib/dkms/nvidia`, and running `sudo dkms autoinstall` doesn't seem to have an effect.

**Comment by aluo-x** [comment] 2020-11-30 21:15
How exactly did you install the driver? Did you use the scripts provided in awesome-clear-linux?

**Comment by brucethemoose** [comment] 2020-11-30 21:52
> How exactly did you install the driver? Did you use the scripts provided in awesome-clear-linux?

First I tried the install scripts yes. Then I followed the clear-linux wiki guide word-for-word, verifying that all the specified tweaks are in place, and then I double checked it.

I'm using the 455.45 drivers. First I tried them as they come, then I tried with the license edit.

I've tried multiple permutations of fixes, including installation without silent mode, installing the non-dkms drivers (which seem to install, but they complain about signature verification and result in a black screen).

I'm probably going to try a clean iso installation at some point (unless there's another good way to reset clear linux back to stock settings), but I have to wait a few days to try that.

**Comment by aluo-x** [comment] 2020-11-30 21:55
I also had to delete the /opt/nvidia folder, otherwise it seemed like the update would fail.

**Comment by brucethemoose** [comment] 2020-11-30 21:56
I should also mention that the same dkms Nvidia drivers work perfectly in Arch Linux, dual booted on the same machine, so there seems to be some Clear Linux specific issue.

Also, I'm already running a dkms module for keyboard functions in clear linux.

**Comment by brucethemoose** [comment] 2020-11-30 21:58
> I also had to delete the /opt/nvidia folder, otherwise it seemed like the update would fail.

I tried this as well. 'rm -r /nvidia/opt` before a few installation attempts.

**Comment by SPAstef** [comment] 2020-11-30 22:50
> > I also had to delete the /opt/nvidia folder, otherwise it seemed like the update would fail.
> 
> I tried this as well. `rm -r /nvidia/opt` before a few installation attempts.

Manual removal of that folder is vital, otherwise for some reason the folder /opt/nvidia/lib doesn't get correctly populated (basically it won't contain any library, but lib64 would, so you could probably still manually link it).

Do you have the "optimus.config" workaround enabled? Did you enable CONFIG_SIG_FORCE? Don't do the silent installation, always go for the graphical one. It's a bit more boring i give you that, but you get to choose to keep the private key, which if removed caused an installation error on my laptop

**Comment by SPAstef** [comment] 2020-11-30 22:55
> > > I also had to delete the /opt/nvidia folder, otherwise it seemed like the update would fail.
> > 
> > 
> > I tried this as well. `rm -r /nvidia/opt` before a few installation attempts.
> 
> Manual removal of that folder is vital, otherwise for some reason the folder /opt/nvidia/lib doesn't get correctly populated (basically it won't contain any library, but lib64 would, so you could probably still manually link it).
> 
> Do you have the "optimus.config" workaround enabled? Did you enable CONFIG_SIG_FORCE? Don't do the silent installation, always go for the graphical one. It's a bit more boring i give you that, but you get to choose to keep the private key, which if removed caused an installation error on my laptop. 
As a rule of thumb, in the 2+ years I've been using Clear Linux, a driver reinstall is consistently needed after a few updates anyway (at least it used to be like that for a long time) so I don't even bother with DKMS anymore. Also NVIDIA drivers get updated relatively frequently, so you get to update them anyway.

**Comment by brucethemoose** [comment] 2020-11-30 23:24
@SPAstef What do you mean by "optimus.config" and "CONFIG_SIG_FORCE?"

**Comment by SPAstef** [comment] 2020-11-30 23:35
> @SPAstef What do you mean by "optimus.config" and "CONFIG_SIG_FORCE?"

https://wiki.archlinux.org/index.php/NVIDIA_Optimus

It's `optimus.desktop` actually. Basically disable Optimus and change the default GPU to nvidia. The CONFIG_SIG_FORCE flag (maybe it's spelled CONFIG_MODULE_SIG_FORCE, i don't remember now) is the one that allows you to bypass the signature check of the module, or something like that. Basically you are able to install the driver, otherwise installation fails

**Comment by bwarden** [comment] 2020-11-30 23:53
> 
> 
> Running into this same issue, on an RTX 2060 laptop.
> 
> Currently trying different permutations of all the workarounds, no luck so far.

This would be better as a discussion in [our forum](https://community.clearlinux.org/) than resurrecting this relatively old GH issue. Chances are each new breakage of NVIDIA's driver has a different underlying cause. We (Clear Linux team) also don't formally support it, so opening an issue here doesn't really get the right eyes on it.

**Closed by bwarden** 2020-11-30 23:53 UTC
Labels: bug, new
