### ISSUE TITLE
Image did not authenticate.

### ISSUE THREAD

**Issue by thelinuxbashtard** [clearlinux/distribution#1366] opened 2019-10-16 21:41 UTC
For about 3 months now I've been trying to install Clear Linux on a brand new HP Pavilion 15-cs2073cl . I have ran the compatibility scripts and I get SUCCESS all the way across the board. I have made more than 200 bootable USBs made by different vendors and using RUFUS, DD, or Etcher. Every single time I try to boot into the USB I am greeted with "selected boot image did not authenticate/". However if I disable secure boot then I can boot into Clear linux, My understanding is that Clear linux should boot into UEFI with secure boot enabled. Any help or advice would be appreciated.

**Comment by ahkok** [comment] 2019-10-16 21:47
As discussed on the IRC forum (thanks for stopping by!) we currently still do not support Secure Boot.

Therefore, this is a duplicate of issue #234 `Secure Boot Support` which is still open.

@tpleavitt can you check we don't have any docs online that claim otherwise? thanks.

**Closed by ahkok** 2019-10-16 21:47 UTC

**Comment by tpleavitt** [comment] 2019-10-16 22:58
There should be no documentation that states we support secure boot at this point.
