### ISSUE TITLE
Default browser not available

### ISSUE THREAD

**Issue by orsetto-bruno** [clearlinux/distribution#803] opened 2019-05-25 11:18 UTC
From a fresh installation of ClearLinux (29620) I tried to sign in to the Slack application. This takes you to a web page to sign in to https://slack.login (or something like that) which it can't open, because it can't find a browser application. 

Firefox *is* installed on the system. 

I opened the Gnome default applications list and the selection for browser is empty, and you cannot interact with it to select the already installed firefox as the default. 

You *can* open firefox directly, where you'll be told that Firefox is not currently your default browser and would you like to make it so. Saying yes to this *does* populate the default applications with Firefox as the selected browser. It would be nice for this process to be smoother though and for Firefox to be something you can add without having to have opened it, or better yet, the default browser _by default_. 

---

As an aside this is my first issue on the project. I love what you have put together here and will be continuing to use Clear Linux, raising issues where I find them. 

Thank you for all the hard work!

**Comment by ahkok** [comment] 2019-05-25 21:26
This is an integration issue. @mrkz

**Comment by mrkz** [comment] 2019-06-11 15:40
@orsetto-bruno Hello, thanks for contributing with your bug report! :tada: 

This appears to be a duplicate of #410 , so I'm closing this issue to keep track of the previous report.

However, notice that this is a high impact for the desktop experience and I'm looking at fixing it soon.

**Closed by mrkz** 2019-06-11 15:40 UTC
Labels: bug, desktop, duplicate, high priority
