### ISSUE TITLE
[BBT][devpkg-open-iscsi]/usr/bin/ld: cannot find -liscsiusr

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1420] opened 2019-10-30 18:35 UTC
In build 31450, we have a regression for devpkg-open-iscsi, fail to compile test, looks like a missing binary

This is the error

 (in test file bat-devpkg-open-iscsi-pkgconfig-compile.t, line 13)
   `echo "int main(int argc, char **argv) { return 42; }" | gcc -x c $CFLAGS $pc_cflags $pc_libs -o foo - 2>&1' failed
 /usr/bin/ld: cannot find -liscsiusr
 collect2: error: ld returned 1 exit status

**Comment by phmccarty** [comment] 2019-10-31 00:31
This is not a regression, since it was also failing in build `31410` and likely earlier.

**Comment by phmccarty** [comment] 2020-01-08 18:59
This is an upstream bug.

**Comment by phmccarty** [comment] 2020-01-08 19:14
I submitted a PR upstream to fix, and I added this patch for open-isci. Should be fixed in build `32060` or newer.

**Comment by phmccarty** [comment] 2020-01-09 21:01
Fixed in release `32060`.

**Closed by phmccarty** 2020-01-09 21:01 UTC
Labels: bug
