### ISSUE TITLE
mono it's available in the bundle with a very old version 5.12 please update to latest (6.8.0 at today)

### ISSUE THREAD

**Issue by dorvan** [clearlinux/distribution#2032] opened 2020-06-20 11:08 UTC
mono it's available in the bundle with a very old version 5.12 please update to latest (6.8.0 at today)

**Comment by romulasry** [comment] 2020-06-20 20:53
https://github.com/mono/mono/releases

**Comment by thiagomacieira** [comment] 2020-06-23 18:32
We know, but Mono is really hard to update and we don't have the expertise. We're far more likely to simply remove it.

**Comment by dorvan** [comment] 2020-06-26 11:38
@thiagomacieira  you can start from gentoo specs for the package. but, a lot of projects ask for c# components, so seems can't be possible consider clear linux (both host or other roles) in this way.
what about the possibility to have dotnetcore as bundle?

**Comment by thiagomacieira** [comment] 2020-06-26 17:11
Sorry, we don't have the spare manpower to learn how to do this. I speak for experience, since I did try to add it a few years ago and gave up.

No, C# and Mono are just too alien for Linux. Please stick to regular languages.

**Comment by dorvan** [comment] 2020-08-24 08:57
> 
> 
> Sorry, we don't have the spare manpower to learn how to do this. I speak for experience, since I did try to add it a few years ago and gave up.
> 
> No, C# and Mono are just too alien for Linux. Please stick to regular languages.

Probably you does not monitor projects in github using C# on linux, and the work of .net core also. we use c# apps on linux since 2012 for business. end it's an increasing market especially related to opencv and IoT, and IIoT.... 
Alien? up to 2014 probably... Not Today.

**Comment by dorvan** [comment] 2020-08-24 08:58
> 
> 
> Still alien and doesn't change the fact we don't have the expertise to do this. Mono is just too complex to package for the little gain we have (not worth the effort/benefit ratio).

here the only Alien, seems your quote.

**Comment by mdhorn** [comment] 2020-11-16 23:17
This was a duplicate of https://github.com/clearlinux/distribution/issues/1779

**Closed by mdhorn** 2020-11-16 23:17 UTC
Labels: To Be Deprecated, package-update
