### ISSUE TITLE
VLC and MP4a codec

### ISSUE THREAD

**Issue by lsatenstein** [clearlinux/distribution#1617] opened 2020-01-02 16:53 UTC
I receive many mp4a files which, with alternative distributions, I am able to watch and play.

Not so with vlc and clear linux 

I am envoking vlc via firefox.

**Comment by thiagomacieira** [comment] 2020-01-02 19:38
We are unable to provide the MP4 codecs for software decoding in Clear. This is unfortunately not up for discussion.

Are you sure VLC is using hardware decoding for those files?

**Comment by ahkok** [comment] 2020-01-06 19:27
Please read the discussion on the forums (https://community.clearlinux.org/) for alternatives and explanation why some codecs are not provided (and won't be).

Closing this as this is a duplicate of several similar bugs.

**Closed by ahkok** 2020-01-06 19:27 UTC
Labels: bug
