### ISSUE TITLE
journalctl spammed by gnome-shell assertion

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#208] opened 2018-09-20 17:52 UTC
The output of journalctl is filled with entries like the one below.

```
Sep 20 10:49:57 cmdeoliv-mobl2 gnome-shell[1239]: g_interface_info_get_n_properties: assertion 'GI_IS_INTERFACE_INFO (info)' failed
```

**Comment by ahkok** [comment] 2018-09-20 17:57
Dupe of #202

**Closed by ahkok** 2018-09-20 17:57 UTC
Labels: bug, duplicate
