### ISSUE TITLE
Cannot login to any instance size other than a default one

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#68] opened 2018-05-17 23:50 UTC
Hi!

Looks like something fails in the recent AMI's initialization process. I cannot login to an EC2 instance of ClearLinux if I choose any alternative size, rather than the default one.

I created a new instance "m5.large" and included a (correct) public key. Instance started, but I cannot login via SSH. I'm getting asked for a password.

ssh -lclear -i ~/.ssh/id_rsa_moco 34.219.98.38 -v

OpenSSH_7.6p1, LibreSSL 2.6.2
debug1: Reading configuration data /Users/michalpurzynski/.ssh/config
debug1: /Users/michalpurzynski/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/Users/michalpurzynski/.ssh/ca538411bd196a94e48328a633ecec98f2b48eac" does not exist
debug1: Connecting to 34.219.98.38 [34.219.98.38] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/michalpurzynski/.ssh/id_rsa_moco type 0
debug1: key_load_public: No such file or directory
debug1: identity file /Users/michalpurzynski/.ssh/id_rsa_moco-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.5
debug1: match: OpenSSH_7.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 34.219.98.38:22 as 'clear'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp521
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp521 SHA256:aH5wjVrtyfSCQSxZEVxGyCX3s4ZTarMw4U1L8+CVNbw
debug1: Host '34.219.98.38' is known and matches the ECDSA host key.
debug1: Found key in /Users/michalpurzynski/.ssh/known_hosts:80
Host key fingerprint is SHA256:aH5wjVrtyfSCQSxZEVxGyCX3s4ZTarMw4U1L8+CVNbw
+---[ECDSA 521]---+
|       o=B*  .o  |
|       +++ . o.. |
|      o + = *  . |
|       = X X oE  |
|      + S & +    |
|     o = X B     |
|      o o * .    |
|       .   .     |
|                 |
+----[SHA256]-----+
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:GuA89IcigEQvN5POkFjBdgpct3OqU7sj68Yg2twFXHM /Users/michalpurzynski/.ssh/id_rsa_moco
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Offering public key: RSA SHA256:tFv0xOhr8NTY9wdkzdn4p5rZGw1Q5I15xhGnEXtXLY0 
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Offering public key: RSA SHA256:Fphv2xpIiMFX21BPkZXyJHzYwQrZpHOvmxD8LO6vLt0 
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
Password: 

I tried with a default instance size and was able to log in.

**Comment by bryteise** [comment] 2018-05-17 23:54
@ahkok This makes me wonder a little more about https://github.com/clearlinux-pkgs/micro-config-drive/blob/master/f.patch because as far as I have been able to verify when doing the Oracle cloud work, the ssh-authorized-keys only works at the top level.

**Comment by mpurzynski** [comment] 2018-05-18 00:06
I detached the root volume from the affected instance and reattached it to another (working) instance, for inspection.
Looks like /home is empty and the clear user does not exist.

May 17 23:57:23 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[167]: pam_unix(sshd:auth): check pass; user unknown

More details



journalctl -l | egrep ssh
May 17 23:44:41 clr-ec23bcc34025d3061dbfd2d543062f48 ssh-keygen[132]: ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
May 17 23:45:28 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: Created slice system-sshd.slice.
May 17 23:45:29 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[6330]: Invalid user clear from 63.245.222.198 port 19526
May 17 23:45:29 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[6330]: Postponed keyboard-interactive for invalid user clear from 63.245.222.198 port 19526 ssh2 [preauth]
May 17 23:45:45 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[6330]: Connection closed by invalid user clear 63.245.222.198 port 19526 [preauth]
May 17 23:48:57 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[6336]: Invalid user clear from 63.245.222.198 port 3439
May 17 23:48:57 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[6336]: Postponed keyboard-interactive for invalid user clear from 63.245.222.198 port 3439 ssh2 [preauth]
May 17 23:49:14 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[6336]: Connection closed by invalid user clear 63.245.222.198 port 3439 [preauth]
May 17 23:54:46 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: Removed slice system-sshd.slice.
May 17 23:57:03 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: Created slice system-sshd.slice.
May 17 23:57:04 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[165]: Invalid user clear from 63.245.222.198 port 48722
May 17 23:57:04 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[165]: Postponed keyboard-interactive for invalid user clear from 63.245.222.198 port 48722 ssh2 [preauth]
May 17 23:57:23 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[167]: pam_unix(sshd:auth): check pass; user unknown
May 17 23:57:23 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[167]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=63.245.222.198
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[165]: error: PAM: Authentication failure for illegal user clear from 63.245.222.198
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[165]: Failed keyboard-interactive/pam for invalid user clear from 63.245.222.198 port 48722 ssh2
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[165]: Postponed keyboard-interactive for invalid user clear from 63.245.222.198 port 48722 ssh2 [preauth]
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[194]: pam_unix(sshd:auth): conversation failed
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[194]: pam_unix(sshd:auth): auth could not identify password for [clear]
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 sshd[194]: error: ssh_msg_send: write
May 17 23:57:26 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: Removed slice system-sshd.slice.

**Comment by mpurzynski** [comment] 2018-05-18 00:10
Extracted the full journalctl -l

Let me know if you want it.

**Comment by bryteise** [comment] 2018-05-18 00:13
Ah seeing the logs for ucd-aws.service and ucd.service would probably be quite helpful.

**Comment by mpurzynski** [comment] 2018-05-18 00:53
[clearlinuxawsfails.txt](https://github.com/clearlinux/distribution/files/2015109/clearlinuxawsfails.txt)

Just in case, the entire thing.

**Comment by mpurzynski** [comment] 2018-05-18 00:55
Juicy pieces

May 17 23:44:40 clr-ec23bcc34025d3061dbfd2d543062f48 ucd[138]: [0.677478] disk: Device wiht label 'config-2' not found!
May 17 23:44:40 clr-ec23bcc34025d3061dbfd2d543062f48 ucd[138]: [0.677487] openstack: config drive was not found
May 17 23:44:40 clr-ec23bcc34025d3061dbfd2d543062f48 ucd[138]: [0.684092] Checking disk /dev/nvme0n1

(...)

May 17 23:44:48 clr-ec23bcc34025d3061dbfd2d543062f48 ucd-aws[186]: parse_headers(): No such file or directory
May 17 23:44:48 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: ucd-aws.service: Main process exited, code=exited, status=1/FAILURE
May 17 23:44:48 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: ucd-aws.service: Unit entered failed state.
May 17 23:44:48 clr-ec23bcc34025d3061dbfd2d543062f48 systemd[1]: ucd-aws.service: Failed with result 'exit-code'.

**Comment by ahkok** [comment] 2018-05-21 20:35
`May 17 23:44:48 clr-ec23bcc34025d3061dbfd2d543062f48 ucd-aws[186]: parse_headers(): No such file or directory`

is the suspect line

**Comment by ahkok** [comment] 2018-05-21 20:36
@bryteise the last AWS instance I brought up used this format properly (`t2.micro`) so we know that works and isn't the cause.

**Comment by bryteise** [comment] 2018-05-26 15:08
Sadly I haven't gotten to look in AWS yet but ucd-aws is looking for the public key here:

169.254.169.254/latest/meta-data/public-keys/0/openssh-key

and the user configuration here:

169.254.169.254/latest/user-data

Both of these locations are documented in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html so maybe the latest folder structure has changed for all the other instances but the default though that seems very odd.

@ahkok ^

**Comment by ahkok** [comment] 2018-09-05 21:39
Issue finally root caused. I will be implementing an actual fix in the next 2 days.

**Comment by ahkok** [comment] 2018-09-06 16:38
The fix will be in `micro-config-drive-33`.

**Comment by ahkok** [comment] 2018-09-06 16:40
Summary of root cause: Some HTTP servers offering the `user-data` and SSH keys do not support `keep-alive`. We assumed they did, because the instances where we developed on early on always worked. The code now ignores keepalive entirely and reopens the socket for the second data request.

**Closed** 2018-10-29 18:03 UTC
Labels: bug

**Comment by tqh** [comment] 2019-05-16 11:21
Still seeing this on AWS in eu-west-1 on a t3-micro, have you updated marketplace image (Latest Version: 28820) ?
