### ISSUE TITLE
rtc_cmos 00:00: nvmem registration failed

### ISSUE THREAD

**Issue by igorgoroshit** [clearlinux/distribution#129] opened 2018-07-26 15:11 UTC
Failed to boot on SYS-5028TK-HTR-NF9 (XEON PHI) 
------------------------

### What is the issue type?

* [x] Bug report
* [ ] Enhancement request

### Describe the problem

Clear Release
23950

System 
SYS-5028TK-HTR-NF9.

CPU
XEON PHI 7290

Got the following error:
rtc_cmos 00:00: nvmem registration failed

We checked this on other systems with xeon phis 72xx
and on all systems with xeon phi the error is the same.

**Comment by bryteise** [comment] 2018-07-26 17:47
@miguelinux I'm hoping you might be able to get access to this hardware. @bwarden Might also have a shot.

**Comment by bwarden** [comment] 2018-07-26 18:11
This looks like the same issue and system as someone in external IRC. I worked with them to debug for a while, narrowed it down to a delay after `random: crng init done`, then everything started working and the problem was no longer reproducible.

**Comment by bwarden** [comment] 2018-07-26 18:12
This was when booting the installer, by the way.

**Comment by bryteise** [comment] 2018-07-26 18:16
Ah okay, yes just looked at IRC. I guess we'll close this for now and wait until the 2nd PHI gets tested to see if this opens back up.

**Closed by bryteise** 2018-07-26 18:16 UTC

**Comment by mmetak** [comment] 2018-08-03 14:09
Hi. I'm also getting this error on archlinux running linux-clear (packaged clr kernel for archlinux).  
Googling lead me to find that it's because `CONFIG_RTC_NVMEM` is not enabled?

**Comment by bwarden** [comment] 2018-08-03 16:07
@mmetak If you're just getting the nvmem warning, and not failing to boot, then this issue is unrelated.
