### ISSUE TITLE
Setting for $PATH unconditionally wiped in interactive subshell

### ISSUE THREAD

**Issue by chipb** [clearlinux/distribution#1033] opened 2019-07-19 22:50 UTC
When working in a development shell, I often set a local value for `$PATH` to point at tools for the project at the time. Something like a manual `export PATH="/path/to/foo:$PATH"` (or even a `virtualenv` activate) while I'm in that shell.

On occasion, I also push my current state on the stack by manually launching a subshell: `bash`.

My expectation would be that `$PATH` in this child still contains the entries that were set in the parent shell, but I found that they are not preserved. From cursory look, I see that `/usr/share/defaults/etc/profile` gets sourced and will unconditionally reset `$PATH` right away. Indeed, there's a whole slew of variables getting clobbered in this file. This seems like very surprising behavior if nothing else.

Am I missing customization that would avoid this? Can the `/usr/share/defaults/etc/profile` file be reworked to both accomplish what it's meant to do and not surprise me?

**Comment by chipb** [comment] 2019-07-19 22:54
I can force a login shell so at least the shell will source my shell startup files, of course, but project-specific environment setup doesn't always belong in there.

**Comment by chaoyi** [comment] 2019-09-15 03:05
PATH set in `~/.config/environment.d/xx.conf` will also be reset by `/usr/share/defaults/etc/profile`.  See https://bugs.archlinux.org/task/47884 (/etc/profile should check whether PATH is empty before overwriting it).

Please consider Fedora's `pathmunge` solution.

**Comment by citron** [comment] 2019-10-09 09:25
I do confirm this bug :(

**Comment by lebensterben** [comment] 2019-10-22 23:30
This problem is due to that `/usr/share/defaults/etc/profile` is sourced for all interactive shells, and it will indiscriminately wipe out `$PATH` before setting it.

It might be necessary to do the wiping for **login shells**, because not correctly setting `$PATH` may result in unexpected behaviours. But for non-login, interactive shell it shall not do that.

I sent a huge [patch](https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/2HRCXHZD22BHIGBJDQRUSBAIUQFDGBRX/) which may solve this by only sourcing it for login-shells.

**Comment by puneetse** [comment] 2020-01-24 22:54
Linking to https://github.com/clearlinux/distribution/issues/742

**Comment by rossburton** [comment] 2020-03-03 21:15
Fixed in filesystem-3.0.14-202.

**Closed by rossburton** 2020-03-03 21:15 UTC
Labels: bug
