### ISSUE TITLE
minor issue: Typos in configure flags of `gdb`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#2307] opened 2021-03-14 20:55 UTC
First, I think the first optarg to `target` should be `%{_arch}-unknown-linux-gnu` so that `enable-targets` and `target` options matches.
```
--enable-targets=%{_arch}-unknown-linux-gnu,%{_arch}-generic-linux-gnu
--target=%{_arch}-generic-linux-gnu %{_arch}-generic-linux-gnu
```

Second, `--with-python=yes` appeared twice.

ref: https://github.com/clearlinux-pkgs/gdb/blob/626b103356522005abbd1adaa04af2e8828932cf/configure#L1

**Comment by phmccarty** [comment] 2021-03-16 23:54
Thanks. I'll take a look.

**Comment by phmccarty** [comment] 2021-03-17 00:12
The current state is a little confusing...

1. In the `%configure` macro expansion, the build/host/target are `--build=x86_64-generic-linux-gnu --host=x86_64-generic-linux-gnu --target=x86_64-clr-linux-gnu`
2. In configure, we add `--target=x86_64-generic-linux-gnu`, which (IIUC) overrides the previous value of `x86_64-clr-linux-gnu`.
3. There is an additional non-flag argument `x86_64-generic-linux-gnu` passed to the script, but I think that's a no-op.
4. We pass `--enable-targets=x86_64-unknown-linux-gnu,x86_64-generic-linux-gnu`.

My initial assessment is that the `--target` and `--enable-targets` values need not match, because `--enable-targets` specifies "alternative target configurations", so it seems that `--enable-targets=x86_64-unknown-linux-gnu` would be most appropriate.

I will test more carefully to confirm the above.

**Comment by phmccarty** [comment] 2021-03-17 00:13
And we will remove the duplicate `--with-python=yes` as well. Nothing to test there ;-)

**Comment by phmccarty** [comment] 2021-03-17 00:43
Okay, I integrated some changes to the gdb package. The duplicate `--with-python=yes` flag is removed and I addressed the other problems described two comments ago. GDB's configuration is confirmed to be the same as before.

**Comment by phmccarty** [comment] 2021-03-19 18:37
Fixed in release 34420.

**Closed by phmccarty** 2021-03-19 18:37 UTC
Labels: bug
