### ISSUE TITLE
swupd update is returning a 255 value on successful update

### ISSUE THREAD

**Issue by lsandov1** [clearlinux/distribution#1128] opened 2019-08-14 16:26 UTC
Fetch-run latest `clearlinux` container, then run `swudp update`. Log indicates update was successful but return code is `255`. This is causing issues when building a docker image base on `clearlinux`, 

Full log:

```
$ docker run -it clearlinux bash
Unable to find image 'clearlinux:latest' locally
latest: Pulling from library/clearlinux
35f41134e2e6: Pull complete 
Digest: sha256:06c4124b80465f3bba66efe670af766a7e8fede81515296aa5a3f08ef1493643
Status: Downloaded newer image for clearlinux:latest
root@690ec2d5ec97/ # swupd update
Update started.
Preparing to update from 30730 to 30760
Downloading packs for:
 - libstdcpp
 - os-core
 - os-core-plus
 - os-core-update
	...100%
Finishing packs extraction...

Statistics for going from version 30730 to version 30760:

    changed bundles   : 4
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 26
    new files         : 3
    deleted files     : 0

No extra files need to be downloaded
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts
Update took 8.2 seconds, 0 MB transferred
Update successful. System updated from version 30730 to version 30760
root@690ec2d5ec97/ # echo $?
255
```

**Comment by hnanni** [comment] 2019-08-14 16:52
I think you need to add "-b" to the swup update command

-b, --no-boot-update    Do not install boot files to the boot partition (containers)

**Comment by lsandov1** [comment] 2019-08-14 17:01
`-b` is a shortcut for `--no-boot-update`. what would that make a difference?

**Comment by hnanni** [comment] 2019-08-14 17:05
I mean, add "-b"
and then just pasted the relevant line of  swupd update --help

**Comment by lsandov1** [comment] 2019-08-14 17:11
neither `-b` not `--no-boot-update` solves the issue

```
$ docker run -it clearlinux bash
root@338e65140d6b/ # swupd update -b
Update started.
Preparing to update from 30730 to 30760
Downloading packs for:
 - libstdcpp
 - os-core
 - os-core-plus
 - os-core-update
	...100%
Finishing packs extraction...

Statistics for going from version 30730 to version 30760:

    changed bundles   : 4
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 26
    new files         : 3
    deleted files     : 0

No extra files need to be downloaded
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts
Update took 6.7 seconds, 0 MB transferred
Update successful. System updated from version 30730 to version 30760
root@338e65140d6b/ # echo $?
255
```

**Comment by ahkok** [comment] 2019-08-14 19:56
@otaviobp can you confirm - I think `255` is a swupd update trigger failure, right?

**Comment by phmccarty** [comment] 2019-08-15 19:04
Pretty sure this is a duplicate of https://github.com/clearlinux/swupd-client/issues/1068

**Closed by phmccarty** 2019-08-15 19:04 UTC
Labels: bug, new
