### ISSUE TITLE
gnupg crashes when encrypting

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#127] opened 2018-07-24 21:41 UTC
Same test on a Fedora passes.

```
$ gpg --full-gen-key
gpg (GnuPG) 2.2.9; Copyright (C) 2018 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: directory '/home/c/.gnupg' created
gpg: keybox '/home/c/.gnupg/pubring.kbx' created
Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection? 1
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (2048) 
Requested keysize is 2048 bits   
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0) 1y
Key expires at Wed 24 Jul 2019 02:29:07 PM PDT
Is this correct? (y/N) y
                        
GnuPG needs to construct a user ID to identify your key.

Real name: Test Name
Email address: test@example.com
Comment: Test                  
You selected this USER-ID:
    "Test Name (Test) <test@example.com>"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? O
gpg: invalid item 'S2' in preference string          
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: invalid item 'S2' in preference string
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: /home/c/.gnupg/trustdb.gpg: trustdb created
gpg: key 37579C91FBE85F88 marked as ultimately trusted
gpg: directory '/home/c/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/home/c/.gnupg/openpgp-revocs.d/F8FCAA593A0762AEA695D3D537579C91FBE85F88.rev'
public and secret key created and signed.

pub   rsa2048 2018-07-24 [SC] [expires: 2019-07-24]
      F8FCAA593A0762AEA695D3D537579C91FBE85F88
uid                      Test Name (Test) <test@example.com>
sub   rsa2048 2018-07-24 [E] [expires: 2019-07-24]

$ gpg --encrypt --recipient test@example.com 
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2019-07-24
gpg: Ohhhh jeeee: ... this is a bug (seskey.c:50:make_session_key)
Aborted (core dumped)
```

**Comment by VictorRodriguez** [comment] 2018-08-05 02:04
confirmed i can reproduce : 

vrodri3@pnp-xeon-server-1 ~ $ gpg --encrypt --recipient vm.rod25@gmail.com
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2019-08-05
gpg: Ohhhh jeeee: ... this is a bug (seskey.c:50:make_session_key)
Aborted (core dumped)

**Comment by iphutch** [comment] 2018-10-29 17:16
@bwarden any progress on this issue?

**Comment by bwarden** [comment] 2018-11-05 21:15
Fixed in release 26080.

- Re-enabled DES/3DES support in libgcrypt, and added warnings when it's used in gpg
- GPG now sets reasonable key/hash prefs by default, instead of 3DES/SHA1 only:
```
     Cipher: AES256, 3DES
     Digest: SHA512, SHA384, SHA256, SHA1
```

**Closed by bwarden** 2018-11-05 21:15 UTC
Labels: bug

**Comment by mrkz** [comment] 2018-11-12 21:58
@bwarden I think we can close this now?

**Comment by probonopd** [comment] 2018-11-12 22:02
Looks like this is no longer an issue, seems to work for me:

```
user@host ~ $ gpg --full-gen-key
gpg (GnuPG) 2.2.11; Copyright (C) 2018 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection? 1
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (2048) 
Requested keysize is 2048 bits   
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0) 1y
Key expires at Tue 12 Nov 2019 10:00:18 PM UTC
Is this correct? (y/N) y
                        
GnuPG needs to construct a user ID to identify your key.

Real name: Test Name
Email address: test@example.com
Comment: Test                  
You selected this USER-ID:
    "Test Name (Test) <test@example.com>"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? O
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: key 42C144F46CB9FC2C marked as ultimately trusted
gpg: directory '/home/user/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/home/user/.gnupg/openpgp-revocs.d/1CBDF9F4148973422A3E6C4142C144F46CB9FC2C.rev'
public and secret key created and signed.

pub   rsa2048 2018-11-12 [SC] [expires: 2019-11-12]
      1CBDF9F4148973422A3E6C4142C144F46CB9FC2C
uid                      Test Name (Test) <test@example.com>
sub   rsa2048 2018-11-12 [E] [expires: 2019-11-12]
```

```
user@host ~ $ cat /etc/os-release 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26220
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
