### ISSUE TITLE
Unable to use system that has an encrypted / partition

### ISSUE THREAD

**Issue by Mountainerd** [clearlinux/distribution#253] opened 2018-10-31 03:54 UTC
Using the same installer USB drive, on most devices, it installs as expected. On a couple devices (both Dell XPS 13 from 2013), it installs, but it doesn't install the bootloader. When I manually add a boot entry for Clear, it gets to the prompt to unlock LUKS, but then hangs. 

1. Install Clear choosing the manual partitioning
2. Add /boot, swap, / and select encrypt / partition
3. Install will complete, reboot, and see above mentioned behavior.

What I would expect is that after installation completes, I reboot and:
1. Clear boots automatically
2. It prompts me for my password to unlock the / partition
3. It completes booting into user environment (I tried both minimal installation and GNOME installation; didn't change symptoms)

 - Clear Linux OS version: Latest installer
 - Bundles: Default installation

**Comment by bryteise** [comment] 2018-10-31 17:59
@Mountainerd as @josuedhg set this up initially I expect he'll be the person to best look into the problem.

**Comment by miguelinux** [comment] 2018-10-31 18:00
What do you see when you reboot the XPS after install Clear Linux?

How do you add the missing entry to the boot loader?

To boot to an encrypted portion CL uses initrd that the installer should
setup.

**Comment by josuedhg** [comment] 2018-10-31 19:46
is it avoiding just the systemd entry or the whole systemd I mean what is in the boot partition? this could be an issue in clr-boot-manager

regarding the hang: if u, this is happening just when u take some time to write the passphrase or everytime, if  removi console=/dev/ttyS0 in the cmdline are u able to see an emergency shell (this is an issue about the mount timeout and I am working on it)

**Comment by Mountainerd** [comment] 2018-10-31 21:51
@miguelinux: If I do the install and reboot, nothing. It'll bring up a menu like I hit F12 to look at boot options. I then go into BIOS, go add a UEFI boot entry pointing to (I think, going from memory) BOOTX64.efi. When I reboot then, it goes to the prompt asking for my unlock password (single line across the top of the screen). I enter password and then it does nothing and I have to hard reset/shutdown.

@josuedhg I tried your suggestion with wdouglas on IRC a couple nights ago and was able to get to emergency shell. I don't remember offhand but it was barking about something like "failed to start cryptography setup". 

Would it help to provide a screenshot of what I get now? I'll be at the computer in about an hour or so.

**Comment by neben** [comment] 2018-11-15 16:37
Same problem here, I get the prompt to enter the passphrase but there is no reaction after entering it. I tried to enter it quickly after the prompt appears, but to no avail. Not sure if it even recognizes the keyboard (tried two different ones, they both work in the BIOS and also the installer). I used installer version 26280 and the hardware is a new Intel NUC.

**Comment by josuedhg** [comment] 2018-11-15 17:34
@Mountainerd are u using a custom kernel, that probably dont have the dm-crypt module built-in?

**Comment by josuedhg** [comment] 2018-11-15 17:36
@neben did u see the same message about cryptsetup when u disable the ttyS0, if not it is a known issue and I am working on fix it, if u saw that message is the same issue and I will also work on it

**Comment by neben** [comment] 2018-11-16 12:55
@josuedhg The issue was with the attached keyboards. It works during during pre-boot (I can enter BIOS etc), and it works once the system is booted up. It does not work, however, during the LUKS prompt, so probably the initrd (?) is missing some drivers. Both a Logitech wireless keyboard with a USB dongle (K400r) and an Apple Keyboard do not work during this phase (I can provide more info if needed). I finally was able to enter the passphrase with a third keyboard.

And yes, if I don't enter the passphrase shortly after booting, there will be a timeout. Thanks for your efforts!

**Comment by Mountainerd** [comment] 2018-11-21 05:58
@josuedhg Nope, nothing custom, just doing a straight-up installation. The issue you mentioned to @neben is the same I experienced. I disabled the tty and saw it complaining about the same. When I initially had this issue, I hopped on IRC and tried a few things and one of the errors I saw pop up after entering my password was something like "failed to start cryptography setup". 

Thank you for taking a look at this further!

**Comment by Mountainerd** [comment] 2018-12-03 07:36
I just tried another install on the same hardware with the latest installer and it kernel panics now. If it helps, I [took a photo](https://photos.app.goo.gl/gNSd16Wx5muwX4Te8) of what I get now and shared it instead of trying to type out all the text here.

**Comment by mdhorn** [comment] 2018-12-05 18:13
@Mountainerd There was a new release of clr-init which handles the encrypted file systems at boot release in Clear Linux OS 26670 (see https://github.com/clearlinux/clr-init/issues/1)
This resolved the problem I was seeing with hang at boot.

**Comment by tpleavitt** [comment] 2019-03-19 20:39
@Mountainerd , @neben  are you still experiencing this issue?

**Comment by Mountainerd** [comment] 2019-03-24 22:32
Hi @tpleavitt -- Thank you for the follow-up. I haven't tried recently as I had a requirement for FDE and only one laptop. I now have others but haven't had the time to check again. I'll give it a look in the next couple days and get back to you.

**Comment by Mountainerd** [comment] 2019-04-03 03:06
@tpleavitt Hey Tom, I installed the latest version of CL on my work laptop today with an encrypted root partition and everything came up fine!

**Comment by tpleavitt** [comment] 2019-04-03 15:22
Awesome!  Thanks @Mountainerd , I'll go ahead and close this issue then

**Closed by tpleavitt** 2019-04-03 15:22 UTC
Labels: bug

**Comment by neben** [comment] 2019-04-22 12:30
I'm pretty sure I still have the timeout issue, if I don't enter the password within a certain period of time. Or would I have to reinstall CL for this?

And regarding supported keyboards for the passphrase entry: The Logitech device works now, but the Apple keyboard still does not (see my previous comment https://github.com/clearlinux/distribution/issues/253#issuecomment-439384660).

**Comment by bkdwt** [comment] 2019-07-08 05:23
This problem persist in the last Clear Linux build. I can't into login because I put the Luks password and nothing happens.

**Comment by jairglez** [comment] 2019-07-12 23:46
@neben there has been changes in the initrd configuration in later Clear Linux releases. I wasn't able to reproduce the timeout issue after waiting more than 10 minutes before entering the LUKS password. Do you continue experiencing issues?

**Comment by jairglez** [comment] 2019-07-12 23:46
@bkdwt thanks for contacting us. Could you please let us know what keyboard configuration are you using?

**Comment by neben** [comment] 2019-08-22 21:36
> @neben there has been changes in the initrd configuration in later Clear Linux releases. I wasn't able to reproduce the timeout issue after waiting more than 10 minutes before entering the LUKS password. Do you continue experiencing issues?

The timeout issue seems to be fixed now, but I still can't use a regular mac keyboard to unlock the disk.

**Comment by miguelinux** [comment] 2019-08-23 21:02
@neben Can you open an issue regarding **missing mac keyboard driver in initrd**?

meanwhile if you add a external keyboard you can type in your LUKS password.

Can you share your `lsmod` output, when you are in CL, please 

I'll add one apple driver but do not know if something more is missing.

**Comment by neben** [comment] 2019-08-28 13:28
> @neben
> Can you verify with **CL 30860**, it includes the changes with `hid-apple` module

@miguelinux I tried with CL 30870 and it works, thanks!

One thing I noticed was that, after mistyping the passphrase twice, I wasn't asked for a third time and had to hard reset the machine. IIRC this used to be the case (i.e., max three attempts), but I'm not sure.

Do you still need the `lsmod` output? If so, any particular part?

**Comment by miguelinux** [comment] 2019-09-02 16:08
@neben  if it works, then `lsmod`output is not needed. 

The initrd with LUKS enabled asked for only 3 times for the password for security. 

Let's us know if you have another issue by opening a  **new GitHub issue**.
