### ISSUE TITLE
pahole update to at least version 1.13

### ISSUE THREAD

**Issue by vcgomes** [clearlinux/distribution#1806] opened 2020-03-05 01:42 UTC
To be able to compile the Linux kernel with the option CONFIG_DEBUG_INFO_BTF enabled, `pahole` at least version 1.13 is necessary. The version in Clear is 1.12. The upstream version is 1.16.

The kernel compilation fails with the following message:
```
BTF: .tmp_vmlinux.btf: pahole version v1.12 is too old, need at least v1.13
Failed to generate BTF for vmlinux
Try to disable CONFIG_DEBUG_INFO_BTF
```

**Comment by thiagomacieira** [comment] 2020-03-05 02:10
Last I checked, pahole failed to compile.

**Comment by thiagomacieira** [comment] 2020-03-05 02:17
```
-- Could NOT find libebl library
CMake Error at cmake/modules/FindDWARF.cmake:102 (message):
  Could NOT find some ELF and DWARF libraries, please install the missing
  packages
```

This is caused by libebl no longer existing in the elfutils package. See https://github.com/drepper/elfutils/commit/b833c731359af12af9f16bcb621b3cdc170eafbc.

I contacted @acmel when this happened but received no reply.

**Comment by thiagomacieira** [comment] 2020-03-05 02:23
Backported https://github.com/acmel/dwarves/commit/de84ae36c7388f8d124fbe39b8073ab72021ad48.

Error now:
```
CMake Error at CMakeLists.txt:55 (message):
  The submodules were not downloaded! GIT_SUBMODULE was turned off or failed.
  Please update submodules and try again.
```

```cmake
 if(NOT EXISTS "${PROJECT_SOURCE_DIR}/lib/bpf/src/btf.h")
	message(FATAL_ERROR "The submodules were not downloaded! GIT_SUBMODULE was turned off or failed. Please update submodules and try again.")
endif()
```

The file `lib/bpf/src/btf.h` does not exist in the tarball.

**Comment by thiagomacieira** [comment] 2020-03-05 02:33
Doing as Fedora did and download the libbpf sources (https://github.com/libbpf/libbpf/tree/4d86cae4f09f3db67d6d0543f94546f85f7b2c38). This worked.

Kojiing.

**Comment by thiagomacieira** [comment] 2020-03-05 02:35
Will be in tomorrow's build.

**Closed by thiagomacieira** 2020-03-05 02:35 UTC
Labels: new, package-update
