### ISSUE TITLE
why so many WARNING during flatpak install?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1230] opened 2019-09-16 10:18 UTC
```
android@clr~ $ flatpak install com.viber.Viber
Looking for matches…
Found similar ref(s) for ‘com.viber.Viber’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Required runtime for com.viber.Viber/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/18.08) found in remote flathub
Do you want to install it? [Y/n]: y

com.viber.Viber permissions:
    ipc      network      pulseaudio      wayland      x11      devices      file access [1]      dbus access [2]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-pictures, xdg-videos, ~/.ViberPC:create
    [2] org.freedesktop.Notifications, org.kde.StatusNotifierWatcher


        ID                                               Arch              Branch            Remote             Download
 1. [—] org.freedesktop.Platform                         x86_64            18.08             flathub              917.5 kB / 295.2 MB
 2. [ ] org.freedesktop.Platform.Locale                  x86_64            18.08             flathub            < 315.9 MB (partial)
 3. [ ] org.gtk.Gtk3theme.Materia-compact                x86_64            3.22              flathu        ID                                       Arch      Branch   Remote    Download
 1. [✓] org.freedesktop.Platform                 x86_64    18.08    flathub   281.2 MB / 295.2 MB
 2. [✓] org.freedesktop.Platform.Locale          x86_64    18.08    flathub    17.3 kB / 315.9 MB
 3. [✓] org.gtk.Gtk3theme.Materia-compact        x86_64    3.22     flathub    77.6 kB / 71.8 kB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel     x86_64    18.08    flathub     1.8 MB / 1.8 MB
 5. [✓] org.freedesktop.Platform.html5-codecs    x86_64    18.08    flathub     3.2 MB / 3.3 MB
 6. [✓] com.viber.Viber                          x86_64    stable   flathub    95.7 MB / 95.7 MB

Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-I1W47Z/org.freedesktop.Platform-7LGV7Z: Creating repo: renameat: Software caused connection abort
Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-I1W47Z/org.freedesktop.Platform.Locale-C6257Z: Creating repo: renameat: Software caused connection abort
Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-I1W47Z/org.gtk.Gtk3theme.Materia-compact-O1FR7Z: Creating repo: renameat: Software caused connection abort
Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-I1W47Z/org.freedesktop.Platform.VAAPI.Intel-AUQ67Z: Creating repo: renameat: Software caused connection abort
Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-I1W47Z/org.freedesktop.Platform.html5-codecs-GK147Z: Creating repo: renameat: Software caused connection abort
Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-I1W47Z/com.viber.Viber-LBIX7Z: Creating repo: renameat: Software caused connection abort
Installation complete.
android@clr~ $ 

```
but i am running viber finally.

**Comment by ahkok** [comment] 2019-09-16 17:46
duplicate of #1016

**Closed by ahkok** 2019-09-16 17:46 UTC
Labels: bug
