### ISSUE TITLE
On KDE Plasma, Firefox has no icon and and broken name/description on favourites menu.

### ISSUE THREAD

**Issue by yerbestpal** [clearlinux/distribution#873] opened 2019-06-11 11:31 UTC
I also remember it never had an icon on Gnome.
![clear2](https://user-images.githubusercontent.com/15250241/59268500-bdb60c00-8c44-11e9-9cdf-cb5182bb9681.png)

**Edit:** After having just making this report, I have noticed Thunderbird also does not have an icon. This is also in the screenshot.

**Comment by anselmolsm** [comment] 2019-06-11 16:36
Duplicate of #681 about Firefox, #666 about Thunderbird. Thanks for reporting, we'll track the work on those issues reported previously.

**Closed by anselmolsm** 2019-06-11 16:36 UTC
Labels: bug, new
