### ISSUE TITLE
No Sound on Install

### ISSUE THREAD

**Issue by rbharathkumar** [clearlinux/distribution#375] opened 2019-01-23 08:07 UTC
Dear Team,
I am trying the clearlinux OS inside a VM as a guest.
Used the installer with default settings. The system boots to a Gnome environment, but I do not have any sound output. 
1. The Sound settings in the Settings page shows Dummy Output only.
2. The alsa-utils bundle is installed.
3. The alsamixer (On pressing F6) shows my intel sound card but not as default.
4. I have also checked for MM in the alsamixer menu.
5. I have also tried installing the PulseEffects flatpak and tried various settings on the /etc/asound.conf file.
6. I have googled on this. Suggestions to perform alsa force-reload is not possible since alsa command is not available.
7. Other suggestions to modify files in /etc/modprod.d is also not working.
8. Please find my other details.
   Host: Manjaro KDE - Stable Branch.
   Guest: Intel Clear Linux - the software is up to date.
   VBox version: 6.0.0 - Extension packs installed on Host.

Kindly help.
Thank you.

**Comment by gvancuts** [comment] 2019-01-23 10:14
Can you confirm what audio settings you have set for your VM in VirtualBox (https://www.virtualbox.org/manual/ch03.html#settings-audio)?

What do these return in your Clear Linux guest?
```
lspci
aplay -l
pactl list cards
```

**Comment by rbharathkumar** [comment] 2019-01-23 18:01
Thank you very much for your response.
Please find the requested details below.

Host Audio Driver	: PulseAudio
Audio Controller	: Intel HD Audio controller,
Enable Audio Output	: Enabled.
Enable Audio Input	: Enabled.

I also have Solus installed as a guest using the same setup. No issues there.

```
@clearlinux ~ $ lspci | grep Audio
00:05.0 Audio device: Intel Corporation 82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller (rev 01)
```

```
@clearlinux ~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Intel [HDA Intel], device 0: Generic Analog [Generic Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Intel [HDA Intel], device 1: Generic Digital [Generic Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

```
@clearlinux ~ $ pactl list cards
Card #0
	Name: alsa_card.pci-0000_00_05.0
	Driver: module-alsa-card.c
	Owner Module: 6
	Properties:
		alsa.card = "0"
		alsa.card_name = "HDA Intel"
		alsa.long_card_name = "HDA Intel at 0xf0424000 irq 21"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:05.0"
		sysfs.path = "/devices/pci0000:00/0000:00:05.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.product.id = "2668"
		device.form_factor = "internal"
		device.string = "0"
		device.description = "Built-in Audio"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Profiles:
		input:analog-stereo: Analog Stereo Input (sinks: 0, sources: 1, priority: 65, available: yes)
		input:iec958-stereo: Digital Stereo (IEC958) Input (sinks: 0, sources: 1, priority: 55, available: yes)
		output:analog-stereo: Analog Stereo Output (sinks: 1, sources: 0, priority: 6500, available: yes)
		output:analog-stereo+input:analog-stereo: Analog Stereo Duplex (sinks: 1, sources: 1, priority: 6565, available: yes)
		output:analog-stereo+input:iec958-stereo: Analog Stereo Output + Digital Stereo (IEC958) Input (sinks: 1, sources: 1, priority: 6555, available: yes)
		output:analog-surround-21: Analog Surround 2.1 Output (sinks: 1, sources: 0, priority: 1300, available: yes)
		output:analog-surround-21+input:analog-stereo: Analog Surround 2.1 Output + Analog Stereo Input (sinks: 1, sources: 1, priority: 1365, available: yes)
		output:analog-surround-21+input:iec958-stereo: Analog Surround 2.1 Output + Digital Stereo (IEC958) Input (sinks: 1, sources: 1, priority: 1355, available: yes)
		output:analog-surround-40: Analog Surround 4.0 Output (sinks: 1, sources: 0, priority: 1200, available: yes)
		output:analog-surround-40+input:analog-stereo: Analog Surround 4.0 Output + Analog Stereo Input (sinks: 1, sources: 1, priority: 1265, available: yes)
		output:analog-surround-40+input:iec958-stereo: Analog Surround 4.0 Output + Digital Stereo (IEC958) Input (sinks: 1, sources: 1, priority: 1255, available: yes)
		output:analog-surround-41: Analog Surround 4.1 Output (sinks: 1, sources: 0, priority: 1300, available: yes)
		output:analog-surround-41+input:analog-stereo: Analog Surround 4.1 Output + Analog Stereo Input (sinks: 1, sources: 1, priority: 1365, available: yes)
		output:analog-surround-41+input:iec958-stereo: Analog Surround 4.1 Output + Digital Stereo (IEC958) Input (sinks: 1, sources: 1, priority: 1355, available: yes)
		output:analog-surround-50: Analog Surround 5.0 Output (sinks: 1, sources: 0, priority: 1200, available: yes)
		output:analog-surround-50+input:analog-stereo: Analog Surround 5.0 Output + Analog Stereo Input (sinks: 1, sources: 1, priority: 1265, available: yes)
		output:analog-surround-50+input:iec958-stereo: Analog Surround 5.0 Output + Digital Stereo (IEC958) Input (sinks: 1, sources: 1, priority: 1255, available: yes)
		output:analog-surround-51: Analog Surround 5.1 Output (sinks: 1, sources: 0, priority: 1300, available: yes)
		output:analog-surround-51+input:analog-stereo: Analog Surround 5.1 Output + Analog Stereo Input (sinks: 1, sources: 1, priority: 1365, available: yes)
		output:analog-surround-51+input:iec958-stereo: Analog Surround 5.1 Output + Digital Stereo (IEC958) Input (sinks: 1, sources: 1, priority: 1355, available: yes)
		output:iec958-stereo: Digital Stereo (IEC958) Output (sinks: 1, sources: 0, priority: 5500, available: yes)
		output:iec958-stereo+input:analog-stereo: Digital Stereo (IEC958) Output + Analog Stereo Input (sinks: 1, sources: 1, priority: 5565, available: yes)
		output:iec958-stereo+input:iec958-stereo: Digital Stereo Duplex (IEC958) (sinks: 1, sources: 1, priority: 5555, available: yes)
		off: Off (sinks: 0, sources: 0, priority: 0, available: yes)
	Active Profile: output:analog-stereo+input:analog-stereo
	Ports:
		analog-input-mic: Microphone (priority: 8700, latency offset: 0 usec, available)
			Properties:
				device.icon_name = "audio-input-microphone"
			Part of profile(s): input:analog-stereo, output:analog-stereo+input:analog-stereo, output:analog-surround-21+input:analog-stereo, output:analog-surround-40+input:analog-stereo, output:analog-surround-41+input:analog-stereo, output:analog-surround-50+input:analog-stereo, output:analog-surround-51+input:analog-stereo, output:iec958-stereo+input:analog-stereo
		analog-input-linein: Line In (priority: 8100, latency offset: 0 usec, not available)
			Part of profile(s): input:analog-stereo, output:analog-stereo+input:analog-stereo, output:analog-surround-21+input:analog-stereo, output:analog-surround-40+input:analog-stereo, output:analog-surround-41+input:analog-stereo, output:analog-surround-50+input:analog-stereo, output:analog-surround-51+input:analog-stereo, output:iec958-stereo+input:analog-stereo
		iec958-stereo-input: Digital Input (S/PDIF) (priority: 0, latency offset: 0 usec)
			Part of profile(s): input:iec958-stereo, output:analog-stereo+input:iec958-stereo, output:analog-surround-21+input:iec958-stereo, output:analog-surround-40+input:iec958-stereo, output:analog-surround-41+input:iec958-stereo, output:analog-surround-50+input:iec958-stereo, output:analog-surround-51+input:iec958-stereo, output:iec958-stereo+input:iec958-stereo
		analog-output: Analog Output (priority: 9900, latency offset: 0 usec)
			Part of profile(s): output:analog-stereo, output:analog-stereo+input:analog-stereo, output:analog-stereo+input:iec958-stereo, output:analog-surround-21, output:analog-surround-21+input:analog-stereo, output:analog-surround-21+input:iec958-stereo, output:analog-surround-40, output:analog-surround-40+input:analog-stereo, output:analog-surround-40+input:iec958-stereo, output:analog-surround-41, output:analog-surround-41+input:analog-stereo, output:analog-surround-41+input:iec958-stereo, output:analog-surround-50, output:analog-surround-50+input:analog-stereo, output:analog-surround-50+input:iec958-stereo, output:analog-surround-51, output:analog-surround-51+input:analog-stereo, output:analog-surround-51+input:iec958-stereo
		analog-output-headphones: Headphones (priority: 9000, latency offset: 0 usec, not available)
			Properties:
				device.icon_name = "audio-headphones"
			Part of profile(s): output:analog-stereo, output:analog-stereo+input:analog-stereo, output:analog-stereo+input:iec958-stereo
		iec958-stereo-output: Digital Output (S/PDIF) (priority: 0, latency offset: 0 usec)
			Part of profile(s): output:iec958-stereo, output:iec958-stereo+input:analog-stereo, output:iec958-stereo+input:iec958-stereo
```
Please let me know if you need any further information.
Thank you

**Comment by ahkok** [comment] 2019-01-23 18:46
does `udevadm trigger` while the desktop is running make the sound cards appear? Please check using `pavucontrol`.

**Comment by rbharathkumar** [comment] 2019-01-24 02:35
Tried running the command `udevadm trigger`. But no change has been found.
Checked in pavucontrol as well. Have tried out various configurations.
Also is it just me or I don't think pavucontrol was available by default. I think it turned up only after I installed the PulseEffects application from the Software Center.

**Comment by rbharathkumar** [comment] 2019-01-25 07:11
Just wanted to update, that I am facing the same issue with the XFCE and KDE installs as well.

**Comment by rbharathkumar** [comment] 2019-01-28 03:34
Any Suggestion Guys ?

**Comment by gvancuts** [comment] 2019-01-28 13:48
I can reproduce this with Clear Linux as a Virtual Box guest on Fedora 29 (VirtualBox 6.0.2r128162). I have  another VM running Ubuntu 18.04 where audio works correctly (using PulseAudio as the back-end and emulating the AC97):
```
Audio:                       enabled (Driver: PulseAudio, Controller: AC97, Codec: STAC9700)
Audio playback:              enabled
Audio capture:               enabled
```

I tried changing the back-end to ALSA and the emulated card to Intel HD but that did not solve the problem in the Clear Linux guest and made it unstable in Ubuntu so sticking to these settings (at least for now).

Here is what `

Here is what `journalctl` tells me:
```
$ journalctl -b -t pulseaudio
-- Logs begin at Fri 2019-01-25 13:24:13 UTC, end at Mon 2019-01-28 13:27:25 UTC. --
Jan 28 13:26:40 clr-vm pulseaudio[387]: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
Jan 28 13:26:40 clr-vm pulseaudio[387]: [pulseaudio] alsa-util.c: Unable to set sw params: No such file or directory
Jan 28 13:26:40 clr-vm pulseaudio[387]: [pulseaudio] alsa-sink.c: Failed to set software parameters: No such file or directory
Jan 28 13:26:40 clr-vm pulseaudio[387]: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
Jan 28 13:26:40 clr-vm pulseaudio[387]: [pulseaudio] alsa-util.c: Unable to set sw params: No such file or directory
Jan 28 13:26:40 clr-vm pulseaudio[387]: [pulseaudio] alsa-source.c: Failed to set software parameters: No such file or directory
Jan 28 13:26:48 clr-vm pulseaudio[601]: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
Jan 28 13:26:48 clr-vm pulseaudio[601]: [pulseaudio] alsa-util.c: Unable to set sw params: No such file or directory
Jan 28 13:26:48 clr-vm pulseaudio[601]: [pulseaudio] alsa-sink.c: Failed to set software parameters: No such file or directory
Jan 28 13:26:48 clr-vm pulseaudio[601]: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
Jan 28 13:26:48 clr-vm pulseaudio[601]: [pulseaudio] alsa-util.c: Unable to set sw params: No such file or directory
Jan 28 13:26:48 clr-vm pulseaudio[601]: [pulseaudio] alsa-source.c: Failed to set software parameters: No such file or directory
Jan 28 13:27:05 clr-vm pulseaudio[601]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=2500
```

I have also collected the output of `pulseaudio -vvvv` if someone is interested to look at them (I have not yet done so and running out of time for today).

**Comment by rbharathkumar** [comment] 2019-01-28 15:22
Thank you very much @gvancuts for spending time and confirming that my sound issues not just limited to my VM. Hope someone would be by to help with this issue.

I am facing the same issue with all the three installs (Gnome, XFCE and KDE)

**Comment by gvancuts** [comment] 2019-02-05 13:37
I got it to work for me (under GNOME). The default kernel-lts config does not include the PCM timer interface:
```
config-4.19.19-415.lts:# CONFIG_SND_PCM_TIMER is not set
```
I added support for it, recompiled the LTS kernel and no I can see the audio output (and it works :-))

**Comment by rbharathkumar** [comment] 2019-02-05 14:37
That is amazing..Great Job.

Is it something only limited to GNOME ? because my XFCE and KDE VMs which incidentally were also on kernel-lts are also having the same issue.

Can you please let me know how I can replicate the same ?
Or I just need to update my system ?

**Comment by gvancuts** [comment] 2019-02-05 16:17
> That is amazing..Great Job.
> 
> Is it something only limited to GNOME ? because my XFCE and KDE VMs which incidentally were also on kernel-lts are also having the same issue.

I haven't tried XFCE and KDE but this is very likely to fix it for them too. The problem is a layer below those. PulseAudio itself was not able to play anything and that now works.

> 
> Can you please let me know how I can replicate the same ?

Here are the few steps I ran through to test this:
* Install the [Clear Linux tooling](https://clearlinux.org/documentation/clear-linux/guides/maintenance/autospec#install-tooling) (on a Clear Linux system)
* Clone the LTS kernel package: `make clone_linux-lts`
* Change to that folder (`cd packages/linux-lts`)
* Edit the `config` file; replace `# CONFIG_SND_PCM_TIMER is not set` by `CONFIG_SND_PCM_TIMER=y`
* Commit your changes
* `make bump` (so that the kernel you're about to compile has a higher release number than the one on your system)
* `make`
* Transfer the `linux-lts-blah-blah.x86_64.rpm` to your virtual machine
* Install this new kernel: `rpm -ivh --nodeps linux-lts-blah-blah.x86_64.rpm`
* Change your system to boot it next time: `sudo clr-boot-manager set-kernel <your new kernel>` (you can check what name to use from `sudo clr-boot-manager list-kernels`
* Reboot and test (and make sure you're indeed running the kernel you've recompiled)

> Or I just need to update my system ?

That will be possible (and much easier than the steps listed above :-)) once the engineering team enables that by default and the upstream repos have been updated. @ahkok or @miguelinux should be able to tell if/when that can happen.

**Comment by rbharathkumar** [comment] 2019-02-05 17:51
@gvancuts : Sounds Complex
But I plan to try it nevertheless. Your instructions are pretty detailed. Will get back to you if I get stuck somewhere. Normally how long does it take to compile the kernel ? I mean just the process alone ?

It is true, that it would be a lot easier if the engineering team would take the time to fix these issues, Maybe we would get lucky and hear from them ?

**Comment by rbharathkumar** [comment] 2019-02-05 17:56
@anselmolsm Thank you so much for your efforts in getting the KDE desktop polished.
I hope my bundle list was helpful.

As you mentioned it would do a whole lot of difference if the desktop bundles come with these packages included. I mean the absolute necessities like the one you had mentioned and the library ones like the pixbuf, gstreamer, the network libraries to have flatpak working..

Anyways looking forward to your response on the Plasma desktop post. Do let me know and I will try updating and test again/reinstall on a new VM.

Thanks :+1:

**Comment by gvancuts** [comment] 2019-02-05 22:37
> @gvancuts : Sounds Complex
> But I plan to try it nevertheless. Your instructions are pretty detailed. Will get back to you if I get stuck somewhere. Normally how long does it take to compile the kernel ? I mean just the process alone ?

That really depends on your machine, it can take a while. It took less than a couple of hours for me but I have no idea how much less since I started it and then went off and did something else for those couple of hours :-)

My system has an `Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz` with 32GB of RAM.

> 
> It is true, that it would be a lot easier if the engineering team would take the time to fix these issues, Maybe we would get lucky and hear from them ?

@miguelinux , what says you? ;)

**Comment by rbharathkumar** [comment] 2019-02-06 04:07
> That really depends on your machine

Oh my machine is nowhere nearly as powerful as yours.
A 5th generation i5 with 8 GB of RAM.

Anyways will wait for a reply from the Engineering Team or from one of the collaborators.
Or else would try doing it...

**Comment by fenrus75** [comment] 2019-02-06 04:17
I've made the suggested change in the kernels in question (main and LTS),
will be in tomorrow morning's build

**Comment by rbharathkumar** [comment] 2019-02-06 04:32
Wow...that was quick...thank you so much..
Will update, test and let you know.

**Comment by gvancuts** [comment] 2019-02-06 08:23
> I've made the suggested change in the kernels in question (main and LTS), will be in tomorrow morning's build

Thanks @fenrus75 

(@rbharathkumar , not sure what timezone you're in but be aware that the Clear Linux download website appears to be down at the moment, I have filed a ticket to get this resolved so bear with us a little)

**Comment by rbharathkumar** [comment] 2019-02-06 11:48
Thank you for the heads-up @gvancuts , I also noticed the same. The CDN site is indeed down.
Will try once it is back online.

**Comment by gvancuts** [comment] 2019-02-06 21:17
> Thank you for the heads-up @gvancuts , I also noticed the same. The CDN site is indeed down.
> Will try once it is back online.

The site is back up and running. The latest update available (27660) has the fix for audio (at least under GNOME). Feel free to try it out whenever you're ready.

**Comment by rbharathkumar** [comment] 2019-02-07 04:12
Hi all, created a new VM and installed the default GNOME desktop.
I confirm that we now have sound in the browsers and the output devices get listed as expected :+1: 
Great work guys :+1:

**Closed** 2019-02-19 03:54 UTC
Labels: bug
