### ISSUE TITLE
Problems starting gdm after minimal installation

### ISSUE THREAD

**Issue by Alec423** [clearlinux/distribution#210] opened 2018-09-21 20:51 UTC
I followed the steps detailed on the [bare metal install](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install) guide and the [create and enable a new userspace](https://clearlinux.org/documentation/clear-linux/guides/maintenance/enable-user-space) one. [EDIT: I also have tried the VMWare disk image installation] I tried them both on a bare metal compatible system and on VMware Player 14 and in both cases when I reach the `systemctl start gdm` step nothing happens

![gdm_not_working](https://user-images.githubusercontent.com/24482735/45905204-d6993b80-bdef-11e8-8a30-4bcbc1e8cd4c.png)

**Steps to reproduce the behavior**
1. Install the system following the aforementioned guides

**Expected behaviour**
The gdm interface should start and connect to the Xorg server

**Screenshots**
Xorg verbose output after trying to start it for the first time: 
![startx_not_working_first_start](https://user-images.githubusercontent.com/24482735/45905206-d731d200-bdef-11e8-9faa-6147ba4297be.png)

Xorg verbose output anfter trying to start it at subsequent times:
![startx_not_working](https://user-images.githubusercontent.com/24482735/45905205-d731d200-bdef-11e8-9b91-2479ac11d12f.png)

**Environment:**
 - Clear Linux OS version: 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
VERSION_ID=25140
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy" 
- Bundles: 
bootloader
c-basic
containers-basic
desktop
desktop-apps
desktop-assets
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
editors
emacs
ethtool
git
go-basic
iproute2
joe
kernel-native
koji
kvm-host
libX11client
mail-utils
mail-utils-dev
mixer
network-basic
network-basic-dev
openssh-server
openssl
os-clr-on-clr
os-core
os-core-dev
os-core-update
os-core-update-dev
os-installer
p11-kit
package-utils
perl-basic
perl-basic-dev
python2-basic
python3-basic
storage-utils
storage-utils-dev
sudo
sysadmin-basic
sysadmin-basic-dev
telemetrics
vim
web-server-basic
which
wpa_supplicant
xemacs

I also attach the [Xorg.0.log](https://github.com/clearlinux/distribution/files/2406997/Xorg.0.log)
 file for further troubleshooting

**Comment by Alec423** [comment] 2018-09-24 06:10
@puneetse I’m sorry, but I tried the preconfigured disk image too and gives the same problems

**Comment by puneetse** [comment] 2018-09-24 15:53
@Alec423 ah, thanks for trying and confirming.

**Comment by ahkok** [comment] 2018-09-24 17:40
Confirmed, this seems to be breaking on xwayland, which is crashing.

**Comment by ahkok** [comment] 2018-09-24 20:08
If you are seeing this issue *and* you have `Xwayland` errors in `journalctl`, you can try the following:

```
# cat /etc/gdm/custom.conf 
[daemon]
WaylandEnable=false
```

That will force gdm not to use Xwayland and may work around the issue (It did for me)

**Comment by Alec423** [comment] 2018-09-25 14:44
@ahkok In the base install there is nothing of such kind, the folder /etc/gdm/ isn't even present, let alone the config file to edit

**Comment by mrkz** [comment] 2018-09-25 14:52
@Alec423 yes, we ship empty `/etc/` due to [stateless](https://clearlinux.org/features/stateless), but you can safely do
```
# mkdir -p /etc/gdm

# cat > /etc/gdm/custom.conf << EOF
[daemon]
WaylandEnable=false
EOF
```

**Comment by miguelinux** [comment] 2018-09-25 14:56
> @ahkok In the base install there is nothing of such kind, the folder /etc/gdm/ isn't even present, let alone the config file to edit

You can create the missing directories and files to do user/admin configurations.

https://clearlinux.org/features/stateless

**Comment by Alec423** [comment] 2018-09-25 17:50
@mrkz unfortunately it still doesn’t work even after creating the folder and the conf file

**Comment by ahkok** [comment] 2018-09-25 17:54
@Alec423 make sure to restart your system. Can you post the output of `journalctl -b` somewhere (e.g. gist.github.com?) and include a link to it? Are you seeing `Illegal Instruction` anywhere?

**Comment by Alec423** [comment] 2018-09-25 18:41
@ahkok this is an extract from the complete log showing a typical boot + login + poweroff case, didn't find any `Illegal Instruction`

https://gist.github.com/Alec423/7fd9ee338a74cb72ddad54625f426d7a

**Comment by ahkok** [comment] 2018-09-25 18:48
Yeah, it seems the VMware virtual machine is a different error path and unrelated to the Illegal Instruction (it doesn't use Xwayland afaics, even)

**Comment by Alec423** [comment] 2018-09-25 18:51
@ahkok I don't have any powerful computer to install clearlinux quickly on and confront the journalctl; is this suggesting that both the VMWare installation and the bare metal one have the same gdm problem but generating from a different source?

**Comment by miguelinux** [comment] 2018-09-25 19:59
I got a coredump  when I use my laptop in lid and connected with external monitor

```
$ coredumpctl 
TIME                            PID   UID   GID SIG COREFILE  EXE
Tue 2018-09-25 14:45:57 CDT     713   311   311  11 error     /usr/bin/gnome-shell
Tue 2018-09-25 14:45:57 CDT     721   311   311   6 error     /usr/bin/Xwayland
```

BUT

When I set `/etc/gdm/custom.conf`, it works well.

**Comment by ahkok** [comment] 2018-09-25 21:35
different problem entirely.

**Comment by ahkok** [comment] 2018-10-04 19:45
`25400` solves the SIGILL problem. Other issues may remain, so, I'm keeping this bug open

**Comment by yakuizhao** [comment] 2018-10-15 01:56
Any progress about this issue?

**Comment by Mountainerd** [comment] 2018-10-30 03:53
Not sure if it's directly applicable here but the symptoms and error output look similar. Recently, when I did a minimal install, then installed the desktop, then tried to login, it barfed like this. Turns out the installer set the ownership on my home directory to root:root. Once I resolved that, errors went away,

**Comment by mrkz** [comment] 2019-04-05 16:52
@Alec423 could you please try to verify the VMware issue still persists? As far as I can see, we are providing `/usr/lib64/dri/vmwgfx_dri.so` (verified on CLR release **28610**). Otherwise we should be able to close this bug now.

Thanks!

**Closed** 2019-06-05 15:06 UTC
Labels: bug, desktop
