### ISSUE TITLE
Can't play H264 or GIFs on Firefox

### ISSUE THREAD

**Issue by mariojuniorjp** [clearlinux/distribution#654] opened 2019-05-01 22:34 UTC
**Describe the bug**
Can't play H264 videos or Gifs on Firefox. When trying to play videos in mp4 or gifs a "could not play" message appears. This happens on various sites like Twitter, Instagram, Imgur etc.

**To Reproduce**
1. Choose any H264 video or GIF 
2. Try to play
3. Doesn't play 

**Expected behavior**
The video or gif be played

**Screenshots**
![Captura de tela de 2019-05-01 19-27-34](https://user-images.githubusercontent.com/11687827/57046655-ad734000-6c47-11e9-9cd1-89623eb36629.png)

![Captura de tela de 2019-05-01 19-28-08](https://user-images.githubusercontent.com/11687827/57046662-b532e480-6c47-11e9-9ab7-98177111d24e.png)

![Captura de tela de 2019-05-01 19-30-33](https://user-images.githubusercontent.com/11687827/57046667-b9f79880-6c47-11e9-91ae-1a1663e41d40.png)

**Environment (please complete the following information):**

 - Clear Linux OS version: [`cat /usr/lib/os-release`]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29150
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]

NetworkManager
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
bootloader
c-basic
cheese
cloc
clr-network-troubleshooter
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
devpkg-base
devpkg-llvm
diffutils
docutils
dosfstools
dpdk
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
games
gdb
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
iperf
iproute2
iptables
joe
kbd
kernel-install
kernel-native
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
locales
mail-utils
make
man-pages
minetest
minetestserver
minicom
mutt
nasm
nautilus
net-tools
network-basic
nfs-utils
notmuch
openblas
openldap
openssh-server
openssl
openvswitch
os-core
os-core-legacy
os-core-update
os-core-webproxy
p11-kit
parallel
parted
patch
perl-basic
pmdk
polkit
powertop
procps-ng
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
samba
seahorse
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
syslinux
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
user-basic
valgrind
vim
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
znc
zsh
zstd

**Additional context**

Compiled ffmpeg git with "configure --shared" and installed but doensn't solve the problem.

**Comment by ahkok** [comment] 2019-05-02 16:08
Duplicate of #429

**Closed by ahkok** 2019-05-02 16:08 UTC
Labels: bug, new
