### ISSUE TITLE
virt-manager not working

### ISSUE THREAD

**Issue by JosePerezCarranza** [clearlinux/distribution#748] opened 2019-05-17 21:40 UTC
virt-manager is not working, giving a traceback  "ModuleNotFoundError: No module named 'gi'
"

$ sudo swupd bundle-add  virt-manager
$ sudo swupd bundle-add  virt-manager-gui
$ virt-manager
Traceback (most recent call last):
  File "/usr/share/virt-manager/virt-manager", line 29, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

==================
$sudo swupd info
Installed version: 29460
Version URL:       https://cdn-alt.download.clearlinux.org/update
Content URL:       https://cdn-alt.download.clearlinux.org/update

**Comment by puneetse** [comment] 2020-01-16 19:45
I'm closing this issue because the run requirement, pygobject is a runtime requirement for the virt-manager package and I cannot reproduce this on the latest Clear Linux build. If you are continuing to have to problem, please feel free to reopen!

**Closed by puneetse** 2020-01-16 19:45 UTC
Labels: bug
