### ISSUE TITLE
[BBT]missing tensorflow related modules

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1548] opened 2019-12-06 17:12 UTC
In  build 31820, we have some modules missed for tensorflow,

These are the errors
```
# (in test file bat-computer-vision-models-python-import_parallel.t, line 418)
#   `python -c "import tensorboard"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorboard'

# (in test file bat-computer-vision-models-python-import_parallel.t, line 424)
#   `python -c "import tensorflow"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorflow'


# (in test file bat-computer-vision-models-python-import_parallel.t, line 430)
#   `python -c "import tensorflow_core"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorflow_core'

# (in test file bat-machine-learning-tensorflow-python-import_parallel.t, line 364)
#   `python -c "import tensorboard"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorboard'

# (in test file bat-machine-learning-tensorflow-python-import_parallel.t, line 370)
#   `python -c "import tensorflow"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorflow'

# (in test file bat-machine-learning-tensorflow-python-import_parallel.t, line 376)
#   `python -c "import tensorflow_core"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorflow_core'

# (in test file bat-machine-learning-tensorflow-python-import_parallel.t, line 382)
#   `python -c "import tensorflow_estimator"' failed
# Traceback (most recent call last):
#   File "", line 1, in 
# ModuleNotFoundError: No module named 'tensorflow_estimator'

```

**Comment by phmccarty** [comment] 2019-12-12 00:07
The root cause for these issues was that tensorflow was broken with python3.8. The fixes landed in release `31870` -- also see #1553.

**Closed by phmccarty** 2019-12-12 00:07 UTC
Labels: bug
